### ISSUE TITLE
Parenthesis in IF expression always returns true

### ISSUE THREAD

**Issue by phedders** [arendst/Tasmota#14530] opened 2022-01-20 13:20 UTC
### PROBLEM DESCRIPTION

Program Version | 2022.01.3(prhother)
Compiled with:
#define USE_EXPRESSION                         // Add support for expression evaluation in rules (+3k2 code, +64 bytes mem)
#define SUPPORT_IF_STATEMENT                 // Add support for IF statement in rules (+4k2 code, -332 bytes mem)
#define SUPPORT_MQTT_EVENT                     // Support trigger event with MQTT subscriptions (+3k5 code)

Parenthesis in IF expressions in RULES are not working as I expect them to.
For example this does what I would expect:

12:53:02.274 CMD: rule3 ON Event#test DO IF (%value% > 2) publish stat/%topic%/test4 YES else publish stat/%topic%/test4 NO ENDIF ENDON
12:53:02.280 RUL: Stored uncompressed, would compress from 111 to 72 (-35%)
12:53:02.286 MQT: stat/LightsCoalStore/RESULT = {"Rule3":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":111,"Free":400,"Rules":"ON Event#test DO IF (%value% > 2) publish stat/%topic%/test4 YES else publish stat/%topic%/test4 NO ENDIF ENDON"}}
12:53:04.720 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:53:04.756 RUL: EVENT#TEST performs "IF (1 > 2) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:53:04.764 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:53:04.975 MQT: stat/LightsCoalStore/test4 = NO
12:53:05.628 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:53:05.664 RUL: EVENT#TEST performs "IF (2 > 2) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:53:05.672 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:53:05.883 MQT: stat/LightsCoalStore/test4 = NO
12:53:06.634 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:53:06.670 RUL: EVENT#TEST performs "IF (3 > 2) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:53:06.679 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:53:06.889 MQT: stat/LightsCoalStore/test4 = YES

But this expression always returns true:

12:53:58.377 CMD: rule3 ON Event#test DO IF (%value% > (1+1)) publish stat/%topic%/test4 YES else publish stat/%topic%/test4 NO ENDIF ENDON
12:53:58.383 RUL: Stored uncompressed, would compress from 115 to 77 (-33%)
12:53:58.388 MQT: stat/LightsCoalStore/RESULT = {"Rule3":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":115,"Free":396,"Rules":"ON Event#test DO IF (%value% > (1+1)) publish stat/%topic%/test4 YES else publish stat/%topic%/test4 NO ENDIF ENDON"}}
12:54:02.469 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:54:02.505 RUL: EVENT#TEST performs "IF (1 > (1+1)) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:54:02.514 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:54:02.722 MQT: stat/LightsCoalStore/test4 = YES
12:54:05.749 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:54:05.784 RUL: EVENT#TEST performs "IF (2 > (1+1)) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:54:05.792 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:54:06.000 MQT: stat/LightsCoalStore/test4 = YES
12:54:06.968 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:54:06.003 RUL: EVENT#TEST performs "IF (3 > (1+1)) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:54:07.001 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:54:07.209 MQT: stat/LightsCoalStore/test4 = YES
12:54:08.680 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
12:54:08.716 RUL: EVENT#TEST performs "IF (X > (1+1)) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
12:54:08.724 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
12:54:08.934 MQT: stat/LightsCoalStore/test4 = YES

The only difference is

IF (%value% > 2) 
IF (%value% > (1+1)) 

But that could be anything with the parentesis - this fails in the same way:
IF (%value% > (2)) 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____ Various Sonoffs and DIY modules
- [x] Tasmota binary firmware version number used: _____ 2022.01.03
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: _____OTA
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
13:13:42.069 CMD: Backlog Template; Module; GPIO 255
13:13:42.097 MQT: stat/LightsCoalStore/RESULT = {"NAME":"Sonoff Mini","GPIO":[33,3232,1,3200,160,1,1,1,224,288,1,1,161,1],"FLAG":0,"BASE":18}
13:13:42.318 MQT: stat/LightsCoalStore/RESULT = {"Module":{"0":"Sonoff Mini"}}
13:13:42.550 MQT: stat/LightsCoalStore/RESULT = {"GPIO0":{"33":"Button2"},"GPIO1":{"3232":"Serial Rx"},"GPIO2":{"0":"None"},"GPIO3":{"3200":"Serial Tx"},"GPIO4":{"160":"Switch1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"288":"Led1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"161":"Switch2"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
13:14:22.162 CMD: Backlog Rule1; Rule2; Rule3
13:14:22.181 RUL: Rule1 ON event#getvars DO publish stat/%topic%/OFFSETS AM:%mem1%/PM:%mem2%/rtime:%mem3% ENDON ON Rules#Timer=1 DO backlog Power 0; publish stat/%topic%/timer end ENDON ON switch1#state=1 DO backlog Power 1; RuleTimer1 %mem3% ENDON ON event#trigger DO if (%TIME% > 360 AND %TIME% < 1410 AND (%TIME% < (%SUNRISE%+%mem1%) OR %TIME% > (%SUNSET%-%mem2%))) Power 1; RuleTimer1 %mem3% endif ENDON ON event#timer DO if (%TIME% > 360 AND %TIME% < 1410 AND (%TIME% < (%SUNRISE%+%mem1%) OR %TIME% > (%SUNSET%-%mem2%))) Power
13:14:22.184 RUL: Rule1 +1; RuleTimer1 %value% endif ENDON
13:14:22.191 MQT: stat/LightsCoalStore/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":541,"Free":265,"Rules":"ON event#getvars DO publish stat/%topic%/OFFSETS AM:%mem1%/PM:%mem2%/rtime:%mem3% ENDON ON Rules#Timer=1 DO backlog Power 0; publish stat/%topic%/timer end ENDON ON switch1#state=1 DO backlog Power 1; RuleTimer1 %mem3% ENDON ON event#trigger DO if (%TIME% > 360 AND %TIME% < 1410 AND (%TIME% < (%SUNRISE%+%mem1%) OR %TIME% > (%SUNSET%-%mem2%))) Power 1; RuleTimer1 %mem3% endif ENDON ON event#timer DO if (%TIME% > 360 AND %TIME% < 1410 AND (%TIME% < (%SUNRISE%+%mem1%) OR %TIME% > (%SUNSET%-%mem2%))) Power 1; RuleTimer1 %value% endif ENDON"}}
13:14:22.418 MQT: stat/LightsCoalStore/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
13:14:22.670 MQT: stat/LightsCoalStore/RESULT = {"Rule3":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":113,"Free":398,"Rules":"ON Event#test DO IF (%value% > (2)) publish stat/%topic%/test4 YES else publish stat/%topic%/test4 NO ENDIF ENDON"}}
13:14:25.634 MQT: tele/LightsCoalStore/STATE = {"Time":"2022-01-20T13:14:25","Uptime":"1T01:40:17","UptimeSec":92417,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":7,"POWER":"OFF","Wifi":{"AP":2,"SSId":"W0W","BSSId":"86:2A:A8:11:21:C9","Channel":13,"Mode":"11n","RSSI":28,"Signal":-86,"LinkCount":4,"Downtime":"0T00:00:18"}}
13:14:25.645 MQT: tele/LightsCoalStore/SENSOR = {"Time":"2022-01-20T13:14:25","Switch1":"ON","Switch2":"ON"} (retained)

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
13:14:45.381 CMD: status 0
13:14:45.388 MQT: stat/LightsCoalStore/STATUS = {"Status":{"Module":0,"DeviceName":"LightsCoalStore","FriendlyName":["LightsCoalStore"],"Topic":"LightsCoalStore","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":1,"PowerRetain":1,"InfoRetain":0,"StateRetain":0}}
13:14:45.413 MQT: stat/LightsCoalStore/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://xtasmota/tasmota-other.bin","RestartReason":"Software/System restart","Uptime":"1T01:40:37","StartupUTC":"2022-01-19T11:34:08","Sleep":50,"CfgHolder":4617,"BootCount":35,"BCResetTime":"2020-07-08T08:57:20","SaveCount":49380,"SaveAddress":"FA000"}}
13:14:45.436 MQT: stat/LightsCoalStore/STATUS2 = {"StatusFWR":{"Version":"2022.01.3(prhother)","BuildDateTime":"2022-01-19T11:00:47","Boot":7,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"426/699"}}
13:14:45.456 MQT: stat/LightsCoalStore/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["x","x"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00028229","2805C80001000600003C5A0A000000000000","00000280","00006000","00004000"]}}
13:14:45.484 MQT: stat/LightsCoalStore/STATUS4 = {"StatusMEM":{"ProgramSize":591,"Free":412,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FCAC787","04368001","000000C7","010000C0","40007881","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,8,9,10,12,16,18,19,20,21,22,24,26,29,37,45","Sensors":"1,2,3,4,5,6"}}
13:14:45.507 MQT: stat/LightsCoalStore/STATUS5 = {"StatusNET":{"Hostname":"LightsCoalStore","IPAddress":"x","Gateway":"x","Subnetmask":"255.255.255.0","DNSServer1":"x","DNSServer2":"0.0.0.0","Mac":"D8:F1:5B:83:E2:5A","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
13:14:45.525 MQT: stat/LightsCoalStore/STATUS6 = {"StatusMQT":{"MqttHost":"rabbit","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_83E25A","MqttUser":"x","MqttCount":7,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
13:14:45.546 MQT: stat/LightsCoalStore/STATUS7 = {"StatusTIM":{"UTC":"2022-01-20T13:14:45","Local":"2022-01-20T13:14:45","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+00:00","Sunrise":"07:34","Sunset":"16:27"}}
13:14:45.566 MQT: stat/LightsCoalStore/STATUS10 = {"StatusSNS":{"Time":"2022-01-20T13:14:45","Switch1":"ON","Switch2":"ON"}}
13:14:45.588 MQT: stat/LightsCoalStore/STATUS11 = {"StatusSTS":{"Time":"2022-01-20T13:14:45","Uptime":"1T01:40:37","UptimeSec":92437,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":7,"POWER":"OFF","Wifi":{"AP":2,"SSId":"x","BSSId":"x","Channel":13,"Mode":"11n","RSSI":24,"Signal":-88,"LinkCount":4,"Downtime":"0T00:00:18"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
13:15:54.394 CMD: weblog 4
13:15:54.400 MQT: stat/LightsCoalStore/RESULT = {"WebLog":4}
13:15:55.130 CFG: Saved to flash at F9, Count 49381, Bytes 4096
13:15:57.945 SRC: MQTT
13:15:57.947 CMD: Grp 0, Cmnd 'EVENT', Idx 1, Len 6, Data 'test=1'
13:15:57.954 MQT: stat/LightsCoalStore/RESULT = {"Event":"Done"}
13:15:57.989 RUL: EVENT#TEST performs "IF (1 > (2)) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF"
13:15:57.991 SRC: Rule
13:15:57.993 CMD: Grp 0, Cmnd 'IF', Idx 1, Len 97, Data '(1 > (2)) publish stat/LightsCoalStore/test4 YES else publish stat/LightsCoalStore/test4 NO ENDIF'
13:15:57.000 MQT: stat/LightsCoalStore/RESULT = {"If":"Done"}
13:15:58.202 SRC: Backlog
13:15:58.205 CMD: Grp 0, Cmnd 'PUBLISH', Idx 1, Len 30, Data 'stat/LightsCoalStore/test4 YES'
13:15:58.209 MQT: stat/LightsCoalStore/test4 = YES


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Please see above

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

I expect that sending event test=1 should result in NO because 1 is not > (2) - but I get YES.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by phedders** [comment] 2022-01-20 13:21
I asked about this in Discord as well:
https://discord.com/channels/479389167382691863/490244847568158751/933709820073213992

Also forgot to add my thanks for Tasmota - it is *amazing* code. I have around 60 devices that use it here and around our church building.

**Comment by sfromis** [comment] 2022-01-20 16:40
Even simpler: Are arithmetic expressions supported as part of logical expressions?

**Comment by phedders** [comment] 2022-01-20 16:43
I think my last paste above shows that arithmetic **is** supported in expressions --  (%value% < 5+5) does as expected assuming + has greater priority than the logical test <.

It is only when parenthesis are added inside the logical expression that I have problems... I think!

**Comment by sfromis** [comment] 2022-01-20 16:51
As the outcome of that last test does not depend on getting to the value 10, it does not confirm arithmetic to be supported. In general, things not supported gives no error messages, just "partial execution" without clear results.

**Comment by phedders** [comment] 2022-01-21 11:04
@sfromis Could you explain what you mean by "does not depend on getting to the value 10" ?

I'm probably being a bit slow - but the test is just doing a comparison with a calculated value of 10 and works correctly or at least as I expected it to with expected affinity rules, so basic arithmetic appears to be working - unless the arithmetic is parenthesised.
I would love to be shown that I'm doing something daft (well sort of...) because it would mean there does not need to a fix in the code :)

**Comment by barbudor** [comment] 2022-01-21 11:07
As you are using values below 5 or higher than 10  you don't prove if the actual comparison is done against 5 or against 5+5
You need to test with a value in between 5 and 10

**Comment by sfromis** [comment] 2022-01-21 11:28
What I mean is that it would be possible for your test case `(1 < 5+5)` to match without the addition being performed, in case of the comparison working out as `1 < 5` and then `+5` ignored due to it not being understood. 
A better test strategy would be `(2 < 1+3)`, which will give different outcomes depending on the addition done or not.

**Comment by phedders** [comment] 2022-01-21 11:38
@sfromis Ahha! I understand now. However I think the arithmetic question is getting away from the core problem somewhat but for completeness, using equality for simplicity:

     rule3 on event#test do if (%value% == 1+3) publish %topic/test YES endif endon

does as you would expect:

11:33:33.299 CMD: event test=0
11:33:33.355 RUL: EVENT#TEST performs "if (0 == 1+3) publish %topic/test YES endif"

11:33:36.400 CMD: event test=1
11:33:36.460 RUL: EVENT#TEST performs "if (1 == 1+3) publish %topic/test YES endif"

11:33:39.589 CMD: event test=2
11:33:39.649 RUL: EVENT#TEST performs "if (2 == 1+3) publish %topic/test YES endif"

11:33:42.477 CMD: event test=3
11:33:42.537 RUL: EVENT#TEST performs "if (3 == 1+3) publish %topic/test YES endif"

11:33:45.161 CMD: event **test=4**
11:33:45.220 RUL: EVENT#TEST performs "if (4 == 1+3) publish %topic/test YES endif"
11:33:45.440 MQT: %topic/test = **YES**

11:33:47.940 CMD: event test=5
11:33:47.997 RUL: EVENT#TEST performs "if (5 == 1+3) publish %topic/test YES endif"


**Now with**
rule3 on event#test do if (%value% == **(1+3)**) publish %topic/test YES endif endon

11:35:50.649 CMD: event test=1
11:35:50.710 RUL: EVENT#TEST performs "if **(1 == (1+3))** publish %topic/test YES endif"
11:35:50.930 MQT: %topic/test = **YES**

11:35:57.235 CMD: event test=2
11:35:57.299 RUL: EVENT#TEST performs "if **(2 == (1+3))** publish %topic/test YES endif"
11:35:57.517 MQT: %topic/test = **YES**

11:36:00.122 CMD: event test=3
11:36:00.182 RUL: EVENT#TEST performs "if **(3 == (1+3))** publish %topic/test YES endif"
11:36:00.397 MQT: %topic/test = **YES**

11:36:02.553 CMD: event test=4
11:36:02.612 RUL: EVENT#TEST performs "if **(4 == (1+3))** publish %topic/test YES endif"
11:36:02.829 MQT: %topic/test = **YES**

11:36:04.933 CMD: event test=5
11:36:04.993 RUL: EVENT#TEST performs "if **(5 == (1+3))** publish %topic/test YES endif"
11:36:05.211 MQT: %topic/test = **YES**

Those should definately **not** all return YES indicating that the expression was TRUE. Only one of those was correct.

**Comment by sfromis** [comment] 2022-01-21 12:19
To try to simplify again... Your original case was:
`(%TIME% > 360 AND %TIME% < 1410 AND (%TIME% < (%SUNRISE%+%mem1%) OR %TIME% > (%SUNSET%-%mem2%)))`

My repeated response is that all comparisons should be wrapped in (), and you are trying to wrap arithmetic expressions in superfluous (), and then see it as a problem that you cannot make that work.

If my assumption about where to place () is correct, you should have used:
`((%TIME% > 360) AND (%TIME% < 1410) AND`
`((%TIME% < %SUNRISE%+%mem1%) OR (%TIME% > %SUNSET%-%mem2%)))`

() around each comparison but not around each arithmetic expression. The latter part seems confirmed by your tests, arithmetic seems to work ok without you "obscuring" it with ().

**Comment by phedders** [comment] 2022-01-21 12:28
@sfromis Wow. It seems you've hit the nail on the head for my use case! As we discussed previously I did have () around all the logic previously but also around the arithmetic evaluations 'for completeness'.

So you've got me a working solution for which I am very grateful.

I think it is still a bug that the 'extra' () are not nullified/optimised away? At least it breaks the "do whats obvious" rule IMHO. If not considered fixable or desirable to fix - I can close the ticket - but perhaps a note in the docs would be helpful for the next poor sucker! :)

**Comment by sfromis** [comment] 2022-01-21 12:40
The "do whats obvious" does not apply when it comes to Tasmota commands or rules. The parsing has been optimized to be as simple as feasible, meaning that you cannot treat it as a programming language where you have freedom to embellish the syntax within a general framework.

**Comment by phedders** [comment] 2022-01-21 16:34
Thanks @sfromis  - It seems to be that way at the moment - but not always:

16:31:07.275 CMD: var9=5+2
16:31:07.283 MQT: stat/LightsCoalStore/RESULT = {"Var9":"7.000"}
16:31:13.948 CMD: var9=(5+2)
16:31:13.956 MQT: stat/LightsCoalStore/RESULT = {"Var9":"7.000"}
16:31:18.328 CMD: var9=(5+3)
16:31:18.336 MQT: stat/LightsCoalStore/RESULT = {"Var9":"8.000"}
16:31:25.895 CMD: var9=(5+(4))
16:31:25.903 MQT: stat/LightsCoalStore/RESULT = {"Var9":"9.000"}

The parser there seems to do what I was expected - perhaps it is a different parser although for compact code I assumed it would be the same one.

So the question is - should the documentation be updated (I can give that a go) or should this ticket stay for a code tweak to fix the false TRUE?

**Comment by sfromis** [comment] 2022-01-21 17:14
> ( ) (parentheses can be used to explicitly control the order of operations)
And you are not trying to control the order of operations.

The parsing situation within a logical expression is much more complex than in a standalone expression in a `var` command, as the parser has too look for () in the meaning of controlling the logical expressions. I'm not trying to say what "should" be done, just observing the complexities of the situation, and how "whats obvious" *really* does not apply to Tasmota due to the constraints of doing as much as possible on ESP8266.

**Comment by ascillato2** [comment] 2022-01-24 13:15
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by phedders** [comment] 2022-01-24 13:16
Thanks everyone :)

**Closed by ascillato2** 2022-01-24 13:15 UTC
Labels: troubleshooting
