### ISSUE TITLE
Compile error framework not found 

### ISSUE THREAD

**Issue by kugelkopf123** [arendst/Tasmota#9254] opened 2020-09-06 18:45 UTC
### PROBLEM DESCRIPTION
PlatformIO does not compile because it says "https://github.com/Jason2866/platform-espressif8266/releases/download/2.9.0/framework-arduinoespressif8266-3.20900.0.tar.gz"
cant find.

Error in Platformio Console:
```
Processing tasmota (platform: espressif8266@2.6.2; framework: arduino; board: esp01_1m)
----------------------------------------------------------------------------------------------------------------------------------------
PackageManager: Installing framework-arduinoespressif8266 @ *
git version 2.17.2 (Apple Git-113)
Cloning into '/Volumes/Macintosh SD/Users/christopher/.platformio/packages/_tmp_installing-qcFuLd-package'...
remote: Repository not found.
fatal: repository 'https://github.com/jason2866/framework-arduinoespressif8266/' not found
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/jason2866/framework-arduinoespressif8266', '/Volumes/Macintosh SD/User/christopher/.platformio/packages/_tmp_installing-qcFuLd-package']]
The terminal process "platformio 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

Platformio_override.ini:

```
; ***  Example PlatformIO Project Configuration Override File   ***
; ***  Changes done here override settings in platformio.ini    ***
;
; *****************************************************************
; ***  to activate rename this file to platformio_override.ini  ***
; *****************************************************************
;
; Please visit documentation for the options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[platformio]
extra_configs = platformio_tasmota_cenv.ini

; *** Build/upload environment
default_envs =
; *** Uncomment the line(s) below to select version(s)
                tasmota
;                tasmota-debug
;                tasmota-ircustom
;                tasmota-minimal
;                tasmota-lite
;                tasmota-knx
;                tasmota-sensors
;                tasmota-display
;                tasmota-zbbridge
;                tasmota-ir
;                tasmota32
;                tasmota32-webcam
;                tasmota32-minimal
;                tasmota32-lite
;                tasmota32-knx
;                tasmota32-sensors
;                tasmota32-display
;                tasmota32-ir
;                tasmota32-ircustom


[common]
platform                  = ${core.platform}
platform_packages         = ${core.platform_packages}
build_unflags             = ${core.build_unflags}
build_flags               = ${core.build_flags}
; *** Optional Debug messages
;                            -DDEBUG_TASMOTA_CORE
;                            -DDEBUG_TASMOTA_DRIVER
;                            -DDEBUG_TASMOTA_SENSOR

; set CPU frequency to 80MHz (default) or 160MHz
;board_build.f_cpu         = 160000000L

; set Flash chip frequency to 40MHz (default), 20MHz, 26Mhz, 80Mhz
;board_build.f_flash       = 20000000L
;board_build.f_flash       = 26000000L
;board_build.f_flash       = 80000000L

; *** Upload Serial reset method for Wemos and NodeMCU
upload_port               = COM5

extra_scripts             = ${scripts_defaults.extra_scripts}
;                            pio/obj-dump.py

; *** Upload file to OTA server using SCP
;upload_port               = user@host:/path
;extra_scripts             = ${scripts_defaults.extra_scripts}
;                            pio/strip-floats.py
;                            pio/sftp-uploader.py

; *** Upload file to OTA server in folder api/arduino using HTTP
;upload_port               = domus1:80/api/upload-arduino.php
;extra_scripts             = ${scripts_defaults.extra_scripts}
;                            pio/strip-floats.py
;                            pio/http-uploader.py

[core]
; Activate only (one set) if you want to override the standard core defined in platformio.ini !!!

;platform                  = ${tasmota_stage.platform}
;platform_packages         = ${tasmota_stage.platform_packages}
;build_unflags             = ${tasmota_stage.build_unflags}
;build_flags               = ${tasmota_stage.build_flags}

;platform                  = ${core_stage.platform}
;platform_packages         = ${core_stage.platform_packages}
;build_unflags             = ${core_stage.build_unflags}
;build_flags               = ${core_stage.build_flags}


[tasmota_stage]
; *** Esp8266 core for Arduino version Tasmota stage
platform                  = espressif8266@2.6.2
platform_packages         = jason2866/framework-arduinoespressif8266
build_unflags             = ${esp_defaults.build_unflags}
build_flags               = ${esp82xx_defaults.build_flags}

; *********** Alternative Options, enable only if you know exactly what you do ********
; NONOSDK221
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK221
; NONOSDK22x_190313
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190313
; NONOSDK22x_191024 = 2.2.1+111-dev(5ab15d1)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191024
; NONOSDK22x_191105 = 2.2.1+113-dev(bb83b9b)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191105
; NONOSDK22x_191122 = 2.2.1+119-dev(a58da79)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191122
; NONOSDK3V0 (known issues)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK3
; lwIP 1.4
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH
; lwIP 2 - Low Memory
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
; lwIP 2 - Higher Bandwidth
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
; lwIP 2 - Higher Bandwidth Low Memory no Features
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY_LOW_FLASH
; VTABLES in Heap
;                            -DVTABLES_IN_DRAM
; VTABLES in IRAM
;                            -DVTABLES_IN_IRAM
; Exception code in firmware /needs much space!
;                           -fexceptions
;                           -lstdc++-exc

[core_stage]
; *** Esp8266 core version. Tasmota stage or Arduino stage version. Built with GCC 10.1 toolchain
platform                  = espressif8266@2.6.2
platform_packages         = framework-arduinoespressif8266 @ https://github.com/Jason2866/platform-espressif8266/releases/download/2.9.0/framework-arduinoespressif8266-3.20900.0.tar.gz
                            ;framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git
                            toolchain-xtensa @ ~2.100100.0
build_unflags             = ${esp_defaults.build_unflags}
                            -Wswitch-unreachable
build_flags               = ${esp82xx_defaults.build_flags}
                            -Wno-switch-unreachable

; *********** Alternative Options, enable only if you know exactly what you do ********
; NONOSDK221
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK221
; NONOSDK22x_190313
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190313
; NONOSDK22x_191024 = 2.2.1+111-dev(5ab15d1)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191024
; NONOSDK22x_191105 = 2.2.1+113-dev(bb83b9b)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191105
; NONOSDK22x_191122 = 2.2.1+119-dev(a58da79)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191122
; NONOSDK3V0 (known issues)
;                            -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK3
; lwIP 2 - Low Memory
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
; lwIP 2 - Higher Bandwidth
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
; lwIP 2 - Higher Bandwidth Low Memory no Features
;                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY_LOW_FLASH
; VTABLES in Heap
;                            -DVTABLES_IN_DRAM
; VTABLES in IRAM
;                            -DVTABLES_IN_IRAM
; Exception code in firmware /needs much space!
;                           -fexceptions
;                           -lstdc++-exc


; *** Debug version used for PlatformIO Home Project Inspection
[env:tasmota-debug]
build_type                = debug
build_unflags             = ${esp_defaults.build_unflags}
build_flags               = ${esp82xx_defaults.build_flags}
                            -Wstack-usage=300

```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: Latest Dev 
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: PlatformIO Core4.3.4 Home 3.2.3
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Download Tasmota Dev Branch. Rename user_config_override_sample.h to user_config_override.h and rename platformio_override_sample.h to platformio_override.h

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by eku** [comment] 2020-09-06 18:54
Yes, I can confirm that.

**Comment by Jason2866** [comment] 2020-09-06 18:56
Update to latest Platformio Release v.5.0

**Comment by kugelkopf123** [comment] 2020-09-06 19:58
OK. For ESP8266 does it work. As far as I see. But for ESP32 not. 

```
*** use provided user_config_override.h as planned ***
*** [tasmota/StackThunk_light.cpp] /Volumes/Macintosh SD/Benutzer/christopherfleuth/Downloads/Github/Tasmota/.pioenvs/tasmota32/.sconsign27.dblite: No such file or directory
===================================================== [FAILED] Took 26.15 seconds =====================================================

Environment    Status    Duration
-------------  --------  ------------
tasmota32      FAILED    00:00:26.147
================================================ 1 failed, 0 succeeded in 00:00:26.147 ================================================
The terminal process "platformio 'run', '--environment', 'tasmota32'" terminated with exit code: 1.
```

**Comment by eku** [comment] 2020-09-07 05:32
> Update to latest Platformio Release v.5.0
How do you know if the error message is not appropriate?

**Comment by kugelkopf123** [comment] 2020-09-07 10:02
Tried the ESP8266 with a fresh install of vsCode, Platformio core 5 and TasmotaDevBranch Download on another MAC.
I havent changed anything(nothing in user_config_override.h or platformio_override.ini). Just downloaded it, en tried to compile. 
Instantly get this Error while building for esp8266:

```
> Executing task: platformio run --environment tasmota-DE <

Processing tasmota-DE (platform: espressif8266@2.6.2; framework: arduino; board: esp01_1m)
-------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 (2.6.2) > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 2.7.4+1 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Converting tasmota.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 83 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <BearSSL> 0.6
|-- <Adafruit CCS811 Library> 1.0.0
|   |-- <Wire> 1.0
|-- <Adafruit MAX31865 library> 1.0.1
|   |-- <SPI> 1.0
|-- <Adafruit MCP9808 Library> 1.1.2
|   |-- <Wire> 1.0
|-- <Adafruit SGP30 Sensor> 1.2.0
|   |-- <Wire> 1.0
|-- <Adafruit VEML7700 Library> 1.0.0
|   |-- <Adafruit BusIO> 1.0.10
|   |   |-- <Wire> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <ESP8266Audio> 1.5.0
|   |-- <SPI> 1.0
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <LittleFS(esp8266)> 0.1.0
|   |-- <SD(esp8266)> 2.0.0
|   |   |-- <SDFS> 0.1.0
|   |   |   |-- <SPI> 1.0
|   |   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |   |-- <SPI> 1.0
|   |-- <SDFS> 0.1.0
|   |   |-- <SPI> 1.0
|   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |-- <SPI> 1.0
|   |-- <ESP8266SdFat> 1.1.0
|   |   |-- <SPI> 1.0
|-- <I2Cdevlib-Core>
|   |-- <Wire> 1.0
|-- <LibTeleinfo> 1.1.3
|-- <I2Cdevlib-MPU6050>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <Mutichannel_Gas_Sensor> 0.0.1
|   |-- <Wire> 1.0
|-- <ArduinoNTPd>
|   |-- <ESP8266WiFi> 1.0
|-- <OpenTherm Library> 0.9.0
|-- <SD(esp8266)> 2.0.0
|   |-- <SDFS> 0.1.0
|   |   |-- <SPI> 1.0
|   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |-- <SPI> 1.0
|-- <UdpListener> 1.0
|-- <VL53L0X> 1.0.2
|   |-- <Wire> 1.0
|-- <C2Programmer> 1.0.0
|-- <cc1101>
|   |-- <SPI> 1.0
|-- <A4988_Stepper> 0.0.1
|-- <Adafruit GFX Library> 1.5.6
|   |-- <SPI> 1.0
|-- <Adafruit ILI9341> 1.2.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <Adafruit LED Backpack Library> 1.1.6
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <Adafruit_SH1106-gemu-1.0>
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <Adafruit SSD1306> 1.3.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|-- <Adafruit_TSL2591_Library>
|   |-- <Wire> 1.0
|-- <ArduinoJson> 5.13.4
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <Arduino ST7789 Library> 0.9.5
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266HTTPClient> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266SAM> 1.0
|   |-- <ESP8266Audio> 1.5.0
|   |   |-- <SPI> 1.0
|   |   |-- <ESP8266HTTPClient> 1.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <LittleFS(esp8266)> 0.1.0
|   |   |-- <SD(esp8266)> 2.0.0
|   |   |   |-- <SDFS> 0.1.0
|   |   |   |   |-- <SPI> 1.0
|   |   |   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |   |   |-- <SPI> 1.0
|   |   |-- <SDFS> 0.1.0
|   |   |   |-- <SPI> 1.0
|   |   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |   |-- <SPI> 1.0
|   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |-- <SPI> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266httpUpdate> 1.3
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <AT24C256>
|   |-- <Wire> 1.0
|-- <FT5206_Library> 1.0.0
|   |-- <Wire> 1.0
|-- <FrogmoreScd30>
|   |-- <Wire> 1.0
|-- <ILI9488> 1.0.2
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <IRremoteESP8266> 2.7.10
|-- <KeeloqLib> 1.1
|-- <LOLIN_HP303B> 1.0.0
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <LinkedList>
|-- <LiquidCrystal_I2C>
|   |-- <Wire> 1.0
|-- <LittleFS(esp8266)> 0.1.0
|-- <NeoPixelBus> 2.5.0
|   |-- <SPI> 1.0
|-- <NewPing> 1.9.1
|-- <PubSubClient> 2.7
|-- <RA8876> 1.0.2
|   |-- <SPI> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|-- <rc-switch> 2.6.2
|-- <RF24> 1.3.3
|   |-- <SPI> 1.0
|-- <SPI> 1.0
|-- <SSD3115> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <TasmotaModbus> 1.2.0
|   |-- <TasmotaSerial> 3.1.0
|-- <TasmotaSerial> 3.1.0
|-- <Ticker> 1.0
|-- <Joba_Tsl2561> 2.0.10
|   |-- <Wire> 1.0
|-- <Wire> 1.0
|-- <base64> 1.1.1
|-- <BME680_driver-bme680_v3.5.9>
|-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <ESP KNX IP Library> 0.5.2
|   |-- <EEPROM> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <HPMA115S0 Arduino Library> 1.0.0
|-- <Unishox Compressor Decompressor highly customized and optimized for ESP8266 and Tasmota> 1.0
Building in release mode
*** use provided user_config_override.h as planned ***
Compiling .pioenvs/tasmota-DE/src/StackThunk_light.cpp.o
In file included from tasmota/my_user_config.h:820:0,
                 from tasmota/StackThunk_light.cpp:28:
tasmota/user_config_override.h:24:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pioenvs/tasmota-DE/src/WiFiClientSecureLightBearSSL.cpp.o
In file included from tasmota/my_user_config.h:820:0,
                 from tasmota/WiFiClientSecureLightBearSSL.cpp:23:
tasmota/user_config_override.h:24:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pioenvs/tasmota-DE/src/tasmota.ino.cpp.o
Generating LD script .pioenvs/tasmota-DE/ld/local.eagle.app.v6.common.ld
Compiling .pioenvs/tasmota-DE/lib640/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/tasmota-DE/lib640/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFi.cpp.o
In file included from tasmota/my_user_config.h:820:0,
                 from /Users/christopher/Downloads/Tasmota-development-2/tasmota/tasmota.ino:41:
tasmota/user_config_override.h:24:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Assembler messages:
Fatal error: can't create .pioenvs/tasmota-DE/lib640/ESP8266WiFi/BearSSLHelpers.cpp.o: No such file or directory
*** [.pioenvs/tasmota-DE/lib640/ESP8266WiFi/BearSSLHelpers.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFiAP.cpp.o: No such file or directory
*** [.pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFiAP.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o: No such file or directory
*** [.pioenvs/tasmota-DE/lib640/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pioenvs/tasmota-DE/src/tasmota.ino.cpp.o: No such file or directory
*** [.pioenvs/tasmota-DE/src/tasmota.ino.cpp.o] Error 1
FileNotFoundError: [Errno 2] No such file or directory: '/Users/christopher/Downloads/Tasmota-development-2/.pioenvs/tasmota-DE/.sconsign37.tmp':
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1391:
    _exec_main(parser, values)
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1355:
    _main(parser)
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1126:
    nodes = _build_targets(fs, options, targets, target_top)
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1329:
    jobs.run(postfunc = jobs_postfunc)
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Job.py", line 113:
    postfunc()
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1326:
    SCons.SConsign.write()
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/SConsign.py", line 114:
    syncmethod()
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 130:
    f = self._open(self._tmp_name, "wb", self._mode)
Exception ignored in: <function dblite.__del__ at 0x100ec9200>
Traceback (most recent call last):
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 126, in __del__
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 123, in close
  File "/Users/christopher/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 130, in sync
FileNotFoundError: [Errno 2] No such file or directory: '/Users/christopher/Downloads/Tasmota-development-2/.pioenvs/tasmota-DE/.sconsign37.tmp'
==================================================== [FAILED] Took 12.14 seconds ====================================================

Environment    Status    Duration
-------------  --------  ------------
tasmota-DE     FAILED    00:00:12.139
=============================================== 1 failed, 0 succeeded in 00:00:12.139 ===============================================
The terminal process "platformio 'run', '--environment', 'tasmota-DE'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
 
```

BTW on this Mac same problem with the ESP32.

**Comment by Jason2866** [comment] 2020-09-07 12:42
The Install and Setup from your PlatformIO is complete and successfull
![image](https://user-images.githubusercontent.com/24528715/92388709-06929400-f118-11ea-98ae-c63404d73380.png)
It does run on MAC. Our zigbee developer @s-hadinger  does use a MAC too. He has no issue

**Comment by Jason2866** [comment] 2020-09-07 12:48
Delete folder `tool-scons`. You have a old version. The actual is `tool-scons @ 4.40001.0`
If this doesnt help delete the complete folder `.platformio` with ALL subfolders.

**Comment by eku** [comment] 2020-09-07 13:19
The update to version 5.0 has indeed fixed the problems, at least for me.

**Comment by Jason2866** [comment] 2020-09-07 13:30
Anyway. The issue is NOT Tasmota related. Please close this issue.
If the issue is still there for you please open a issue in platformio github.

**Closed** 2020-09-07 13:55 UTC
Labels: awaiting feedback, troubleshooting

**Comment by kugelkopf123** [comment] 2020-09-07 14:14
If I delete the .platformio folder in my home directory, the next time I compile (ESP32), the outdated version will be installed again. 
Only the packages/tools-scons folder needs to be deleted from the .platformio folder. The next time you compile, the latest version will be loaded. 
Thanks for your help!

**Comment by kugelkopf123** [comment] 2020-09-08 07:43
@ascillato2 
There is still this problem left:
`*** [tasmota/StackThunk_light.cpp] /Volumes/Macintosh SD/Benutzer/christopher/Downloads/Github/Tasmota/.pioenvs/tasmota32-DE/.sconsign37.dblite: No such file or directory
`
And by the way, its not possible to "update" to 4.0.4.
Perhaps you could have a look into your .platformio Folder. In my i find tools-scons/scons-local-4.0.1 and i cant do anything on this. Everytime i try to build for esp32 it gets overwritten with this version. 
Btw. Tried latest Dev this morning,too. Same result.

**Comment by Jason2866** [comment] 2020-09-08 13:28
@kugelkopf123  the issue is closed correctly. The issue you have is not caused from Tasmota.
The Problem you have is PlatformIO related. You can try latest Tasmota development version. I have updated the espressif32 platformio framework to latest 2.0.0. version. Maybe it helps.
If not the ONLY way is opening a issue in platformio github

**Comment by kugelkopf123** [comment] 2020-09-08 14:11
@Jason2866 
Ok. Ive tried that. The previous Post was the result of the new esp32 v. 2.0.0 frameworks.
It's just strange that this error occured right after an update to the current version of the Tasmota Dev.
So nothing else was installed or changed. Only the Tasmota project folder was updated via Github Desktop.
