### ISSUE TITLE
Sonoff THR316D Settings with DS18B20

### ISSUE THREAD

**Issue by Nau30** [arendst/Tasmota#18212] opened 2023-03-17 14:56 UTC
### PROBLEM DESCRIPTION
When the DS18B20 is physically disconnected from the THR316D (simulating a breakdown or damage to the DS18B20), the temperature continues to be displayed on the display for 5 minutes, and the last temperature value continues to be displayed in HA until the THR316D is forced to reboot, because the LWT only works when the device as a whole is disconnected (malfunction).

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff THR316D
- [x] Tasmota binary firmware version number used: 12.4.0
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
17:46:42.375 CMD: Backlog Template; Module; GPIO 255
17:46:42.415 MQT: stat/THR316D_10_BC5BF8/RESULT = {"NAME":"Sonoff THR316D","GPIO":[32,0,0,0,0,9280,0,0,0,321,0,576,320,9184,9216,0,0,224,0,9248,0,1312,0,3840,0,0,0,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":1}
17:46:42.644 MQT: stat/THR316D_10_BC5BF8/RESULT = {"Module":{"0":"Sonoff THR316D"}}
17:46:42.856 MQT: stat/THR316D_10_BC5BF8/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"9280":"TM1621 DAT"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"321":"Led_i2"},"GPIO14":{"0":"None"},"GPIO15":{"576":"LedLink_i"},"GPIO16":{"320":"Led_i1"},"GPIO17":{"9184":"TM1621 CS"},"GPIO18":{"9216":"TM1621 WR"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"224":"Relay1"},"GPIO22":{"0":"None"},"GPIO23":{"9248":"TM1621 RD"},"GPIO24":{"0":"None"},"GPIO25":{"1312":"DS18x201"},"GPIO26":{"0":"None"},"GPIO27":{"3840":"Output Hi"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
17:48:36.065 CMD: Backlog Rule1; Rule2; Rule3
17:48:36.115 MQT: stat/THR316D_10_BC5BF8/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":43,"Free":468,"Rules":"on Time#Minute|1 do backlog status 10 endon"}}
17:48:36.352 MQT: stat/THR316D_10_BC5BF8/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
17:48:36.553 MQT: stat/THR316D_10_BC5BF8/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
17:49:12.944 CMD: Status 0
17:49:12.954 MQT: stat/THR316D_10_BC5BF8/STATUS = {"Status":{"Module":0,"DeviceName":"THR316D_10","FriendlyName":["THR316D_10"],"Topic":"THR316D_10_BC5BF8","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
17:49:12.966 MQT: stat/THR316D_10_BC5BF8/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"https://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"0T05:02:49","StartupUTC":"2023-03-17T09:46:23","Sleep":50,"CfgHolder":4617,"BootCount":42,"BCResetTime":"2023-03-11T08:37:49","SaveCount":180}}
17:49:12.983 MQT: stat/THR316D_10_BC5BF8/STATUS2 = {"StatusFWR":{"Version":"12.4.0(tasmota)","BuildDateTime":"2023-03-15T15:48:08","Core":"2_0_6","SDK":"4.4.3.20230129","CpuFrequency":160,"Hardware":"ESP32-D0WD-V3 rev.3","CR":"458/699"}}
17:49:12.999 MQT: stat/THR316D_10_BC5BF8/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["IoT",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","11000080","00006000","00004000","00000000"]}}
17:49:13.024 MQT: stat/THR316D_10_BC5BF8/STATUS4 = {"StatusMEM":{"ProgramSize":1483,"Free":1396,"Heap":148,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DIO","Features":["00000809","9F9AD7CF","0015A001","B7F7BFCF","05DA9BC0","E0360DC7","480840D2","20200000","D43C482D","000080B1"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,59,60,62,63,66,82,86,87,88","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,103,127"}}
17:49:13.038 MQT: stat/THR316D_10_BC5BF8/STATUS5 = {"StatusNET":{"Hostname":"THR316D-10-BC5BF8-7160","IPAddress":"192.168.3.26","Gateway":"192.168.3.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.3.1","DNSServer2":"0.0.0.0","Mac":"78:21:84:BC:5B:F8","IP6Global":"","IP6Local":"fe80::7a21:84ff:febc:5bf8","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"192.168.3.1","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00","IP6Global":"","IP6Local":""},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
17:49:13.052 MQT: stat/THR316D_10_BC5BF8/STATUS6 = {"StatusMQT":{"MqttHost":"10.1.30.16","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_BC5BF8","MqttUser":"homeassistant","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
17:49:13.064 MQT: stat/THR316D_10_BC5BF8/STATUS7 = {"StatusTIM":{"UTC":"2023-03-17T14:49:13","Local":"2023-03-17T17:49:13","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+03:00","Sunrise":"08:59","Sunset":"20:57"}}
17:49:13.097 MQT: stat/THR316D_10_BC5BF8/STATUS10 = {"StatusSNS":{"Time":"2023-03-17T17:49:13","DS18B20":{"Id":"3C01F096F775","Temperature":24.7},"TempUnit":"C"}}
17:49:13.112 MQT: stat/THR316D_10_BC5BF8/STATUS11 = {"StatusSTS":{"Time":"2023-03-17T17:49:13","Uptime":"0T05:02:50","UptimeSec":18170,"Heap":150,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":21,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":44},"POWER":"ON","Wifi":{"AP":1,"SSId":"IoT","BSSId":"2C:C8:1B:F6:1B:DA","Channel":1,"Mode":"11n","RSSI":100,"Signal":-33,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
Add LWT separately for the sensor or change the configuration of topics (add sensor availability control), and also add a relay setting - when the sensor is disconnected (broken), relay 1. turns off 2. turns on 3. remains in the position in which it was at the time of the last connection with the sensor.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment] 2023-03-17 15:17
LWT does not make sense for the sensor separately, as this is for the device as such.

When HA cannot handle lack of new sensor data well, you could make a mitigation in Tasmota with rules to publish "something" if TelePeriod was reached without having sensor data. Same rules could also be used for your specific ideas about what you'd like to happen on the relays with loss of sensor data.

**Comment by Jason2866** [comment] 2023-03-17 16:36
Not an issue. A way to solve is shown. Closing since working as designed.

**Closed by Jason2866** 2023-03-17 16:36 UTC
Labels: as designed
