### ISSUE TITLE
Fallback Topic not unique

### ISSUE THREAD

**Issue by pgScorpio** [arendst/Tasmota#8300] opened 2020-04-28 14:23 UTC
Please DO NOT OPEN AN ISSUE:
  - If your Tasmota version is not the latest from the development branch, please update your device before submitting your issue. Your problem might already be solved. The latest precompiled binaries of Tasmota can be downloaded from http://thehackbox.org/tasmota/
  - If you have an issue when flashing was done via Tuya Convert, please address it to Tuya Convert Team
  - If your issue is a flashing issue, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
  - If your issue is compilation problem, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
  - If your issue has been addressed before (i.e., duplicated issue), please ask in the original issue
  - If your issue is a Wi-Fi problem or MQTT problem, please try the steps provided in the [FAQ](https://tasmota.github.io/docs/FAQ) and [Troubleshooting](https://tasmota.github.io/docs/Troubleshooting)

 Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

DO NOT DELETE ANY TEXT from this template! Otherwise the issue will be auto-closed.
-->

### PROBLEM DESCRIPTION
From the manual:

> By default the Fallback Topic is DVES_XXXXXX_fb where xxxxxx is derived from the last 6 charactes of the device's MAC address (excluding :)

This means that we only use the second half of the MAC address. However the first 3 bytes of the MAC address are (or at least should be) vendor specific, and you would expect that all 'Espressif' devices have the same first 3 bytes in their MAC, but I discovered this is **not** the case (see picture, ). Espressive has multiple MAC ranges  (at least 2, see links.), so you **can** have two devices with the same Fallback Topic !

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): 2x L-10A01-RF
- [x] Tasmota binary firmware version number used: _____
  - [x ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x ] Flashing tools used: Tasmotiser
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
n.a.

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:

```
- [ x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
n.a.

```
- [x ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
n.a.

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
n.a.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Why don't we simply use the  **full** MAC address like MAC_XXXXXXXXXXXX as a fallback topic ?
since this should always be unique.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

![Screenshot_20200428-154522](https://user-images.githubusercontent.com/9221087/80495762-9f462580-8968-11ea-819e-ee59193de9c6.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
[https://hwaddress.com/oui-iab/C4-4F-33/](url)
[https://hwaddress.com/oui-iab/D8-F1-5B/](url)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment] 2020-04-28 14:40
What is the probability that _you_ will have **_the_** two devices with the same least significant three bytes of these two Espressif MAC ranges? It's smaller than 1/(2*256^3) (~3e-8) because you have to also account for the population of people buying Espressif based devices and you being the one that gets the "duplicates". OK, it's not zero, but is it high enough for concern?

**Comment by pgScorpio** [comment] 2020-04-28 15:29
Hi meingraham, thanks for the quick reaction.

First of all a slight correction:

The chance is (number of tasmota devices on the network)  *  (number of 'Espressif' MAC ranges') / (2^24), (in my case about 4e-6 or 1 on 250000.)

Secondly: I **did** run into this problem (I wish I was that lucky in the lottery!) while trying to add a new sonoff on my network. And it took me hours to find out out what was going on (a esp12 on the network with the same lower 3 bytes in the mac !). 

Thirthly: With the exponentially growing number of Espressif based devices (I expect that there are already more than 2 Espressif MAC ranges.) the chances will only grow too 

Finally: Even if the chances are very low, it's so easy to prevent it, so why don't change it !

**Comment by meingraham** [comment] 2020-04-28 15:50
I never was much good with statistics :wink:

I still think you need to take into account the population. But, yes, if only you were as lucky as you appear to be unlucky :wink:

If you want this issue to be looked more critically, you need to open a "feature request" and fully complete the template so that the issue isn't automatically closed by the bot.

**Comment by pgScorpio** [comment] 2020-04-28 17:10
Yes I know you're right, but still I think it should be an easy fix that one day could save someone else some big problems too.

And I did think I fully completed the template, but no idea why it still got closed right away )-:)
just because I didn't fill in the non-applicable 'Tasmota binary firmware version number' ??

**Comment by meingraham** [comment] 2020-04-28 17:39
Adding the three bytes (six characters) may have other implications in how the fb topic is treated elsewhere and impact that code... but yes, could be minimal.

Even though it's superfluous, providing some of the information (e.g., `Status 0` which has lots of pertinent information) could be useful... and the bot is expecting that.

I'll try to re-open. But if I can't then please create a new issue with all the info you can... even if it might be N/A.

**Comment by pgScorpio** [comment] 2020-04-28 18:25
Thanks for reopening.
If purely the lenght of the fb topic would be an issue it could be shortened to just M_XXXXXXXXXXXX (same length)
but I guess that would not be the case.

**Comment by pgScorpio** [comment] 2020-04-28 20:16
FYI:

I just found out that Espressif already has 34 MAC ranges !
See https://hwaddress.com/company/espressif-inc/

**Comment by stefanbode** [comment] 2020-05-13 14:11
What other projects are doing is to use the ID from the splash and the ID from the mac as we do. In this case, it should be unique. I still had no problems and I have quite a lot ESP here. Class-D does not work anymore...

**Comment by pgScorpio** [comment] 2020-05-14 19:11
> In this case, it should be unique. 

No it isn't ! It should be if the manufacturer has only one mac range, espressif has already 34 mac ranges in use (and still growing)..

> I still had no problems and I have quite a lot ESP here

So do I, and I ran into this problem ! That's why I reported this issue.

> Class-D does not work anymore...

No idea what you mean with that...

**Comment by ascillato2** [comment] 2020-05-26 15:12
Closing this issue as it has been added by Theo. 

Thanks.

**Closed by ascillato2** 2020-05-26 15:12 UTC
Labels: enhancement, fixed
