### ISSUE TITLE
Support Shelly addon / sensor module

### ISSUE THREAD

**Issue by vergoossen** [arendst/Tasmota#7469] opened 2020-01-09 22:19 UTC
**Have you looked for this feature in other issues and in the docs?**  
Yes, couldn't find anything.

**Is your feature request related to a problem? Please describe.**  
https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312
Tried to assign al gpio's to ds18b20 sensor, but it doesn't work. I think this module needs an additonal driver.

**Describe the solution you'd like**  
Should be nice if Tasmota can support this module, it's great to attach inwall / in switchbox sensors.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by llevering** [comment] 2020-01-16 09:47
As the module 'clicks' onto the standard available GPIO pins of the Shelly 1, I would assume the module communicates with serial communication over the RX/TX pins. As no useful other GPIO pin is available for the click on module. Which sadly makes it a bit more work to implement I guess. But would be really nice if it can get support in Tasmota.

**Comment by Gamester17** [comment] 2020-01-16 15:07
+1 however I would like to connect a Si7021 or AM2301 humidity sensor instead as requested in #7530

**Comment by Gamester17** [comment] 2020-01-16 15:59
@ascillato2 as I understand it that while the GPIO ports on the Shelly 1PM is connected to mains AC power, that new GPIO-adapter that Shelly sells as part of its Temperature Sensor Addon is isolated so any sensors connected via that GPIO-adapter on the Shelly 1PM would not be directly connected to mains AC power. 

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312

**Comment by ascillato2** [comment] 2020-01-16 16:10
@Gamester17 The Shelly ADD-ON is isolating the sensor from mains. That is why you can connect shelly supported sensors to a shelly device through this ADD-ON. But only through this ADD-ON. And so far, only using stock firmware due this ADD-ON is not supported by Tasmota so far.

You are saying:

> Sonoff Pow or Sonoff Pow R2 with a wired Si7021 or AM2301 sensors would also work be a solution my purpose of....

An that is very dangerous. You must read the docs. NEVER CONNECT SENSORS TO ANY POWER MEASURING DEVICE like a SONOFF POW.. You can electrocute yourself. Those devices are NOT ISOLATED and your sensor will have MAINS AC. DO NOT PUT YOURSELF, YOUR FAMILY AND HOME AT RISK.

**Comment by arendst** [comment] 2020-01-16 16:26
Let someone buy it, crack it open and report pin lay-out.

**Comment by vergoossen** [comment] 2020-01-16 16:28
I have some at home.
Can crack it tonight if it helps :)

**Comment by vergoossen** [comment] 2020-01-16 19:16
![578E5B7E-E3B7-4DF7-B824-7DF3FA42D16A](https://user-images.githubusercontent.com/25444741/72555518-fe41cc00-389c-11ea-84e8-894991d41782.jpeg)
![5631CA83-9399-478B-83CE-0CCEB2034252](https://user-images.githubusercontent.com/25444741/72555520-fe41cc00-389c-11ea-9ebf-b4a0bda9bbf2.jpeg)
![050D115D-511D-40BC-B3B5-D87EC900EEB3](https://user-images.githubusercontent.com/25444741/72555521-fe41cc00-389c-11ea-939f-9ac0cfd03977.jpeg)

There you go :)

**Comment by vergoossen** [comment] 2020-01-16 19:28
![image](https://user-images.githubusercontent.com/25444741/72556344-b459e580-389e-11ea-90cc-66e6a8adb3df.png)

Texts are very hard to read... Let me know if you need to know more / if I can test something.

**Comment by Gamester17** [comment] 2020-01-17 12:11
@vergoossen Nice! Is it possible for you to get some better pictures?

**Comment by vergoossen** [comment] 2020-01-17 12:11
What kind of pictures do you want, what do you want to see?

**Comment by Gamester17** [comment] 2020-01-17 12:13
I guess that I just mean sharper closeups so that you can clearly see all paths & chip text + orientations

**Comment by vergoossen** [comment] 2020-01-17 12:34
![DSC_0036](https://user-images.githubusercontent.com/25444741/72612776-03029080-392e-11ea-9b1e-361591be1a65.JPG)
![DSC_0037](https://user-images.githubusercontent.com/25444741/72612777-03029080-392e-11ea-9efd-9fc00d9621cf.JPG)
![DSC_0039](https://user-images.githubusercontent.com/25444741/72612778-039b2700-392e-11ea-863b-99b0870398eb.JPG)
![DSC_0040](https://user-images.githubusercontent.com/25444741/72612779-039b2700-392e-11ea-891d-ad58df4b8491.JPG)

Are these pictures better?

**Comment by arendst** [comment] 2020-01-17 15:08
Way better. No we know the 8-pin chip is a TexasInstruments ISO7221 Dual channel Digital Isolator.

GPIO03 is connected to pin 2 and would become an input.
GPIO00 is connected to pin 3 and would become an output.

Both pins 6 and 7 are connected together and fed through to the second pin on the connector where the DS18B20 is connected.

So it seems in order to talk to the DS18B20 we will need a driver sending data to the DS18B20 via GPIO00 and receiving data from the DS18B20 via GPIO03.

**Comment by vergoossen** [comment] 2020-01-17 15:12
Hmm, that sounds like a lot of work?
And do you need to write a seperate driver for each sensor? For example a DHT22 needs another new driver? Or can it be a "universal" driver which can handle all already supported sensors?

**Comment by arendst** [comment] 2020-01-17 15:13
At first it would be a separate driver for any sensor where it is even questionable if it would work for other sensors considering the two pin to one wire construction.

**Comment by arendst** [comment] 2020-01-17 15:14
Looks to me like a nice hobby project for someone who loves Shelly and sensors ;-)

**Comment by vergoossen** [comment] 2020-01-17 15:16
Haha yes, unfortunately I can't write C, only "web languages". 
Otherwise I would love to help :).

**Comment by vergoossen** [comment] 2020-01-17 16:29
Maybe it's not that simple, but:
When you configure template gpio3 to ds18x20, that should be step 1?
And then tasmota should send data to gpio0? Can I test that with a serialsend in console? Or is it nog that simple?

**Comment by arendst** [comment] 2020-01-17 16:39
No it's not that simple. The single wire protocol used by DS18B20 is timing dependant.

What you could try is 
- make a copy of file xsns_05_ds18x20.ino and rename it as xsns_05_ds18x20_shelly.ino
- change the top define #ifdef USE_DS18x20 into USE_DS18x20SHELLY
- disable define USE_DS18x20 in user_config.h (or user_config_override.h)
- add define USE_DS18x20SHELLY in above file and recompile to check your copy is OK
- then change reads from input port to GPIO03 and writes to output port GPIO00 (that's tricky if you don't know how to address a port/GPIO)

Seeing what I wrote there is much more to it.

I think I make a basic writeup for this sensor for Shelly and let you test.

Hold on.

**Comment by altelch** [comment] 2020-01-17 16:45
The TI chip does galvanic separation for IO on GPIO0 and GPIO3. I don't really understand the pinout of the second connector. There are only 3 Lines connected. Pin 4-6 seems to be floating as I can'd detect a gnd-layer on the backside of the board or any vias connecting this pins to anywhere. The we are left to 1-3.  1 and to are the GPIO-Pins, 3 is GND or VCC. DS18x20 is a One-Wire protocol, we need only one gpio to talk to the device, so the second GPIO is probably used to ground (?) or power the vcc line of the connected sensors. I'd guess Pin 1 is vcc, Pin 2 is data and pin3 is GND.

**Comment by arendst** [comment] 2020-01-17 16:53
Give the latest commit a try. You will have to compile yourself and make the changes I mentionend above in either ``my_user_config.h`` or ``user_config_override.h``

**Comment by vergoossen** [comment] 2020-01-17 17:05
Do I still need to configure something in web interface?
I selected shely1 in modules and in console i get a lot of this messages:
18:04:48 CMD: nknown"}
18:04:48 RSL: stat/tasmota/RESULT = {"Command":"Unknown"}
18:04:48 CMD: D: a/RESULT = {"Command":"Unknown"}
18:04:48 RSL: stat/tasmota/RESULT = {"Command":"Unknown"}
18:04:48 CMD: :04:47 CMD: }
18:04:48 CMD: t/tasmota/RESULT = {"Command":"Unknown"}
18:04:48 RSL: stat/tasmota/RESULT = {"Command":"Unknown"}

**Comment by arendst** [comment] 2020-01-17 17:08
Turn seriallog off

**Comment by vergoossen** [comment] 2020-01-17 17:19
Okay sorry its gone now.
But, i selected shelly1 as module, but nothing comes in the webinterface/console.
I also tried to configure template gpio3 to ds18x20 but nothing happens..

**Comment by arendst** [comment] 2020-01-17 17:25
Other than Shelly1 or Shelly1PM there is nothing to configure. The GPIOs 00 and 03 are hardcoded. 

If you see the option for DS18x20 in your gui than you did not disable the old driver (and possibly activate the new driver). The option should not be there.

**Comment by vergoossen** [comment] 2020-01-17 17:30
Okay then I did something wrong.
Ill check tonight.

**Comment by vergoossen** [comment] 2020-01-17 18:25
Now there's no more option DS18x20 in the gui, but i still dont see anything in gui/console about the sensor.

**Comment by arendst** [comment] 2020-01-18 11:33
I ordered one. Once arrived I will dive into.

**Comment by vergoossen** [comment] 2020-01-18 12:02
Nice! I could also send one to you.

**Comment by Gamester17** [comment] 2020-01-20 12:14
In somewhat relevant news I read on Shelly German support-forum that Dimitar Dimitrov (CEO of Allterco Robotics which makes Shelly) recently posted on Shelly's Facebook page with a statement that their next official firmware for Shelly 1 and Shelly 1PM will add support DHT22 Temperature and Humidity Sensor

https://www.shelly-support.eu/forum/index.php?thread/1547-temperatur-luftfeuchtigkeitsensor-dht22/

So my follow-up question to this is if the official Shelly firmware code is really open source not?

**Comment by meingraham** [comment] 2020-01-20 12:58
Shelly firmware is not open source.

**Comment by ascillato** [comment] 2020-01-20 13:56
@Gamester17 Shelly is not open source, what they said is that their API to control shelly devices in a local network is open and fully explained in their documentation. So, there is your confusion. Their firmware is closed source but how to control it externally is open and documented.

**Comment by Gamester17** [comment] 2020-01-20 14:33
@ascillato honest mistake given that they title it as "open source" and not "open API" on their site:

https://shelly.cloud/shelly1-open-source/

All resellers of Shelly that I can find also re-hash that "open source" title when selling the Shelly 1.

So a just a case false advertisement from Allterco Robotics when marketing their Shelly products?

**Comment by ascillato** [comment] 2020-01-20 14:36
> So a just a case false advertisement from Allterco Robotics when marketing their Shelly products?

I don't think so. May be just a bad translation to english or bad choice of words. As soon as you enter in their site, it is explained as my previous comment.

**Comment by vergoossen** [comment] 2020-01-23 10:02
Don't know if it makes sense.
But i thought the addon has an internal pullup resistor.

**Comment by vergoossen** [comment] 2020-02-03 08:14
@arendst did you already receive the addon? :)

**Comment by arendst** [comment] 2020-02-04 14:53
Got it. Need time to dive

**Comment by arendst** [comment] 2020-02-05 13:44
To start you'll need to undefine GPIO00 as LedI in the standard template as it is now being used as an input for the sensor. 

So use this template when the Add-On is connected.
```
{"NAME":"Shelly 1PM U2","GPIO":[0,0,0,0,82,134,0,0,0,0,0,21,0],"FLAG":2,"BASE":18}
```
It doesn't show (additional) temperatures as the protocol still needs to be worked out...

**Comment by arendst** [comment] 2020-02-05 14:19
This is what we're looking for:

![image](https://user-images.githubusercontent.com/11044339/73849818-deae1b80-482a-11ea-81d9-431f6d63bb56.png)

Now finding a way to integrate...

**Comment by arendst** [comment] 2020-02-05 15:36
Latest dev commit and version 8.1.0.6 supports the shelly add-on for DS18x20.

To use it you'll need an updated Shelly 1PM template. This is the correct one:
```
{"NAME":"Shelly 1PM U2","GPIO":[255,255,0,255,82,134,0,0,0,0,0,21,0],"FLAG":2,"BASE":18}
```
Once activated go to the Module Configuration screen and enter the DS18x20 parameters like 

![image](https://user-images.githubusercontent.com/11044339/73856111-45d0cd80-4835-11ea-83b4-f1779362af87.png)

With the latest version 8.1.0.6 now Shelly 1 also allows the above configuration.

After the restart the additional sensor(s) should be displayed like

![image](https://user-images.githubusercontent.com/11044339/73856200-600aab80-4835-11ea-856f-95340f1d3129.png)

**Comment by vergoossen** [comment] 2020-02-05 17:32
Is the template the same for shelly1?

**Comment by ascillato** [comment] 2020-02-05 18:01
> Is the template the same for shelly1?

No, they are different devices with different capabilities and different connections.

**Comment by ascillato** [comment] 2020-02-05 18:03
TEMPLATES:

```
* SHELLY 1PM
OLD: {"NAME":"Shelly 1PM","GPIO":[56,0,0,0,82,134,0,0,0,0,0,21,0],"FLAG":2,"BASE":18}
NEW: {"NAME":"Shelly 1PM U2","GPIO":[255,255,0,255,82,134,0,0,0,0,0,21,0],"FLAG":2,"BASE":18}

* SHELLY 1
OLD: {"NAME":"Shelly 1","GPIO":[0,0,0,0,21,82,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}
NEW: {"NAME":"Shelly 1 U2","GPIO":[255,255,0,255,21,82,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}
```

**Comment by vergoossen** [comment] 2020-02-05 18:06
Thnx will try asap.

**Comment by spielkind1** [comment] 2020-02-05 18:50
Hi i tried it with:
{"NAME":"Shelly 1 U2","GPIO":[255,255,0,255,21,82,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}
but it dont work

**Comment by ascillato** [comment] 2020-02-05 19:16
@spielkind1

In old versions of Tasmota is not going to work. This has been added today to the codebase. See the date of the comments. Latest precompiled bins are at http://thehackbox.org/tasmota as explained in the docs and in the readme

**Comment by spielkind1** [comment] 2020-02-05 19:17
i found it, but still wont work :(
![image](https://user-images.githubusercontent.com/60711819/73874883-96a3ee80-4854-11ea-9094-387bfb7c054c.png)

**Comment by ascillato** [comment] 2020-02-05 19:18
Please, read Theo's comment on how configure the sensor.

**Comment by spielkind1** [comment] 2020-02-05 19:22
where can i find this comment?

**Comment by ascillato** [comment] 2020-02-05 19:23
Please scroll back a little on this issue

**Comment by spielkind1** [comment] 2020-02-05 19:36
i know what you mean, now i need to restore. sh.... tomorrow ;)

**Comment by ascillato2** [comment] 2020-02-05 20:10
@vergoossen 

Please, tell us if this template works for your SHELLY 1 with SENSOR ADDON with the DS18X20 Temp sensor under latest Tasmota (8.1.0.6). Thanks.

**Comment by arendst** [comment] 2020-02-05 20:30
The updated Shelly 1 template is also embedded in the firmware so an external template is not really needed. The ds18x20 gpio module config is still needed.

**Comment by arendst** [comment] 2020-02-06 11:20
And another teaser, connecting an AM2301 to the Shelly Add-On:

![image](https://user-images.githubusercontent.com/11044339/73932615-08bf1680-48db-11ea-89fb-093c2416fe9e.png)

Working on integration...

**Comment by arendst** [comment] 2020-02-06 11:46
To use a DHT family sensor use the latest commit and the following module config:

![image](https://user-images.githubusercontent.com/11044339/73934355-86385600-48de-11ea-9e95-33da7c6453d6.png)

Note: for any of the three available DHT family options you always select ``DHT11o`` for GPIO00.

**Comment by Gamester17** [comment] 2020-02-06 15:34
@arendst Very cool! Do you also happen to own a Si7021 humidity and temperature sensor?

Si7021 sensors are latest sold by Itead for their Sonoff TH series so can be bought nicely packaged

https://www.itead.cc/wiki/Sonoff_Sensor_Si7021

https://sonoff.tech/product/accessories/si7021

Sonoff page incorrectly says it only supports -10 Celcius but it does support -40 same as AM2301

**Comment by arendst** [comment] 2020-02-06 15:36
I don't but as the current driver always supported the SI7021 chances are they will also work on the Shelly Add-On

**Comment by vergoossen** [comment] 2020-02-06 16:12
Addon is not working on 8.1.0.6 on shelly1. Template was also not in, i added myself and configured gpios, restarted device but no ds18x20 temperature shown.

**Comment by arendst** [comment] 2020-02-06 16:14
Pls provide output of commands ``status 0``, ``template`` and ``gpio``.

**Comment by vergoossen** [comment] 2020-02-06 16:16
17:16:36 CMD: backlog status 0;template;gpio
17:16:36 RSL: stat/tasmota/STATUS = {"Status":{"Module":0,"FriendlyName":["Tasmota"],"Topic":"tasmota","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
17:16:36 RSL: stat/tasmota/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Power on","Uptime":"0T00:00:33","StartupUTC":"2020-02-06T16:16:03","Sleep":50,"CfgHolder":4617,"BootCount":7,"SaveCount":17,"SaveAddress":"FB000"}}
17:16:36 RSL: stat/tasmota/STATUS2 = {"StatusFWR":{"Version":"8.1.0.6(tasmota)","BuildDateTime":"2020-02-06T15:55:13","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"337/699"}}
17:16:36 RSL: stat/tasmota/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["WATERPAS",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
17:16:36 RSL: stat/tasmota/STATUS4 = {"StatusMEM":{"ProgramSize":569,"Free":432,"Heap":27,"ProgramFlashSize":2048,"FlashSize":2048,"FlashChipId":"1540EF","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
17:16:36 RSL: stat/tasmota/STATUS5 = {"StatusNET":{"Hostname":"tasmota-8022","IPAddress":"192.168.1.113","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"98:F4:AB:F3:9F:56","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
17:16:36 RSL: stat/tasmota/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F39F56","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
17:16:36 RSL: stat/tasmota/STATUS7 = {"StatusTIM":{"UTC":"Thu Feb 06 16:16:36 2020","Local":"Thu Feb 06 17:16:36 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:13","Sunset":"17:54"}}
17:16:36 RSL: stat/tasmota/STATUS10 = {"StatusSNS":{"Time":"2020-02-06T17:16:36","Switch1":"OFF"}}
17:16:36 RSL: stat/tasmota/STATUS11 = {"StatusSTS":{"Time":"2020-02-06T17:16:36","Uptime":"0T00:00:33","UptimeSec":33,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"WATERPAS","BSSId":"18:E8:29:E7:90:26","Channel":1,"RSSI":100,"Signal":-43,"LinkCount":1,"Downtime":"0T00:00:06"}}}
17:16:36 RSL: stat/tasmota/RESULT = {"NAME":"Shelly 1 U2","GPIO":[255,255,0,255,21,82,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}
17:16:37 RSL: stat/tasmota/RESULT = {"GPIO0":{"192":"DS18x20o"},"GPIO1":{"0":"None"},"GPIO3":{"4":"DS18x20"}}

**Comment by arendst** [comment] 2020-02-06 16:23
I see you changed the flash layout from default Tasmota supported 1024 to 2048. So you compiled this image yourself as we do not support this flash layout.

In that case did you use the default USE_DS18x20 define?

**Comment by vergoossen** [comment] 2020-02-06 16:25
Huh flash layout?
I compiled with your last commit? There are no bin's available right?

**Comment by arendst** [comment] 2020-02-06 16:28
Yes there are always development bins available from http://thehackbox.org/tasmota/ compiled every hour when a new commit has been made.

Your compiled flash layout is 2M while the supported Tasmota images only support 1M size. Somewhere in your compile environment you set it to 2M. The default Tasmota platfromio environment provided with the Tasmota respository also only supports 1M flash sizes

**Comment by arendst** [comment] 2020-02-06 16:30
The flash size is probably not the cause of your unability to see the DS18x20. ARe you sure you made firm connections using the shelly provided clips? I was unable to use them and hd to revert to old dutch "kroonsteentjes".

**Comment by vergoossen** [comment] 2020-02-06 16:31
Hmm strange, dont know about change 1M to 2M.
I flashed with the bin and its indeed not working.

Let me check addon with shelly firmware or looking for a PM which is somewhere here.
1 sec

**Comment by vergoossen** [comment] 2020-02-06 16:43
Allright bad connections indeed :). Its working now :).
Let me try AM2302 sensor now :D

**Comment by vergoossen** [comment] 2020-02-06 16:49
And that one is also working!
Nice! :) Thanks for the great support!

**Comment by arendst** [comment] 2020-02-06 16:49
So let's close this issue.

**Closed by arendst** 2020-02-06 16:49 UTC
Labels: Add to Docs, awaiting feedback, enhancement, fixed

**Comment by spielkind1** [comment] 2020-02-13 17:51
Shelly 1 U2 hast no function with 8.1.0.8

**Comment by vergoossen** [comment] 2020-04-02 10:08
Why it's removed?

**Comment by arendst** [comment] 2020-04-02 10:28
Has it?

![image](https://user-images.githubusercontent.com/11044339/78238898-5d4ad080-74dd-11ea-8cf4-2bd435214fa9.png)

**Comment by vergoossen** [comment] 2020-04-02 10:31
Ah I see, its because spielkind said it has no function in 8.1.0.8

**Comment by spielkind1** [comment] 2020-04-02 10:40
Yes

Theo Arends <notifications@github.com> schrieb am Do., 2. Apr. 2020, 12:28:

**Comment by the-cyberspace** [comment] 2020-04-26 08:48
I have 2 DS18B20 sensors plugged into the shelly temperature add-on module on a shelly 1pm:

![shelly1pm](https://user-images.githubusercontent.com/46862733/80302518-cd7e0680-87aa-11ea-97a8-67442ff33da6.png)

And i have this configuration:
`{"NAME":"Shelly 1PM","GPIO":[56,0,0,0,82,134,0,0,131,132,0,21,0],"FLAG":2,"BASE":18}`

![shelly1pm_1](https://user-images.githubusercontent.com/46862733/80302561-f7cfc400-87aa-11ea-9a9e-a24f1ec4dc92.png)

I`m not sure what i have to change to get the data from the sensor. Can someone help me with that?

**Comment by arendst** [comment] 2020-04-26 10:00
Configure the sensor like below:

![image](https://user-images.githubusercontent.com/11044339/80304343-6285fd00-87b5-11ea-99c2-3df13a933f1f.png)

**Comment by the-cyberspace** [comment] 2020-04-26 10:53
I don`t have any options there:

![shelly1pm_1](https://user-images.githubusercontent.com/46862733/80305433-df68a500-87bc-11ea-918e-d1c47df44f30.png)

**Comment by spielkind1** [comment] 2020-04-26 11:42
Dont change the template, change your settings and dont forget the
widerstand between current and data..

Roy <notifications@github.com> schrieb am So., 26. Apr. 2020, 10:48:

**Comment by arendst** [comment] 2020-04-26 11:49
Try another template
```
{"NAME":"Shelly 1PM U2","GPIO":[255,255,0,255,82,134,0,0,0,0,0,21,0],"FLAG":2,"BASE":18}
```

**Comment by the-cyberspace** [comment] 2020-04-26 12:33
It`s working now with that template! Thanks!

**Comment by hulkhaugen** [comment] 2020-04-30 09:05
Just came over this. So I can connect a DHT22 to GND,3.3V and RXD/GPIO3 to a Shelly 1PM Module? Or do I need some sort of add-on module? Will this disable the default external button function of the Shelly relay?

**Comment by arendst** [comment] 2020-04-30 10:50
I suggest you start reading this issue from the top down and proceed to the one you just entered.

**Comment by SmartNightly** [comment] 2020-06-24 20:55
Hi there, great work thx!

I've got connected 4 sensors to my shelly 1. But i get only 3 values. Is this hardware-limitation of the shelly addon? Or did i miss something in template config?

<img width="362" alt="Bildschirmfoto 2020-06-24 um 22 53 56" src="https://user-images.githubusercontent.com/64711109/85626660-a7bb9380-b66d-11ea-96d9-2e03a97d680b.png">

**Comment by arendst** [comment] 2020-06-25 12:20
I guess more should work up to 8 but it all depends on how you connected them and if the shelly can power them.

To rule out the fourth being broken did you already swap it with the third?

**Comment by sirLeone** [comment] 2020-09-10 11:43
Is it possible to connect jsn-sr04t to shelly 1PM using above extension ?

**Comment by arendst** [comment] 2020-09-10 11:53
You can connect anything but there is no driver support for this device using the shelly addon.

**Comment by wmertens** [comment] 2020-12-14 07:46
Purely out of academic interest (for now): Would it be possible to connect an LCD module via the 1-wire interface with the addon?

**Comment by pilot1981** [comment] 2021-01-04 10:17
Hi,
anyone know if I can use temperature add-on to attach n.2 reed sensor (one for close sensor and one for open sensor)?

**Comment by wmertens** [comment] 2021-01-04 10:52
@pilot1981 I don't know tasmota, but the add-on implements the 1-wire bus, so you need to make your reed switches talk to that, and have a driver in tasmota that supports that.

Shelly supports 1 reed switch that simply shorts the signal to ground (I believe), so then you can only have 1

**Comment by Maikel-K** [comment] 2021-10-06 18:59
Would it be easy to change the maximum amount of DS18B20 sensors in the software?
I would like to use the Shelly 1PM with addon module with 6 temperature sensors too switch on floorheating pump and read the temperature of the water in and out.

**Comment by barbudor** [comment] 2021-10-06 19:07
And what do you think the limit is ?
There is no hard coded limit in Tasmota, you can put as many sensors as can fit into the SENSOR MQTT messages
I've seen up to 18 DS18X20

**Comment by applechrist** [comment] 2021-12-22 21:21
Would it be possible to use the XKC-Y25-NPN as well?

**Comment by tim4849** [comment] 2022-06-26 13:41
Hi all, I have connected to my Shelly 1pm temperature sensors DS18B20 via the addon sensor module. Now the timers do not work anymore. I had set up 16 timers to control (on/off) of my circulation pump. Likewise, the WEB interface responds very poorly, manual switching also does not work safely, obviously the 1pm restarts again and again.

I'm using follwing Template: {"NAME":"Shelly 1PM Temp","GPIO":[1,1,0,1,192,2720,0,0,0,0,0,224,0,4736],"FLAG":0,"BASE":18}

Who knows similar problems or what am I doing wrong? Please for help!

**Comment by ascillato** [comment] 2022-06-27 05:23
Hi, that seems to be an excess in power consumption. Do you have restarts when you disconnect the sensor?

**Comment by SuperMaximus1984** [comment] 2022-08-01 21:25
Is it possible to use 2xDHT22 (AM2032) sensors in Shelly 1 with Add-on & Tasmota?
It was not possible in Shelly's standard firmware.

**Comment by chivas03** [comment] 2022-11-26 10:16
> Is it possible to use 2xDHT22 (AM2032) sensors in Shelly 1 with Add-on & Tasmota? It was not possible in Shelly's standard firmware.

Hey, have you been able to run at least on DHT22 with the Shelly1 Add-On based on Tasmota?

**Comment by SuperMaximus1984** [comment] 2022-11-26 18:42
> DHT22

Yes, sure. But there's not much sense for me to run Tasmota on Shelly as device itself unlike other ESP's does not physically support connectivity of more than 1 humidity sensor.

**Comment by notacoderjustauser** [comment] 2022-11-26 19:10
my experience was, that the wifi connection in the 1pm is far more stable wenn running tasmota as when the original firmware is installed. This matters when the sensor is in a cellar or behind concrete walls for example.

**Comment by chivas03** [comment] 2022-11-27 21:58
> > DHT22
> 
> Yes, sure. But there's not much sense for me to run Tasmota on Shelly as device itself unlike other ESP's does not physically support connectivity of more than 1 humidity sensor.

Hello, thanks for your input. For my application, it is OK to have one DHT22. (bathroom - thermostat + ventilation control)
I thought prior to use an ESP within a flush box, but with an external power supply, one relay and the sensor would lead to some extension of the available space - so I came up to use the Shelly with the add-on

**Comment by Kolia56** [comment] 2024-01-26 15:55
As of 1/24/2024, DS18x20 is supported. See current development branch. See updated template as well

**Comment by sfromis** [comment] 2024-01-26 16:58
It was already supported for a long time, as this thread relates to ESP8266, not ESP32 and the "plus" variant of Shelly devices where it got to be supported very recently.

**Comment by Kolia56** [comment] 2024-01-26 17:54
> It was already supported for a long time, as this thread relates to ESP8266, not ESP32 and the "plus" variant of Shelly devices where it got to be supported very recently.

my bad, I apologise, I made a confusion because of numerous opened tabs in internet browser.
