### ISSUE TITLE
Treatlife DS01 - Dimmer value not updated when brightness changed on device with 8.5.1

### ISSUE THREAD

**Issue by mcarson75** [arendst/Tasmota#9658] opened 2020-10-29 01:13 UTC
### PROBLEM DESCRIPTION
With Tasmota 8.5.1 on a Treatlife DS01 dimmer, when the brightness level is changed at the device there is a "TuyaReceived" message seen with the new brightness level.  However, the RESULT message is not seen in the console, nor updated as seen in MQTT Explorer.  Messages sent to the device work as expected - if Home Assistant sends a Dimmer command or if the Dimmer command is issued from the console, the RESULT message is updated and the dimming value on the switch changes appropriately.

Switch information is received properly (RESULT reflects POWER on or off)

Downgrading to 8.5.0 restores the messages.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): _Treatlife DS01 dimmer_
- [X] Tasmota binary firmware version number used: _8.5.1_
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: _Tasmotizer_
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
02:08:31 MQT: tasmota/outside/dimmer-test/light/stat/RESULT = {"NAME":"DS01 Dimmer","GPIO":[0,107,0,108,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":54}
02:08:31 MQT: tasmota/outside/dimmer-test/light/stat/RESULT = {"Module":{"0":"DS01 Dimmer"}}
02:08:31 MQT: tasmota/outside/dimmer-test/light/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"107":"Tuya Tx"},"GPIO2":{"0":"None"},"GPIO3":{"108":"Tuya Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
None
```
- [ ] Provide the output of this command: `Status 0`:
```
N/A since I have since downgraded
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```

```

### TO REPRODUCE
- Flash 8.5.1
- Change dimmer value with device faceplate
- TuyaReceived message with new dimming value seen with weblog 4
- No MQTT RESULT message seen

### EXPECTED BEHAVIOUR
- TuyaReceived message with new dimmer value
- MQTT RESULT sent with payload `{"POWER","ON","Dimmer":xx}`

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by effelle** [comment] 2020-10-29 13:11
Duplicate of #9583 . Already fixed on dev channel trough #9606 .

**Closed by effelle** 2020-10-29 13:11 UTC
Labels: duplicated
