### ISSUE TITLE
PowerRetain MQTT setting ignored  in "stat/dimmername/RESULT" in JSON format

### ISSUE THREAD

**Issue by PatBoud** [arendst/Tasmota#10432] opened 2021-01-06 16:22 UTC
### PROBLEM DESCRIPTION
PowerRetain MQTT setting ignored  when the Dimmer publishes "stat/dimmername/RESULT" in JSON format.

A MQTT message is properly published in topic "stat/dimmername/RESULT" with JSON data {"POWER":"OFF"}, 
but **it is not retained** , even though PowerRetain has been set to ON.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): WiFi Dimmer, brand unknown
- [ ]x Tasmota binary firmware version number used: 9.2
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [x ] Flashing tools used: OTA update
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

17:15:49 MQT: stat/cuisine/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
17:15:49 MQT: stat/cuisine/RESULT = {"Module":{"54":"Tuya MCU"}}
17:15:50 MQT: stat/cuisine/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"2304":"Tuya Rx"},"GPIO14":{"0":"None"},"GPIO15":{"2272":"Tuya Tx"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

17:12:28 CMD: status 0
17:12:28 MQT: stat/cuisine/STATUS = {"Status":{"Module":54,"DeviceName":"CESmartDimmer-1","FriendlyName":["CESmartDimmer-1"],"Topic":"cuisine","ButtonTopic":"","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":1,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
17:12:28 MQT: stat/cuisine/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://ota.tasmota.com/tasmota/release-9.2.0/tasmota.bin","RestartReason":"External System","Uptime":"0T00:49:55","StartupUTC":"2021-01-06T15:22:33","Sleep":50,"CfgHolder":4617,"BootCount":73,"BCResetTime":"2021-01-06T13:27:22","SaveCount":5792,"SaveAddress":"F6000"}}
17:12:28 MQT: stat/cuisine/STATUS2 = {"StatusFWR":{"Version":"9.2.0(tasmota)","BuildDateTime":"2020-12-21T15:03:40","Boot":4,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"374/699"}}
17:12:28 MQT: stat/cuisine/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["PatBoud",""],"TelePeriod":0,"Resolution":"558180C0","SetOption":["00008069","2805C8000100060000005AFF000000000000","00000000","00006100","00000000"]}}
17:12:28 MQT: stat/cuisine/STATUS4 = {"StatusMEM":{"ProgramSize":586,"Free":416,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440C8","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
17:12:28 MQT: stat/cuisine/STATUS5 = {"StatusNET":{"Hostname":"cuisine-2918","IPAddress":"10.12.14.43","Gateway":"10.12.14.1","Subnetmask":"255.255.255.0","DNSServer":"24.200.241.37","Mac":"BC:DD:C2:EF:6B:66","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
17:12:28 MQT: stat/cuisine/STATUS6 = {"StatusMQT":{"MqttHost":"10.12.14.13","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_EF6B66","MqttUser":"patboud","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
17:12:28 MQT: stat/cuisine/STATUS7 = {"StatusTIM":{"UTC":"2021-01-06T16:12:28","Local":"2021-01-06T17:12:28","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:42","Sunset":"17:09"}}
17:12:28 MQT: stat/cuisine/STATUS10 = {"StatusSNS":{"Time":"2021-01-06T17:12:28"}}
17:12:28 MQT: stat/cuisine/STATUS11 = {"StatusSTS":{"Time":"2021-01-06T17:12:28","Uptime":"0T00:49:55","UptimeSec":2995,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Dimmer":100,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"PatBoud","BSSId":"10:33:BF:EA:A9:28","Channel":1,"RSSI":78,"Signal":-61,"LinkCount":1,"Downtime":"0T00:00:05"}}}

```
- [x ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

17:02:18 CMD: weblog 4
17:02:18 MQT: stat/cuisine/RESULT = {"WebLog":4}
17:02:18 CFG: Saved to flash at F9, Count 5789, Bytes 4096
17:02:20 TYA: Send "55aa00000000ff"
17:02:20 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
17:02:20 TYA: Heartbeat
17:02:20 WIF: Checking connection...
17:02:21 {"TuyaReceived":{"Data":"55AA0007000501010001010F","Cmnd":7,"CmndData":"0101000101","DpType1Id1":1,"1":{"DpId":1,"DpIdType":1,"DpIdData":"01"}}}
17:02:21 TYA: fnId=11 is set for dpId=1
17:02:21 TYA: RX Relay-1 --> MCU State: On Current State:Off
17:02:21 SRC: Switch
17:02:21 MQT: stat/cuisine/RESULT = {"POWER":"ON"}
17:02:21 {"TuyaReceived":{"Data":"55AA0007000501010001010F","Cmnd":7,"CmndData":"0101000101","DpType1Id1":1,"1":{"DpId":1,"DpIdType":1,"DpIdData":"01"}}}
17:02:21 TYA: fnId=11 is set for dpId=1
17:02:21 TYA: RX Relay-1 --> MCU State: On Current State:On
17:02:21 {"TuyaReceived":{"Data":"55AA0007000501010001010F","Cmnd":7,"CmndData":"0101000101","DpType1Id1":1,"1":{"DpId":1,"DpIdType":1,"DpIdData":"01"}}}
17:02:21 TYA: fnId=11 is set for dpId=1
17:02:21 TYA: RX Relay-1 --> MCU State: On Current State:On
17:02:22 {"TuyaReceived":{"Data":"55AA0007000501010001010F","Cmnd":7,"CmndData":"0101000101","DpType1Id1":1,"1":{"DpId":1,"DpIdType":1,"DpIdData":"01"}}}
17:02:22 TYA: fnId=11 is set for dpId=1
17:02:22 TYA: RX Relay-1 --> MCU State: On Current State:On
17:02:22 {"TuyaReceived":{"Data":"55AA0007000803020004000000FF16","Cmnd":7,"CmndData":"03020004000000FF","DpType2Id3":255,"3":{"DpId":3,"DpIdType":2,"DpIdData":"000000FF"}}}
17:02:22 TYA: fnId=21 is set for dpId=3
17:02:22 TYA: RX value 255 from dpId 3 
17:02:22 CFG: Saved to flash at F8, Count 5790, Bytes 4096
17:02:26 {"TuyaReceived":{"Data":"55AA0007000501010001000E","Cmnd":7,"CmndData":"0101000100","DpType1Id1":0,"1":{"DpId":1,"DpIdType":1,"DpIdData":"00"}}}
17:02:26 TYA: fnId=11 is set for dpId=1
17:02:26 TYA: RX Relay-1 --> MCU State: Off Current State:On
17:02:26 SRC: Switch
17:02:26 MQT: stat/cuisine/RESULT = {"POWER":"OFF"}
17:02:26 {"TuyaReceived":{"Data":"55AA0007000803020004000000FF16","Cmnd":7,"CmndData":"03020004000000FF","DpType2Id3":255,"3":{"DpId":3,"DpIdType":2,"DpIdData":"000000FF"}}}
17:02:26 TYA: fnId=21 is set for dpId=3
17:02:26 TYA: RX value 255 from dpId 3 
17:02:27 CFG: Saved to flash at F7, Count 5791, Bytes 4096
17:02:31 TYA: Send "55aa00000000ff"
17:02:31 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
17:02:31 TYA: Heartbeat
17:02:33 CMD: weblog 2
17:02:33 SRC: WebConsole from 10.12.14.164
17:02:33 CMD: Group 0, Index 1, Command "WEBLOG", Data "2"
17:02:33 MQT: stat/cuisine/RESULT = {"WebLog":2}
```

### TO REPRODUCE
Easy. Pressing the On or Off button on the dimmer.
A MQTT message is properly published in topic "stat/dimmername/RESULT" with JSON data {"POWER":"OFF"}, 
but **it is not retained**, even though PowerRetain has been set to ON.

I have been using version 6 for a long while and was having this issue.
Updated to 9.2 this morning using OTA and the documented update flow.
Problem persists.

### EXPECTED BEHAVIOUR
MQTT status messages for Power in JSON format should be retained, as set with command "PowerRetain".

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
I tried to disable the NON-JSON status updates because I don't use them in Home-Assistant.
Did not fix the issue with JSON status messages.

Non-JSON messages were properly retained, as seen in the log:
16:23:45 MQT: stat/cuisine/POWER = OFF (retained)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-01-10 16:42
Closing this issue as it is **duplicated**. Sorry.

RESULT topic is by design not retained due to is used by all responses. For all commands. You need to rewrite your logic to use the supported formats. Please, address this to the Tasmota support chat. Thanks.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2021-01-10 16:42 UTC
Labels: duplicated, question
