### ISSUE TITLE
Add support for laser ToF Sensor VL53L1X

### ISSUE THREAD

**Issue by atifan** [arendst/Tasmota#9152] opened 2020-08-23 15:05 UTC
**Have you looked for this feature in other issues and in the docs?**  
Yes, but the thread was closed. Seems to be no support until now for this sensor.

**Is your feature request related to a problem? Please describe.**  
The problem is, there is no support for this sensor in actual Tasmota.
There is only support for the sensor VL53L0X -> range until 2m.
The range of the VL53L1X up to 4m.
I would like to use this sensor to measure my water in zisterne, because ultrasonic is not workling well in my case.

**Describe the solution you'd like**  
I would like to have Tasmota with support for the VL53L1X sensor, so that you can use it with tasmota like other sensors too.

**Describe alternatives you've considered**  
I have no alternatives.

**Additional context**  
The sensor is descriped here: https://www.st.com/resource/en/datasheet/vl53l1x.pdf

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment] 2020-08-23 17:55
Try this. Enabling by `#define USE_VL53L1X` [VL53L1X](https://github.com/Jason2866/Tasmota/tree/vl53l1x)
Since i do not have the sensor i couldn´t do a test. I would be surprised (a bit) if it works.

**Comment by atifan** [comment] 2020-08-23 18:30
Cool thx very much, I will try it as soon i have the sensor and tell you if it works!

**Comment by stefanbode** [comment] 2020-08-26 10:34
I know it works. :) Also for rain detection

**Comment by kugelkopf123** [comment] 2020-08-26 10:38
>I know it works. :) Also for rain detection

@stefanbode Tell me More! 
How?! Sounds pretty interesting!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by device111** [comment] 2020-08-27 10:30
@Jason2866 
great!

but you must delete DOMOTICZ Section. There is No support of `Distance` in Tasmota.

**Comment by atifan** [comment] 2020-08-27 11:24
For me the driver works, but I had to change the I2C address in driver from 0x52 to 0x29.
@device111 and @stefanbode Did it work for you directly without any change?

**Comment by atifan** [comment] 2020-08-27 11:48
For me it works, but it does not measure right :( But atm I dont know if its because of sensor/reflect or if the driver does not work correct. I am trying to get it out.

**Comment by device111** [comment] 2020-08-27 12:18
sorry, i don‘t have this sensor. I only had a look at the source code.

**Comment by Jason2866** [comment] 2020-08-27 12:59
@device111  Thx for the DOMOTICZ hint.

**Comment by ascillato2** [comment] 2020-09-13 15:35
Closing this issue as the PR with this feature has been submitted for review.

Thanks.

**Closed by ascillato2** 2020-09-13 15:35 UTC
Labels: duplicated, feature request (devs?)

**Comment by RigoWeb** [comment] 2022-02-20 18:11
Sorry for digging out this old thread, but is there any chance to add support for multiple VL53L**1**X sensors support for as it is possible for VL53L**0**X? See [https://tasmota.github.io/docs/VL53L0x/#tasmota-settings-for-multiple-sensors](https://tasmota.github.io/docs/VL53L0x/#tasmota-settings-for-multiple-sensors). Maybe the same logic can be used? Thanks!

**Comment by barbudor** [comment] 2022-02-20 19:05
The approach with controlling XSHUT pin is interresting and could be definitively be used with VL53L1X too.
I can have a look later next week (after Thursday) if that's ok for you. However as I'm away from home I won't have a VL53L1X to test. So you will have to test for me.

**Comment by RigoWeb** [comment] 2022-02-21 06:12
This sounds great! I have four VL53L1X devices for testing, so this is the smallest problem. I am using this sensors the first time, but I've seen that there are some differences in the measurement range modes (short, medium and long range for the 1X while the 0X has only two modes). It would be great if all three modes can be supported (I think by a #define). Thank you!

**Comment by RigoWeb** [comment] 2022-03-04 17:20
Don't want to hurry, but have you had time to take a look? Or maybe you've even had some success? Thank you!

**Comment by barbudor** [comment] 2022-03-04 19:17
😂
Apologies I've been very busy with real life work and not enough free time. But it's still in my to-do list.
Please allow me a few more days

**Comment by barbudor** [comment] 2022-03-07 23:20
@RigoWeb I have a 1st version (tasmota-sensors)
I tried to test it but it looks like I have burned down my only VL53L1X :(
So please test is, 1st with a single VL53L1X and no XSHUT. It should behave like before
The single VL531X with XSHUT, then 2, etc ...

It is a 1st version to test the mecanism with XHUT
If ok, then I'll look into the 3 modes you were asking for too
[tasmota-test-vl53l1x_1.zip](https://github.com/arendst/Tasmota/files/8201440/tasmota-test-vl53l1x_1.zip)

**Comment by RigoWeb** [comment] 2022-03-08 07:49
@barbudor First: Thank you really very much for your effort! I've tried, but without success.

- 1 VL53L1X / no XSHUT: Doesn't shows up in web GUI or console
- 1 VL53L1X with XSHUT: Shows up in GUI: **VL53L1X Distance  0 mm** (distance always 0, seems there is no continous measurement)
- 2 VL53L1X with 2 XSHUT: same as above (only one sensor listed). I recognized that there is no suffix VL53L1X**_1** Distance

And I hade a strange effect: Sometimes the pin config gets lost, and the console show following on reboot: 
`00:00:00.050 FRC: Some settings have been reset (5)`

I will reflash the old firmware later, just to make sure, that all my 4 VL53L1X are working (mabye your isn't burned?)

**Comment by barbudor** [comment] 2022-03-08 08:10
Yep looks like my code is bad :)
Can you try an 'i2cscan'?
The config being erase is typical of a boot loop due to a crash

I will work again on it tonight

**Comment by RigoWeb** [comment] 2022-03-08 09:26
Never heared about I2CScan :-)
Gave a try in the console:
`RESULT = {"I2CScan":"No devices found"}`

**Comment by barbudor** [comment] 2022-03-08 21:48
The good news is that my VL53X1X is not dead 😄
The bad news is that I have totally broken the driver's code and I need to restart from the beginning 🤣
I need a clean and fresh restart tomorrow
Sorry for the delay

**Comment by RigoWeb** [comment] 2022-03-09 05:10
Hey, great that you've don't produced some magic smoke :-) 
I am doing such things every day. I mean bug coding AND magic smoke ;-) Looking forward!

**Comment by device111** [comment] 2022-03-10 10:47
Hi RigoWeb,

you can try this binary. The Pololu Driver Api for the L0 and L1 are the same.
So this only a Quick and Dirty Hack that you can try. If it works, we can implement the L1 Driver to the L0 Driver.
[tasmota.bin.gz](https://github.com/arendst/Tasmota/files/8222630/tasmota.bin.gz)

**Comment by RigoWeb** [comment] 2022-03-10 16:58
Thanks, but I'm not sure what I have to try :-)
I2CScan responses me "Device(s) found at 0x29", but I can't see the sensor(s) show up in the GUI (with and without XSHUT)...

PS offtopic: Just because I've noticed that you gave me a german binary: I'm from Switzerland...

**Comment by device111** [comment] 2022-03-10 19:29
ok, then the quick and dirty hack wasn't successful after all. Let's wait what barbudor proggs.
thanks for testing.

**Comment by barbudor** [comment] 2022-03-10 20:33
Hi @device111 
I agree that if we could have a single library/driver for both VL53L*X with support for XSHUT it could be interresting to be able to mix those 2 devices to get a wide range of distance for example
I look at Polulu's Github however but I can see 2 different drivers.
ST publishes 2x "API" which have similar API but are not fully identical.

My goal was to 1st get to work the 1X with SHUT 
Then refactoring is an interresting option but on my side I would prefer to do it in 2 steps.

But if you can get it to work 1st, you're welcome to PR before me 🤣, I won't be annoyed

**Comment by barbudor** [comment] 2022-03-10 23:30
Here you are
[tasmota-sensors-vl53l1x_B.zip](https://github.com/arendst/Tasmota/files/8227772/tasmota-sensors-vl53l1x_B.zip)
Note that the XSHUT GPIO are still labelled VL53L0X but you can only have either L0X (i2cdriver31) or L1X (i2cdriver54) enabled at the same time

If that's ok, I will then add the capability to set the range.
I see that the L0X also have a option for a median fileter that I could backport too

```
00:28:50.246 RSL: SENSOR = {"Time":"2022-03-11T00:28:50","VL53L1X-1":{"Distance":110}}
```
![image](https://user-images.githubusercontent.com/2996042/157772573-048b6f2c-9846-4ab7-840b-08d6d341f549.png)
![image](https://user-images.githubusercontent.com/2996042/157772688-032c9311-6aae-4f15-b7d0-b6f8b68d227e.png)

**Comment by RigoWeb** [comment] 2022-03-11 05:33
See below my test results. Interresting, that I can't reproduce your measurement, I always get 9999. Do you have any idea?
![VL53L1X](https://user-images.githubusercontent.com/48877125/157807230-572c8af8-32fc-409b-8ad0-f014f5e84406.png)

I have load the firmware OTA, does this make a difference compared to serial flashing?

**Comment by barbudor** [comment] 2022-03-11 12:01
@RigoWeb strange
Out of curiosity, how many VL are actually connected in each case? Is that 1, 1, 2?
I'll ré-investigate more tonight

**Comment by barbudor** [comment] 2022-03-11 12:03
BTW 9999mm is generally a read error
I got that when my Dupont wires were not correctly set
With 1 and 2 XSHUT, which indexes were you using? 1 and 1+2?

**Comment by RigoWeb** [comment] 2022-03-11 12:04
1 without XSHUT, then 1 with 1 XSHUT, then 2 with 2 XSHUT's

**Comment by RigoWeb** [comment] 2022-03-11 15:34
Following my test setup; I'm always removing the not required (not configured) XSHUT and I2C wires...
![IMG_20220311_162712](https://user-images.githubusercontent.com/48877125/157897904-05820772-f2e2-4fed-b70f-618b2a09327b.jpg)

**Comment by barbudor** [comment] 2022-03-11 20:12
I can't reproduce your problems.
I only have 1 sensor to test but it get consitenctly detected without XSHUT or with the right XSHUT.
For exemple I've setup 3 GPIO as XSHUT 1, 5 and 8 and connected the sensor to XSHUT_5 and it is correctly detected as #5. Others, being not present are just ignored
And finally it is working well also with XSHUT. It's just that when moving from XSHUT to no XSHUT you must power cycle the  sensor so it gets back to it's default address.

Note that from your photo I feel that GND is not connected to the sensors. The mini D1 GND is connected to the top blue lines but the sensors are connected to the bottom blue lines. Those lines are not connected together. You need to connect them or preferably directly connect the GND from th emini-D1 to the bottom blue line.

**Comment by RigoWeb** [comment] 2022-03-11 21:02
The GND ist connected on the left side of the breadboard (outside the foto). I will try a clean serial erase/flash tomorrow, hope this helps...

**Comment by barbudor** [comment] 2022-03-11 22:36
I'm confident so I PR'ed. Wait for the merge.

**Comment by RigoWeb** [comment] 2022-03-12 11:13
@barbudor I'm a little bit confused. After two hours of trying, I come to the following results:

- With the default firmware (compiled with #define USE_VL53L1X) the sensor works as expected.
- With your test firmware, the pin assignments gets lost on boot (00:00:00.050 FRC: Some settings have been reset (5)), but only if a VL53L1X is connected to SDA/SCL. I have tested two different D1 mini modules, both times with the same result.
- Then I flashed the stock firmware again, and everything works as expected.

Do you have any other idea that could help me? I'm out of idea now :-)

**Comment by barbudor** [comment] 2022-03-12 11:46
`00:00:00.050 FRC: Some settings have been reset (5)`
This the message from Fast Reboot Count which detects that your boards has rebooted multiple times very quickly, the most obvious case being that drivers are crashing during boot.
To recover, Tasmota disable features one after the other at each boot until it stabilize. At step 5, configuration of GPIO is erased. This disable I2C and the driver.

Are you sure that you have downloaded and upgraded with my latest version above ? tasmota-sensors-vl53l1x_B.zip
Are you sure that any driver based on address 0x29 is disabled **including I2cdriver31** which is for the VL53L0X. You can't have both drivers enabled at the same time.
The simplest being to have ONLY i2cdriver54 enabled

Getting a serial terminal connected to the D1 can provide more logs when boot-looping.

To avoid any confusion, here is a binary with **only the VL53L1X** driver.
[tasmota-vl53l1x_C.zip](https://github.com/arendst/Tasmota/files/8237538/tasmota-vl53l1x_C.zip)

**Comment by RigoWeb** [comment] 2022-03-12 13:42
Hey, I had some success, thank you!!! I've used your tasmota-vl53l1x_C.zip firmware and I always cut off the power after reconfiguring something. Again I have some strange results :o)

- 2 sensors with XSHUT on GPIO12 and GPIO14 works like a charm, but the sensor-number seems to be wrong:
_VL53L1X-1 Distance 145 mm
VL53L1X-**6** Distance 136 mm_
- A 3rd sensor doesn't ever show up in GUI
- A 3rd sensor with XSHUT on GPIO13 or 16 doesn't show up in GUI but both other sensors works correctly
- A 3rd sensor with XSHUT on GPIO1 or 3 doesn't show up in GUI but seems to prevent one of the other both sensors from working properly
- A 3rd sensor with XSHUT on GPIO15 seems to prevent proper booting

I know that there are several pin restrictions on the ESP8266, so I think some of the results are therefore. And I don't knew that I can/have to enable/disable the specific driver. I'm sure you have again any hints :-)

**Comment by barbudor** [comment] 2022-03-12 14:12
> * 2 sensors with XSHUT on GPIO12 and GPIO14 works like a charm, but the sensor-number seems to be wrong:
>   _VL53L1X-1 Distance 145 mm
>   VL53L1X-**6** Distance 136 mm_

The number should match the index number for VL53LXX XSHUT in the GPIO configuration.
Each VL53LXX SHUT pin should have a different number from the drop box (see screenshot below)

> * A 3rd sensor doesn't ever show up in GUI
> * A 3rd sensor with XSHUT on GPIO13 or 16 doesn't show up in GUI but both other sensors works correctly

GPIO13 should work.
GPIO16 should work too although there are some specifics with GPIO16 but that should matter for that specific use case.

> * A 3rd sensor with XSHUT on GPIO1 or 3 doesn't show up in GUI but seems to prevent one of the other both sensors from working properly

1 and 3 are for the serial link. Avoid those

> * A 3rd sensor with XSHUT on GPIO15 seems to prevent proper booting

Yes. GPIO15 must be LOW at boot but the VL53LXX modules have a pull on XSHUT so the chip can be used even when the module's pin is not connected.
If you need to use this pin for XSHUT, you need to remove the pull-up on the VL53LXX module. So the existing pull-down on the mini-D1/nodeMCU would keep GPIO15 LOW for the boot time. Then the driver will set it HI to enable the chip.


Some readings about GPIO usage:
https://tasmota.github.io/docs/Expanding-Tasmota/
https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

These pins should be safe for XSHUT:
![image](https://user-images.githubusercontent.com/2996042/158021253-ac9947de-b01e-4cc4-a8ad-590ccb92729d.png)

**Comment by barbudor** [comment] 2022-03-12 14:31
You can enable `Weblog 3` to get some more messages at boot

**Comment by RigoWeb** [comment] 2022-03-13 07:42
I've done some more testing. 4 sensors attached, measuring distance should be about 100mm. I've done 4 configurations, always only changed the XSHUT number, saved and repowered. After this test I've toggled the hardware sensor positions to make sure that all sensors working... 
![test-4x](https://user-images.githubusercontent.com/48877125/158049876-0cdff09f-aeea-458e-8a0b-9e76cd3a50dc.png)
Sometimes the 9999mm values changed to a small value from 1mm to 10mm like in measurement 2. Do you see any logic? I don't really...
