### ISSUE TITLE
ESP32-C3 retains gpio state for non-relay gpios due to gpio_hold_en

### ISSUE THREAD

**Issue by smhc** [arendst/Tasmota#20030] opened 2023-11-15 22:26 UTC
### PROBLEM DESCRIPTION

For ESP32-C3 boards, any pin configured as a relay will retain its state even when configured as something else, e.g output_hi or output_lo. The use of gpio.digital_write() is also ignored for these pins, even if it is kept as a relay. This can make diagnosing issues quite difficult when temporarily using 'relay' to test a pin and having the state "stuck" thereafter.

The "bug" is due to this code which uses gpio_hold_en for REL1: https://github.com/arendst/Tasmota/blob/a01bed3928d74306f5f138c0b9a341ae5ddf981e/tasmota/tasmota_support/support.ino#L1466

Unfortunately this 'gpio_hold_en' flag is left on the pin even after reconfiguring the gpio. A hard power reset is required to clear this flag. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32-C3-12F
- [x] Tasmota binary firmware version number used: 13.2.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Web
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

09:02:40.778 CMD: Backlog Template; Module; GPIO 255:
09:02:40.794 MQT: stat/tasmota_56EED4/RESULT = {"NAME":"xx","GPIO":[1,1,1,3872,3872,1,1,3872,7648,1,3872,0,0,0,0,0,0,0,1,1,1,1],"FLAG":0,"BASE":1}
09:02:41.027 MQT: stat/tasmota_56EED4/RESULT = {"Module":{"0":"xx"}}
09:02:41.230 MQT: stat/tasmota_56EED4/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"3872":"Output Lo"},"GPIO4":{"3872":"Output Lo"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"3872":"Output Lo"},"GPIO8":{"7648":"Input1"},"GPIO9":{"0":"None"},"GPIO10":{"3872":"Output Lo"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


09:03:59.880 MQT: stat/tasmota_56EED4/STATUS = {"Status":{"Module":0,"DeviceName":"xxxx","FriendlyName":["xxxx"],"Topic":"tasmota_56EED4","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
09:03:59.914 MQT: stat/tasmota_56EED4/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release-13.2.0/tasmota32c3.bin","RestartReason":"Vbat power on reset","Uptime":"0T00:04:59","StartupUTC":"2023-11-15T22:59:00","Sleep":50,"CfgHolder":4617,"BootCount":136,"BCResetTime":"2023-11-14T05:44:35","SaveCount":444}}
09:03:59.949 MQT: stat/tasmota_56EED4/STATUS2 = {"StatusFWR":{"Version":"13.2.0(tasmota32)","BuildDateTime":"2023-10-19T09:05:17","Core":"2_0_14","SDK":"4.4.6.231011","CpuFrequency":160,"Hardware":"ESP32-C3 v0.3","CR":"396/699"}}
09:03:59.975 MQT: stat/tasmota_56EED4/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxx",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000A00B","2805C80001800600003C5A0A192800000000","00008088","00006000","00004000","00000000"]}}
09:04:00.006 MQT: stat/tasmota_56EED4/STATUS4 = {"StatusMEM":{"ProgramSize":1852,"Free":1027,"Heap":177,"StackLowMark":4,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":80,"FlashMode":"DIO","Features":["00000809","9F9AD7DF","0015A001","B7F7BFCF","05DA9BC4","E0360DC7","080840D2","20200000","D4BC482D","010A80B1"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,59,60,62,63,66,67,68,86,87,88","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,103,105,109,127","I2CDriver":"7,8,9,10,11,12,13,14,15,17,18,20,24,29,31,36,41,42,44,46,48,58,62,65,69,76,77,82"}}
09:04:00.063 MQT: stat/tasmota_56EED4/STATUS5 = {"StatusNET":{"Hostname":"tasmota-56EED4-3796","IPAddress":"192.168.1.79","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"8.8.8.8","DNSServer2":"8.8.4.4","Mac":"A0:76:4E:56:EE:D4","IP6Global":"fd06:8df3:e47f:940:a276:4eff:fe56:eed4","IP6Local":"fe80::a276:4eff:fe56:eed4","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":19.0}}
09:04:00.101 MQT: stat/tasmota_56EED4/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.111","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_56EED4","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
09:04:00.128 MQT: stat/tasmota_56EED4/STATUS7 = {"StatusTIM":{"UTC":"2023-11-15T23:04:00","Local":"2023-11-16T09:04:00","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+10:00","Sunrise":"17:00","Sunset":"02:08"}}
09:04:00.146 MQT: stat/tasmota_56EED4/STATUS10 = {"StatusSNS":{"Time":"2023-11-16T09:04:00"}}
09:04:00.164 MQT: stat/tasmota_56EED4/STATUS11 = {"StatusSTS":{"Time":"2023-11-16T09:04:00","Uptime":"0T00:05:00","UptimeSec":300,"Heap":177,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":4,"Objects":52},"Wifi":{"AP":1,"SSId":"xxxx","BSSId":"xx:xx:xx:xx:xx:xx","Channel":11,"Mode":"11n","RSSI":98,"Signal":-51,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE

- Configure a GPIO as "Relay 1"
- Toggle the relay
- Modify the relay gpio via 'gpio.digital_write()
-- Note that the API call is ignored
- Configure the same GPIO as either OUTPUT_LO or OUTPUT_HI
-- Note that the setting is ignored
- Modify the reconfigured gpio via 'gpio.digital_write()
-- Note that the API call is ignored

### EXPECTED BEHAVIOUR

- The GPIO should have gpio_hold_dis() set when configured as something other than a relay.
- Expose gpio.hold_dis/gpio.hold_en via berry?
- gpio.digital_write should call gpio_hold_dis first?
- The use of gpio_hold_en() should only be used if a flag to retain state is on?
- The documentation might want to describe this behaviour?
- Do nothing, and just keep this issue around to help others searching for the problem?

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment] 2023-11-16 08:18
Some background info.

All esp8266 and esp32 derivatives are supposed to keep their relay state after a restart. Measures have been taken to make this possible as default arduino code did not support this. The esp32c3 needed additional steps to have this functionality. Alas does the solution need a power cycle and not just a restart to remove this functionality. 

I will add a SetOption to enable debugging in your case but the default behaviour will be as it is now.

**Comment by arendst** [comment] 2023-11-16 08:21
Ah I see you're using berry. In that case the dis should be called first like in function DigitalWrite(). It would have been better if berry allowed you to use that function but then it seems berry doesn't mind template config anyway.....

**Comment by smhc** [comment] 2023-11-16 08:34
I thought at a minimum it could at least call gpio_hold_dis on all *non*relay pins when saving configuration (or if it happens to know the previous setting for the pin, only for pins that were previously set as relay 1). That would solve 99% of the issues without needing any new option or special logic in the berry callback.

**Comment by arendst** [comment] 2023-11-16 09:15
I'll have to dive in and find a way to divert edge cases (like redefining relays by something different).

**Comment by arendst** [comment] 2023-11-16 09:27
Try latest dev. At least the "normal" functionality should now work like changing RELAY to OUTPUT_HI/LOW.

**Comment by smhc** [comment] 2023-11-16 13:19
Thanks @arendst - I'm not in a position to try it right now but I assume it would work ok. I'm guessing that the digital write occurs when configuring an output_lo/hi, triggering the reset.
I'm just not sure how the performance/power may be impacted making this call on every value change.. but I suppose it already was getting called for relay1s anyway.

**Comment by arendst** [comment] 2023-11-17 12:03
Latest change should fix both "default" Tasmota outputs AND Berry configured outputs.

**Comment by smhc** [comment] 2023-11-17 20:47
Thanks @arendst that looks like it should work. I can try it out later this week but happy to close the issue for now.

**Comment by Jason2866** [comment] 2023-11-21 10:10
Closing since fixed. You can reopen when the issue is unexpectedly still there.

**Closed by Jason2866** 2023-11-21 10:10 UTC
Labels: fixed
