### ISSUE TITLE
ENERGY_Total value suddenly jumps -2kwh

### ISSUE THREAD

**Issue by lolax80** [arendst/Tasmota#12683] opened 2021-07-18 16:59 UTC
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff pow r2_
- [x] Tasmota binary firmware version number used: __9.4.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: ESPflasher
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

8:58:50.164 MQT: stat/tasmota_9C1794/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
18:58:50.174 MQT: tele/tasmota_9C1794/STATE = {"Time":"2021-07-18T18:58:50","Uptime":"0T02:57:09","UptimeSec":10629,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":3,"POWER":"ON","Wifi":{"AP":2,"SSId":"das_ist_mein_Buero","BSSId":"C0:25:06:25:61:41","Channel":11,"RSSI":100,"Signal":-37,"LinkCount":1,"Downtime":"0T00:00:03"}}
18:58:50.182 MQT: tele/tasmota_9C1794/SENSOR = {"Time":"2021-07-18T18:58:50","ENERGY":{"TotalStartTime":"2021-07-17T00:00:00","Total":48.799,"Yesterday":2.059,"Today":3.640,"Period":5,"Power":296,"ApparentPower":296,"ReactivePower":0,"Factor":1.00,"Voltage":243,"Current":1.215}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

09:36:19.707 MQT: stat/tasmota_9C1794/STATUS = {"Status":{"Module":43,"DeviceName":"Balkonkraftwerk Garbenteich","FriendlyName":["Tasmota"],"Topic":"tasmota_9C1794","ButtonTopic":"0","Power":1,"PowerOnState":1,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
09:36:19.714 MQT: stat/tasmota_9C1794/STATUS1 = {"StatusPRM":{"Baudrate":4800,"SerialConfig":"8E1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Power On","Uptime":"0T17:34:38","StartupUTC":"2021-07-18T14:01:41","Sleep":50,"CfgHolder":4617,"BootCount":55,"BCResetTime":"2021-06-04T15:39:31","SaveCount":180,"SaveAddress":"F8000"}}
09:36:19.720 MQT: stat/tasmota_9C1794/STATUS2 = {"StatusFWR":{"Version":"9.4.0(tasmota)","BuildDateTime":"2021.04.23 10:07:24","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"387/699"}}
09:36:19.725 MQT: stat/tasmota_9C1794/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Unifi","das_ist_mein_Buero"],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C8000100068000005A0A000000000000","00000080","00006000","00000000"]}}
09:36:19.737 MQT: stat/tasmota_9C1794/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":22,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashFrequency":40,"FlashMode":2,"Features":["00000407","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
09:36:19.745 MQT: stat/tasmota_9C1794/STATUS5 = {"StatusNET":{"Hostname":"tasmota_9C1794-6036","IPAddress":"192.168.1.30","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"84:CC:A8:9C:17:94","Webserver":2,"WifiConfig":0,"WifiPower":17.0}}
09:36:19.750 MQT: stat/tasmota_9C1794/STATUS6 = {"StatusMQT":{"MqttHost":"ich.du.de,"MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_9C1794","MqttUser":"mqtt","MqttCount":7,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
09:36:19.757 MQT: stat/tasmota_9C1794/STATUS7 = {"StatusTIM":{"UTC":"2021-07-19T07:36:19","Local":"2021-07-19T09:36:19","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":99,"Sunrise":"06:07","Sunset":"21:44"}}
09:36:19.762 MQT: stat/tasmota_9C1794/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
09:36:19.771 MQT: stat/tasmota_9C1794/STATUS10 = {"StatusSNS":{"Time":"2021-07-19T09:36:19","ENERGY":{"TotalStartTime":"2021-07-17T00:00:00","Total":49.237,"Yesterday":3.881,"Today":0.196,"Power":159,"ApparentPower":159,"ReactivePower":0,"Factor":1.00,"Voltage":240,"Current":0.662}}}
09:36:19.780 MQT: stat/tasmota_9C1794/STATUS11 = {"StatusSTS":{"Time":"2021-07-19T09:36:19","Uptime":"0T17:34:38","UptimeSec":63278,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":7,"POWER":"ON","Wifi":{"AP":2,"SSId":"das_ist_mein_Buero","BSSId":"C0:25:06:25:61:41","Channel":11,"RSSI":100,"Signal":-36,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-07-18 17:51
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by lolax80** [comment] 2021-07-18 18:08
there are no further information
today and yesterday the value from ENERGY_Total dropped. today from 47 to 45 at 04pm. I can see on the mqtt client

**Comment by ascillato** [comment] 2021-07-18 19:33
we need the output of the Tasmota console to have some information in order to help you. As the previous issues where this exact same problem occurs, it was due to hardware failure or bad connection. We can troubleshoot that from the output of the console. Remember to do that with weblog set to 4 before attempting to reproduce the problem.

**Comment by lolax80** [comment] 2021-07-19 07:40
i have updated the status.
But until today I can't post you the weblog, because  when the drop comes im not online.
 i do not know when the problem comes

**Comment by ascillato** [comment] 2021-07-19 10:27
From your status 0, your device didn't have power 17 hours ago. Tasmota saves the energy today al midnight but if your device is not powered, the value is lost.

**Comment by lolax80** [comment] 2021-07-19 10:44
Ok i understand, but the total value dropped at 4pm

**Comment by ascillato** [comment] 2021-07-19 12:43
because your mains AC have a power loss, or because your device have restarted for any reason.

If you see in the STATUS 0 the RESTART REASON as POWER ON, that means that your device was left without power.

**Comment by lolax80** [comment] 2021-07-19 12:58
Ok, but if there was at 3pm a Power the Value total is the on power up the value from 0am?
Maybe tasmota can write the total value every hour in the Flash?

Von meinem iPhone gesendet

**Comment by Jason2866** [comment] 2021-07-19 13:31
Please use latest Tasmota version 9.5. There where changes/fixes

**Comment by ascillato** [comment] 2021-07-19 14:08
> Maybe tasmota can write the total value every hour in the Flash?

Tasmota is designed to make your device last as long as it can. If a firmware saves data very frequently to the flash, the flash wears out and eventually fails. That is why, those values are saved only at midnight.

Just a rough example calculation. The storage of this IoT devices are flash memories, not hard drives. Most of flash memories has 150.000 write cycles. (The more expensive memories have more, the cheapers have less).
If you have an event that writes data every 5 minutes, you will reach the 150.000 events in 1 year and a half. After that, your device will fail with random issues. To mitigate that, Tasmota has delayed savings (to gather more events and write them all at once) and also sequential settings blocks (so this data is saved in different parts of the memory to not wear the same part and distribute the usage). Tasmota as it is is very good. I have several devices running Tasmota since jan/2018 flawlessly.

If your power grid is not stable (like having microcuts or so), may be would be better to add an UPS to what your are measuring (depending on which are your use-case) Or just saving the reported data in your home automation software. All depends on what you need.

**Comment by sfromis** [comment] 2021-07-19 15:42
What I do to not lose energy monitoring data in case of a power outage is to save it in my backend server. Thus, I can correct data if i see a drop, only losing up to 5 minutes (teleperiod) of data. I could even detect this, and send commands to the device to restore last seen values upon power up.

**Comment by lolax80** [comment] 2021-07-19 15:46
Cool, how do you Monitor Irans How you send the last Right value.
I use mqtt with iobroker.

Von meinem iPhone gesendet

**Comment by Jason2866** [comment] 2021-07-19 16:04
Correct data: when you receive energy data every teleperiod time. If this packet (heartbeat) is missing you have a power drop.

**Comment by sfromis** [comment] 2021-07-19 16:35
The command EnergyReset can be used to set the values. Any command can be sent via MQTT. How to do in ioBroker is outside of what I've played with.

**Comment by ascillato2** [comment] 2021-07-19 16:45
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2021-07-19 16:45 UTC
Labels: duplicated, template missing/incomplete, troubleshooting

**Comment by katodev** [comment] 2022-06-01 11:20
I have the same problem with tasmota version 9, 10, 11. If the load is greater 40 Watt the energy today value stops by 2000 kW/h and raise again with less 40 Watt load.
And the calculation is wrong too. With 30 W load the energy today value can't raise by 1200kW/h in 45 min.
