### ISSUE TITLE
Hide Alexa discovered objects

### ISSUE THREAD

**Issue by prstprst** [arendst/Tasmota#6762] opened 2019-10-27 13:21 UTC
Hello, 

I'm using an electrodragon in shutter mode and I've added a third output that is a "pwm" directly connected to the buit-in led of the electrodragon. Then, by using rules, I've linked the dimmer of the third output to the command of the shutters. And like this, with alexa,  I can use the dimmer of the dicovered third output and control my shutters with granularity. May be I'm false. But It's the way I found.
But in this case, the problem is that Alexa discover the two others output of the electrodragon. So for each shutter in my house, I have two more dicovered and unusable devices in my alexa interface. 
I repeat, may be I'm false, but I don't understand how I can discover only one device with alexa when I use the tasmota shutter mode with a dual relay real device (like electrodragon or sonoff dual)
Soory if I'm not at the good place. I'm newbee. Thx :-)
Thank to have taken time to read me again 
prst

**Comment by s-hadinger** [comment] 2019-10-27 13:42
Currently there is no way to hide some devices from Alexa. You need to delete the unwanted devices via the Alexa app.

**Comment by s-hadinger** [comment] 2019-10-27 13:44
Duplicate of #6722

**Comment by ascillato2** [comment] 2019-10-27 14:02
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2019-10-27 14:02 UTC
