### ISSUE TITLE
Enhancement Request for PowerOnState

### ISSUE THREAD

**Issue by ralphrmartin** [arendst/Tasmota#11852] opened 2021-04-23 05:46 UTC
### PROBLEM DESCRIPTION
PowerOnState options are too limiting.
 In the case of an extended power cut for example, it is not appropriate to just switch the relay on, or off, or even to set it to its previous state. E.g. we may only want a lamp to come on at night.
In cases where the relay is controlled by timers, it would be much more appropriate to (a) check the current time at power on, (b) set the relay to whatever the timers imply, given the current time of day.
Could this be added as an option for some future Tasmota release?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff S26, but applies to any controller
- [X] Tasmota binary firmware version number used: 9.4.0
  - [X] Pre-compiled
  - [ ] Self-compiled
- [X] Flashing tools used: OTA
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
06:40:51.799 CMD: Backlog Template; Module; GPIO 255
06:40:51.822 RSL: RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
06:40:52.044 RSL: RESULT = {"Module":{"8":"Sonoff S2X"}}
06:40:52.299 RSL: RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
Not using rules

```
- [X] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
06:42:10.680 CMD: Status 0
06:42:10.687 RSL: STATUS = {"Status":{"Module":8,"DeviceName":"Tasmota_Right_Propagator","FriendlyName":["Tasmota_Right_Propagator"],"Topic":"tasmota_1C5B1C","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
06:42:10.693 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T08:50:06","StartupUTC":"2021-04-22T20:52:04","Sleep":50,"CfgHolder":4617,"BootCount":9,"BCResetTime":"2021-04-08T13:40:27","SaveCount":63,"SaveAddress":"F9000"}}
06:42:10.697 RSL: STATUS2 = {"StatusFWR":{"Version":"9.4.0(tasmota)","BuildDateTime":"2021-04-21T12:48:39","Boot":7,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"421/699"}}
06:42:10.701 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["rrmair",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A0A000000000000","00000081","00006000","00000000"]}}
06:42:10.710 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":598,"Free":404,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
06:42:10.715 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota_1C5B1C-6940","IPAddress":"192.168.1.137","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.102","Mac":"CC:50:E3:1C:5B:1C","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
06:42:10.719 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1C5B1C","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
06:42:10.725 RSL: STATUS7 = {"StatusTIM":{"UTC":"2021-04-23T05:42:10","Local":"2021-04-23T06:42:10","StartDST":"2021-03-28T01:00:00","EndDST":"2021-10-31T02:00:00","Timezone":99,"Sunrise":"06:00","Sunset":"20:30"}}
06:42:10.730 RSL: STATUS10 = {"StatusSNS":{"Time":"2021-04-23T06:42:10"}}
06:42:10.735 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-04-23T06:42:10","Uptime":"0T08:50:06","UptimeSec":31806,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"ON","Wifi":{"AP":1,"SSId":"rrmair","BSSId":"18:E8:29:CA:34:26","Channel":1,"RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:03"}}}
06:42:13.450 RSL: STATE = {"Time":"2021-04-23T06:42:13","Uptime":"0T08:50:09","UptimeSec":31809,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"ON","Wifi":{"AP":1,"SSId":"rrmair","BSSId":"18:E8:29:CA:34:26","Channel":1,"RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:03"}}

```
- [X] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
Not an issue which is triggered as such

```

### TO REPRODUCE
Use any Tasmota device, power cycle it.

### EXPECTED BEHAVIOUR
Ideal behaviour would be to set relay according to time of day, and timers, not just set relay to off, on, or previous state.

### SCREENSHOTS
Not needed.

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-04-23 12:28
Moving to discussions as this is not a bug report.

**Closed** 2021-04-23 12:28 UTC
Labels: question
