### ISSUE TITLE
Zigbee2Tasmota - Support Request: Wireless 12 Scene Switch (TS004F, _TZ3000_xabckq1v)

### ISSUE THREAD

**Issue by mklan** [arendst/Tasmota#13128] opened 2021-09-14 14:55 UTC
### PROBLEM DESCRIPTION
I'd like to request the support within zigbee2tasmota for this Wireless 12 Scene Switch (TS004F, _TZ3000_xabckq1v)

https://zigbee.blakadder.com/Eardatek_ESW-4ZAA-CN.html

Below is the zbstatus3 response: 

```JSON
{
   "ZbStatus3":[
      {
         "Device":"0x50A2",
         "Name":"4way-control-livingroom",
         "IEEEAddr":"0x5C0272FFFE24A609",
         "ModelId":"TS004F",
         "Manufacturer":"_TZ3000_xabckq1v",
         "Endpoints":[
            1
         ],
         "Config":[
            
         ],
         "Reachable":true,
         "BatteryPercentage":100,
         "LastSeen":3555,
         "LastSeenEpoch":1631626787,
         "LinkQuality":71
      }
   ]
}
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Zigbee Bridge
- [x] Tasmota binary firmware version number used: 9.5.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Tasmotizer
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  15:42:11.457 CMD: Backlog Template; Module; GPIO 255
  15:42:11.458 SRC: WebConsole from 192.168.1.163
  15:42:11.460 CMD: Grp 0, Cmnd 'BACKLOG', Idx 1, Len 26, Data 'Template; Module; GPIO 255'
  15:42:11.472 SRC: Backlog
  15:42:11.474 CMD: Grp 0, Cmnd 'TEMPLATE', Idx 1, Len 0, Data ''
  15:42:11.478 MQT: stat/zigbee-bridge/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
  15:42:11.704 SRC: Backlog
  15:42:11.706 CMD: Grp 0, Cmnd 'MODULE', Idx 1, Len 0, Data ''
  15:42:11.709 MQT: stat/zigbee-bridge/RESULT = {"Module":{"75":"Sonoff ZbBridge"}}
  15:42:11.957 SRC: Backlog
  15:42:11.958 CMD: Grp 0, Cmnd 'GPIO', Idx 1, Len 3, Data '255'
  15:42:11.965 MQT: stat/zigbee-bridge/RESULT = {"GPIO0":{"320":"Led_i1"},"GPIO1":{"3552":"Zigbee Tx"},"GPIO2":{"0":"None"},"GPIO3":{"3584":"Zigbee Rx"},"GPIO4":{"5312":"Zigbee Rst1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"640":"I2C SDA"},"GPIO13":{"576":"LedLink_i"},"GPIO14":{"608":"I2C SCL"},"GPIO15":{"0":"None"},"GPIO16":{"32":"Button1"},"GPIO17":{"0":"None"}}


```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  15:43:06.429 CMD: Backlog Rule1; Rule2; Rule3
  15:43:06.430 SRC: WebConsole from 192.168.1.163
  15:43:06.432 CMD: Grp 0, Cmnd 'BACKLOG', Idx 1, Len 19, Data 'Rule1; Rule2; Rule3'
  15:43:06.458 SRC: Backlog
  15:43:06.459 CMD: Grp 0, Cmnd 'RULE', Idx 1, Len 0, Data ''
  15:43:06.463 MQT: stat/zigbee-bridge/RESULT = {"Rule1":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
  15:43:06.677 SRC: Backlog
  15:43:06.679 CMD: Grp 0, Cmnd 'RULE', Idx 2, Len 0, Data ''
  15:43:06.687 MQT: stat/zigbee-bridge/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
  15:43:06.927 SRC: Backlog
  15:43:06.928 CMD: Grp 0, Cmnd 'RULE', Idx 3, Len 0, Data ''
  15:43:06.936 MQT: stat/zigbee-bridge/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
  


```
- [x] Provide the output of this command: `Status 0`:
```lua
  15:44:11.414 CMD: Status 0
15:44:11.415 SRC: WebConsole from 192.168.1.163
15:44:11.417 CMD: Grp 0, Cmnd 'STATUS', Idx 1, Len 1, Data '0'
15:44:11.421 MQT: stat/zigbee-bridge/STATUS = {"Status":{"Module":75,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"zigbee-bridge","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
15:44:11.425 MQT: stat/zigbee-bridge/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Power On","Uptime":"0T02:34:28","StartupUTC":"2021-09-14T12:09:43","Sleep":50,"CfgHolder":4617,"BootCount":10,"BCResetTime":"2021-09-07T10:14:53","SaveCount":40,"SaveAddress":"F7000"}}
15:44:11.428 MQT: stat/zigbee-bridge/STATUS2 = {"StatusFWR":{"Version":"9.5.0(zbbridge)","BuildDateTime":"2021-06-17T08:27:09","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":160,"Hardware":"ESP8266EX","CR":"400/699"}}
15:44:11.430 MQT: stat/zigbee-bridge/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":3,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Unser Internet 2.4","Mein Internet"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000080","00006000","00000000"]}}
15:44:11.438 MQT: stat/zigbee-bridge/STATUS4 = {"StatusMEM":{"ProgramSize":589,"Free":1200,"Heap":22,"ProgramFlashSize":2048,"FlashSize":2048,"FlashChipId":"1540A1","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0F1007C4","04400001","00000002","00000000","00000000","00020000","00000000","00000000"],"Drivers":"1,2,7,9,10,20,23,41","Sensors":""}}
15:44:11.443 MQT: stat/zigbee-bridge/STATUS5 = {"StatusNET":{"Hostname":"zigbee-bridge-6172","IPAddress":"192.168.1.102","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"1.1.1.1","Mac":"C8:2B:96:04:B8:1C","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
15:44:11.447 MQT: stat/zigbee-bridge/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.114","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_04B81C","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
15:44:11.452 MQT: stat/zigbee-bridge/STATUS7 = {"StatusTIM":{"UTC":"2021-09-14T14:44:11","Local":"2021-09-14T15:44:11","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"06:25","Sunset":"19:05"}}
15:44:11.456 MQT: stat/zigbee-bridge/STATUS10 = {"StatusSNS":{"Time":"2021-09-14T15:44:11"}}
15:44:11.462 MQT: stat/zigbee-bridge/STATUS11 = {"StatusSTS":{"Time":"2021-09-14T15:44:11","Uptime":"0T02:34:28","UptimeSec":9268,"Vcc":3.458,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"xxxxxxxxxxxxxxxxx","BSSId":"xxxxxxxxxxxxxxxxxxxx","Channel":6,"Mode":"11n","RSSI":100,"Signal":-43,"LinkCount":1,"Downtime":"0T00:00:04"}}}


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:

 When I press a button, it is using sniffing group 0x0000 and there are some recieving messages:

```lua
  15:46:36.795 ZIG: {"ZbEZSPReceived2":"734290013F0003FDFF0401060001FF00010000C4000000"}
  15:46:36.796 ZIG: ZbEZSPSentRaw 80
  15:46:36.797 ZIG: {"ZbEZSPReceived":"3F0003FDFF0401060001FF00010000C4000000"}
  15:46:36.798 ZIG: Sniffing group 0x0000
  15:46:37.125 ZIG: {"ZbEZSPReceived2":"034290013F0003FDFF0401060001FF0001000027010000"}
  15:46:37.126 ZIG: ZbEZSPSentRaw 81
  15:46:37.127 ZIG: {"ZbEZSPReceived":"3F0003FDFF0401060001FF0001000027010000"}
  15:46:37.127 ZIG: Sniffing group 0x0000
  15:46:53.090 WIF: Checking connection...
  15:46:58.984 ZIG: {"ZbEZSPReceived2":"1342900145000004010000010100010000AB50B0C7E5FFFF2A1C5F11D20A01FF42210121D10B03281F0421A84305213F00062404000000000A2170136410000B210800"}
  15:46:58.985 ZIG: ZbEZSPSentRaw 82

```

### TO REPRODUCE
Pair with zigbee2tasmota and start pressing buttons.

### EXPECTED BEHAVIOUR
Providing information via mqtt which button was pressed and in which pattern (single press, double press, long press).
But single press and maybe release is enough for now.

### SCREENSHOTS
no Screenshots available

### ADDITIONAL CONTEXT
zigbee2mqtt and ZHA have support implemented. So maybe it is possible to port it?

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-09-14 19:14
Moving to discussions/Ideas as this is a feature request and not a bug report.

**Closed** 2021-09-14 19:14 UTC
Labels: feature request (devs?)
