### ISSUE TITLE
Support for bl0940 energy monitoring - BW-SHP10 - and Support for 1.5 stop bits in serial communication

### ISSUE THREAD

**Issue by MadDoct** [arendst/Tasmota#8175] opened 2020-04-14 10:15 UTC
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Provide suport for bl0940 energy monitoring chip as used by bw-shp10
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._
It uses UART for communication connected to tx and rx, but also has CF connected to gpio14
it seems to use baudrate 4800 8N and 1.5(?!) stop bits - this may be the problem...
I've tried to comunicate with it using serialsend, but can't... Maybe due to the stopbits - tried 8N1 and 8N2
datasheet - http://www.belling.com.cn/media/file_object/bel_product/BL0940/datasheet/BL0940_V1.1_en.pdf

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment] 2020-05-13 07:30
Still waiting for my banggood ordered device...

**Comment by kubiq** [comment] 2020-05-13 14:13
I have the device, but don't even know how to take it apart

**Comment by MadDoct** [comment] 2020-05-13 16:19
I took it apart... That's why I have the above information...
It is glued together and then soldered...

**Comment by arendst** [comment] 2020-05-16 09:38
Got it. Now find the time.

**Comment by arendst** [comment] 2020-05-17 11:54
Been playing around with all kinds of serial configs but all I receive is nothing. I'm even wondering if the Tx/Rx from the BL0940 is really connected to Rx/Tx to the ESP8266.

Before I try to open mine @MadDoct can you provide pictures of your opened up device so I/we can trace any additional signals going to/from both chips.

Regarding the 1.5 parity I think using 8N1 with a delay of 104uSec in between bytes send should provide the same functionality. Recieving shouldn't be an issue at 8N1 as the Uart would just handle it anyway having a slight delay between the bytes received.

**Comment by arendst** [comment] 2020-05-17 12:04
Just learned there are two versions; with or without metering. I wonder if mine has metering at all....

**Comment by arendst** [comment] 2020-05-17 12:13
And re-ordered the metering one.

**Comment by MadDoct** [comment] 2020-05-18 13:53
well, thats a pitty... mine is the metering one
about the connections, I checked with a multimeter and they are as described in the OP.
If you want, I can try modified firmwares or whatever you want @arendst ...

**Comment by arendst** [comment] 2020-05-18 14:15
You might want to try the attached file. It is a debug version with alpha code but it should start displaying serial data when you enable ``Weblog 4``.

[xnrg_14_bl0940.zip](https://github.com/arendst/Tasmota/files/4644611/xnrg_14_bl0940.zip)

In my case it displays ziltge, nil, nothing, nada, niets....

**Comment by napcode** [comment] 2020-05-18 14:55
> You might want to try the attached file. It is a debug version with alpha code but it should start 
Tried it but looks like some bits are missing:
`tasmota/xnrg_14_bl0940.ino:196:31: error: 'ValidTemplate' was not declared in this scope
   if (ValidTemplate("BW-SHP10") && PinUsed(GPIO_BL0940_RX) && PinUsed(GPIO_BL0940_TX)) {`

**Comment by arendst** [comment] 2020-05-18 15:00
Add this anywhere:
```
bool ValidTemplate(const char *search) {
  char template_name[strlen(SettingsText(SET_TEMPLATE_NAME)) +1];
  char search_name[strlen(search) +1];

  LowerCase(template_name, SettingsText(SET_TEMPLATE_NAME));
  LowerCase(search_name, search);

  return (strstr(template_name, search_name) != nullptr);
}
```

**Comment by arendst** [comment] 2020-05-18 15:02
or use latest commit of development.

**Comment by napcode** [comment] 2020-05-18 15:53
Added some logs for driver init. Using GPIO01 and GPIO03 as RX/TX I do get those logs. Hence, the template matching seems to work but after that, I don't see life signs from the serial interface. If my order went correct, I should have the metered version. I'll probably play around with the code later tonight.

**Comment by Lefuneste83** [comment] 2020-05-18 16:01
I am using 2 SHP10 metering versions. I flashed them with Tuya Convert as I did not want to disassemble them. I used the provided template for the non-metering version which works great except that there is no monitoring.

{"NAME":"BW-SHP10","GPIO":[0,0,0,0,157,21,0,0,0,17,0,0,0],"FLAG":0,"BASE":18}

So I am highly interested in your efforts to communicate with the power metering part. Let me know if I can provide some help.

**Comment by corporalp** [comment] 2020-05-20 08:18
Same config as @Lefuneste83 here, I did use folowing template. 

{"NAME":"BW-SHP10_3","GPIO":[0,107,0,108,157,21,0,0,0,17,134,0,0],"FLAG":0,"BASE":45}

It shows Power, Today, yesterday, total.
Missing voltage & current. 

firmware 8.3.1

**Comment by arendst** [comment] 2020-05-24 11:07
Research....

![IMG_20200524_130246](https://user-images.githubusercontent.com/11044339/82752605-6e1e1100-9dbf-11ea-8aab-1b75f0315465.jpg)

**Comment by MadDoct** [comment] 2020-05-24 11:49
Wow Theo! That was a little bit "overkill" :)

**Comment by arendst** [comment] 2020-05-24 11:52
I seem to have broken it when I tried to remove the top.  So I went a bit further...

Now I want to make sure the serial connection between the BL0940 and the ESP8266 is as you suggested.

**Comment by MadDoct** [comment] 2020-05-24 14:35
Believe me, it is... I tested it with a multimeter in continuity mode...

**Comment by arendst** [comment] 2020-05-24 15:21
You seem to be right.

I still can't monitor any data from the BL0940. I connected wires to Rx and Tx and while powering the device from 5V there is nothing received even when swapping the wires.

There must something more to it to let the BL0940 talk to the ESP8266...

**Comment by MadDoct** [comment] 2020-05-25 08:10
Are you sure it has nothing to do with the 1.5 stop bits?

**Comment by arendst** [comment] 2020-05-25 08:15
It might but I tried faking it and nothing comes through.

I tried a terminal tool too supporting stopbit 1.5 but it fails on my windows PC UART not supporting 1.5 stopbits...

**Comment by napcode** [comment] 2020-05-25 08:58
I didn't manage to get anything either (didn't open the device yet though). Maybe the BL0940 is configured to use SPI insted of UART? According to the manual, pin 10 is used to configure that. Is Pin 10 connected to VDD?

**Comment by arendst** [comment] 2020-05-25 09:06
Thx for the info but this device uses the 10-pin BL0940 which doesn't have SPI.

So serial it is.

**Comment by CervDotBe** [comment] 2020-06-07 08:37
Just asking, is there any update on this?

**Comment by arendst** [comment] 2020-06-07 09:27
Yes.

![IMG_20200607_112015](https://user-images.githubusercontent.com/11044339/83965127-a8081080-a8b1-11ea-8243-08605c5cb536.jpg)

I received my second SHP-10 yesterday and while still running the default tuya code I'm able to monitor the BL0940 chip. I still need to find the correct serial config as I'm currently using a rewritten software serial interface able to talk 1.5 stopbit.

While monitoring the tuya code I noticed I was wrong with the register request codes.

Using the current code you might be able to receive someting by changing the line ``Bl0940Serial->write(0x58);`` into ``Bl0940Serial->write(0x50);``

I'm almost there...

**Comment by s-hadinger** [comment] 2020-06-07 09:30
Just out of curiosity, why do we need support for 1.5 stop bits? Just set to 2 stop bits so data transmitted will have at least 2 bits. As far as I recall, the receiver doesn't care about number of stop bits as pong as there is 1.

**Comment by arendst** [comment] 2020-06-07 09:34
You beat me to it. I was struggling to get the 1.5 stopbit functional and I did receive data but most of it were zeros. Last night I had the eureka moment that the zeros were caused by a voltage difference caused by 5V/3V6 level change; I powered my opto couplers with 5V while the serial data was being provided on a 3V6 level.

Add 2 diodes solved my voltage problem and using two serial terminals on 4800-8N1 they now provide steady readings so yes, we do not need 1.5 stopbits.

The main issue is that the BL0940 documentation is wrong; to read registers I need 0x50 instead of 0x58.

**Comment by arendst** [comment] 2020-06-07 09:36
BTW the optocouplers are needed. I had a 230V shock already this morning.

**Comment by arendst** [comment] 2020-06-07 14:22
Progress:

![image](https://user-images.githubusercontent.com/11044339/83971296-01d10080-a8db-11ea-87a6-0caab9951c90.png)

**Comment by MadDoct** [comment] 2020-06-07 14:52
very cool @arendst !
Can I try it? Do you have test firmware?

**Comment by arendst** [comment] 2020-06-07 15:23
Basic support for BL0940 as used in BW-SHP10 is in current development.

Energy values are not being updated yet.

Use the following template to add energy measurement:
```
{"NAME":"BW-SHP10","GPIO":[0,148,0,207,158,21,0,0,0,17,0,0,0],"FLAG":0,"BASE":18}
```

**Comment by napcode** [comment] 2020-06-08 19:40
Awesome! I flashed 3 SHP10 with the latest development commit and so far it is working nicely.

**Comment by arendst** [comment] 2020-06-09 08:18
Thx for reporting back.

Closing as it has been implemented.

**Closed by arendst** 2020-06-09 08:18 UTC
Labels: feature request (devs?), fixed

**Comment by linkvt** [comment] 2020-06-11 07:09
Hi guys, quick question, does this device still need power monitoring calibration? The [documentation of BL0940](http://www.belling.com.cn/media/file_object/bel_product/BL0940/datasheet/BL0940_V1.1_en.pdf) says it is calibration free but I'm not deeply into this.

The [supported devices page of e.g. Blitzwolf SHP10-P](https://templates.blakadder.com/blitzwolf_SHP10P) still includes the template for power monitoring calibration for this device but AFAIK it would not be needed, right?

**Comment by arendst** [comment] 2020-06-11 07:29
It won't hurt to calibrate I think. Simply use commands Voltageset, Currentset and Powerset. Perhaps just to verify no calibration was needed ;-)

**Comment by yoyolb** [comment] 2020-06-11 20:10
Hi guys. Thank you for your work. I have two metered SHP10: they work fine with latest development build except Energy Today/Yesterday/Total. The value is about 10 times too high.

**Comment by arendst** [comment] 2020-06-12 08:58
Energy Today is calculated using the active_power value returned by the BL0950. Active_power is represented by a value related to power used within one hour.

So a 60W incandescant bulb uses 60W per hour. It should have been called 60Wh.
This translates to 0.060kWh.

To achieve this value every second the active_power is divided by 3600 and fed to the Energy Today counter.

If I use the 60W bulb it indeed increments Energy Today every minute with 0.001kWh resulting in the final 0.060kWh after one hour.

What is your kind of load?
Perhaps you can report the internal BL0940 registers by enabling logging level 4 (``weblog 4``) for a minute to see how the, currently unused, CF pulses increment.

**Comment by Lefuneste83** [comment] 2020-06-12 10:40
Hi guys. Just a quick notice from my experience following your developments. I have tried the suggested template {"NAME":"BW-SHP10","GPIO":[0,148,0,207,158,21,0,0,0,17,0,0,0],"FLAG":0,"BASE":18} against the latest dev version I could get from the repo yesterday (8.3.1.2) that I compiled and uploaded to the device. I previously had a 8.3.1 also compiled and the other recommended template {"NAME":"BW-SHP10","GPIO":[0,107,0,108,157,21,0,0,0,17,134,0,0],"FLAG":0,"BASE":45}.

In 8.3.1 I get instant power working once calibrated.
In 8.3.1.2 I get a fully functional device with voltage and all the data showing and updating nicely once calibrated.
Both had SetOption19 1 and SetOption65 1 (tried also with 0 for the second one).

But I have a weird behavior with the latest dev version and template. Please take it with a grain of salt as I am still investigating. After a random period, the device turns itself off. I have seen this happening several times since yesterday. This seems to occur at random intervals with nothing going on elsewhere in the MQTT queue. This did not seem to occur in 8.3.1. I am rolling back to 8.3.1 now with the previous version of the template to see if this is related to the upgrade.
I have looked into my MQTT queue to see if something external would trigger the OFF command but so far, it seems that the device turns itself off without any command behind sent to it.
I have no retain status anywhere and the device is not integrated yet to any automation, just logged into the broker (with TLS active should I add). Timers are obviously not active.

I see that the latest template requires at least 8.3.1.3+ version but I could not find it as the dev branch seems only at 8.3.1.2. (as of yesterday) I have upped the log levels to try to catch the event that triggers the change of state but I am puzzled as to what causes this event.

Any clues about this ? Maybe the dev branch I used does not have the commits yet ?

**Comment by yoyolb** [comment] 2020-06-12 11:19
Hi guys.

@arendst : my load is a motor (water pump). Current (~6A), voltage (~235V) and power factor (~0.91) are reported as expected. Power values look OK also. I made some tests with a SONOFF POW R2 which gives the same current/voltage/power factor values and correct Energy Today/Yesterday/Total with the same load.
So I think there is a problem in the way Energy is computed with BL0940 chip.

I will try to get and report internal registers as requested.

@Lefuneste83: I have experienced same issue as you with my device that unexpectedly turned off from time to time.

**Comment by arendst** [comment] 2020-06-12 13:35
The power off may be overtemp like I've seen:

```
15:26:14 MQT: tele/shp10/STATE = {"Time":"2020-06-12T15:26:14","Uptime":"0T03:52:15","UptimeSec":13935,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":2,"SSId":"indebuurt_IoT","BSSId":"18:E8:29:CA:17:C1","Channel":11,"RSSI":100,"Signal":-46,"LinkCount":1,"Downtime":"0T00:00:07"}}
15:26:14 MQT: tele/shp10/SENSOR = {"Time":"2020-06-12T15:26:14","ENERGY":{"TotalStartTime":"2020-06-07T14:29:21","Total":2.383,"Yesterday":0.000,"Today":2.343,"Period":161.87,"Power":0.00,"ApparentPower":0.00,"ReactivePower":0.00,"Factor":0.00,"Voltage":238.8,"Current":0.000,"BL0940":{"Temperature":44.0}},"TempUnit":"C"}
15:30:43 SRC: Overtemp
15:30:43 MQT: stat/shp10/RESULT = {"POWER":"OFF"}
15:30:43 MQT: stat/shp10/POWER = OFF
15:30:43 CFG: Saved to flash at F8, Count 182, Bytes 4096
15:31:14 MQT: tele/shp10/STATE = {"Time":"2020-06-12T15:31:14","Uptime":"0T03:57:15","UptimeSec":14235,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":2,"SSId":"indebuurt_IoT","BSSId":"18:E8:29:CA:17:C1","Channel":11,"RSSI":100,"Signal":-46,"LinkCount":1,"Downtime":"0T00:00:07"}}
15:31:14 MQT: tele/shp10/SENSOR = {"Time":"2020-06-12T15:31:14","ENERGY":{"TotalStartTime":"2020-06-07T14:29:21","Total":2.494,"Yesterday":0.000,"Today":2.454,"Period":110.67,"Power":0.00,"ApparentPower":0.00,"ReactivePower":0.00,"Factor":0.00,"Voltage":238.5,"Current":0.000,"BL0940":{"Temperature":43.8}},"TempUnit":"C"}
```
Will investigate as it should overtemp at 90 C

**Comment by arendst** [comment] 2020-06-12 15:00
To monitor if invalid overtemp is causing the power off enable logging level 3 and watch the above shown message when your power goes off.

The latest fix will also report the overtemp temperature.

**Comment by Lefuneste83** [comment] 2020-06-12 15:22
Amazing ! Thanks for the info Theo. I'll have a look at this. FYI, I haven't had a POWER OFF since rolling back to 8.3.1 with previous template so it looks like a side effect so far. I'll push the new version again with logs up to your suggested level.

**Comment by arendst** [comment] 2020-06-12 15:25
Hold on. Just noticed the BL0940 receives valid data but the temp is wau too high causing the overtemp to trigger:

```
17:22:07 BL9: U 151808, I 87296, P 5585408, T 52149
17:22:07 NRG: GlobTemp 9837.2
17:22:07 SRC: Overtemp
17:22:07 MQT: stat/shp10/RESULT = {"POWER":"OFF"}
17:22:07 MQT: stat/shp10/POWER = OFF
17:22:07 CFG: Saved to flash at FB, Count 217, Bytes 4096
```
Currently working on yet another fix :-)

**Comment by Lefuneste83** [comment] 2020-06-12 15:32
Indeed... A tad high... I've installed the new version and increased the log anyhow. Now I am waiting for the event...

**Comment by arendst** [comment] 2020-06-12 15:46
In 8.3.1 there was no energy monitoring for BL0940 hence no overtemp control.

**Comment by Lefuneste83** [comment] 2020-06-12 16:29
I see... This explains the different behavior...

**Comment by Lefuneste83** [comment] 2020-06-12 22:20
Compiled and applied the latest commit, no power off so far (about 4 hours straight vs less than 1 hour before)... Seems fine, will leave it overnight and see what happens.

**Comment by arendst** [comment] 2020-06-13 10:28
@yoyolb the latest commit contains another way of calculating energy usage.

Pls try and report back if the Energy Today values are more in line with what you expect.

**Comment by Lefuneste83** [comment] 2020-06-14 20:06
I haven't had any unexpected power off since yesterday. I still need to validate the power indicator against a known load.

**Comment by yoyolb** [comment] 2020-06-15 07:42
Hello guys.

@arendst  I upload the latest development binary from thehackbox (build time: 20200614 16:01 GMT+2, version 8.3.1.3, commit 3c4fb6c).

Made some tests with a SONOFF POW R2 and BW-SHP10 in series. It looks OK.
Devices are not calibrated.
The load is a water pump, alternatively working and not working for about 40 minutes.

Energy read on SONOFF POW R2: 0,499 kWh
Energy read on BW-SHP10: 0,478 kWh

Since neither SONOFF nor BW are calibrated, I believe the difference (<5%) is "normal".

Thank you a lot.

**Comment by CervDotBe** [comment] 2020-06-20 13:21
CurrentSet on this version (or device?) seems to be in A and not in mA as described in the documentation

**Comment by corporalp** [comment] 2020-06-25 13:49
@arendst  Can you explain how to open the SHP10? After flashing it is not responding any more so I would like to take a look
tnx

**Comment by arendst** [comment] 2020-06-25 14:08
The top is glued on the body. Using a small screwdriver wiggle the glue loose all around the surface and then you must be able to remove it

**Comment by un1te** [comment] 2020-06-25 19:26
where can i find 8.3.1.3 version?
can't see any sensors with  {"NAME":"BW-SHP10","GPIO":[0,107,0,108,157,21,0,0,0,17,134,0,0],"FLAG":0,"BASE":45}.

**Comment by CervDotBe** [comment] 2020-06-26 07:45
http://thehackbox.org/tasmota/

> where can i find 8.3.1.3 version?
> can't see any sensors with {"NAME":"BW-SHP10","GPIO":[0,107,0,108,157,21,0,0,0,17,134,0,0],"FLAG":0,"BASE":45}. using 8.3.1

http://thehackbox.org/tasmota/

**Comment by AdamWeglarz** [comment] 2020-10-23 13:57
Hi,

I have this device. I managed to open it without destroying it completely,
Can you share info how to flash Tasmota into it?
Where to solder vcc gnd tx rx and gpio0 or there is simpler method :-) ?

![122413093_354126735853019_1760284159668359467_n](https://user-images.githubusercontent.com/45738893/97012595-4686cc80-1548-11eb-9f51-b2c9d8686824.jpg)

**Comment by arendst** [comment] 2020-10-23 14:18
Look at the picture up in this thread. It contains labels near the test points. One of them is called IO0. That's gpio0.

**Comment by napcode** [comment] 2020-10-23 16:53
You can flash these devices with tuya-convert. There is no need to open
them anymore.

**Comment by AdamWeglarz** [comment] 2020-10-23 20:31
Hi,

I have one more question:
{"NAME":"BW-SHP10","GPIO":[0,107,0,108,157,21,0,0,0,17,134,0,0],"FLAG":0,"BASE":45}
I am using this template and power consumption is not realistic. It shows 2watts on ender 3 printing :D 
Should I calibrate it or there is better template?

Adam

**Comment by dogbolt** [comment] 2020-11-05 16:35
I have just successfully flashed 10 of these devices with tuya-convert, but in doing so I discovered and repaired an internal hardware fault resulting in completely dead device with no LED activity etc. My device did not have the power monitoring chip. Thanks to the contributors on this page who confirmed how to open the device. I caused negligible physical damage, and the device is back working OK now.

The approach I adopted was to squeeze the body of the device in a vice and then gently, one millimetre at a time, went around the groove with very fine flat-bladed screwdriver levering the 2 parts apart. Every couple of millimetres there was a slight 'snik' sound as the joint progressively cracked open. Then I was able to check the voltages on the board but all were zero relative to ground everywhere. 

To get further inside, I had to unsolder the 3 large L N E connections to remove the circuit board assembly. On inspection all 4 solder connections between the rear board and the small riser board were completely cracked through and were not providing support nor electrical connection. I resoldered the joints and reassembled the unit. I was then able to flash it, and it is now working correctly.

I hope this will be of use to anyone looking for information on opening and repairing these units.

![BW-SHP10-repair](https://user-images.githubusercontent.com/73639447/98268393-5e1c7700-1f84-11eb-8c14-46859b44e2c1.jpg)

**Comment by peterk6502** [comment] 2021-01-11 20:49
I did not read the tuya-convert instructions carefully, therefore I ended up with also with an dead SHP10 switch.
The curl trick didn't work also, therefore the only option left was to open the device and flash it directly.
I have made some recordings and pictures, maybe it is to some use to somebody (see youtube link).
[https://www.youtube.com/watch?v=o0oZF238xc0](url)

**Comment by alexelite** [comment] 2022-01-19 18:37
Hi, 

Last year I bought a dozen BlitzWolf BW-SHP10-P and opened them up using the vise method.
I disassembled one completely and tested it without the black plastic shield. It started arcing the moment I plugged it in the outlet without any load connected. 
The distance between a capacitor from the power supply and one of the power prong mounting points is very small and it arched. Also it arched between what looks like a fuse and the earth connection. 
![20211125_203434](https://user-images.githubusercontent.com/2135472/150189583-b0d1db17-5ded-4632-9245-0891d9a53e7b.jpg)
![20211125_202949](https://user-images.githubusercontent.com/2135472/150189568-de33eb51-bbed-45d8-a540-008296fcfb8a.jpg)


The plastic shield was even embossed from the metal mounting point.
![20211125_203530](https://user-images.githubusercontent.com/2135472/150189580-8d113b19-d363-462a-9da3-f86496d7800f.jpg)
![20211125_202927](https://user-images.githubusercontent.com/2135472/150189589-9ca408f2-c9c7-4a94-947f-45e93452f7dd.jpg)

I used some playdough to check the distance and it is very tiny.
![20211125_203944](https://user-images.githubusercontent.com/2135472/150189575-a46af3c2-295e-4a71-b291-84ddfb77ae21.jpg)
The plastic shield has a low melting point so some excessive heating in that area could lead to arching.

The arching was not enough to trip the 30mA RCD or the 16A breaker and I don't have arc fault circuit interrupters installed.
Probably with enough time it would lead to melting and even fire. To mitigate this I installed mica insulating sheets cut to size before reinstalling the PCB.

**Comment by bilogic** [comment] 2023-05-08 14:23
![image](https://user-images.githubusercontent.com/946010/236849416-2e835b38-daf1-4c2f-9626-5d2a6dd79c8d.png)

On my 2nd unit, it reports all 0s, unlike the 1st unit , this was never powered on while it was using the Tuya firmware.

**Comment by bilogic** [comment] 2023-05-09 02:30
Was the code tested only against BW-SHP10's BL0940? Or with others as well?

**Comment by barbudor** [comment] 2023-05-09 18:13
The only other device in the template repository that is using BL0940 is this one https://templates.blakadder.com/homcloud_AS-SM1E.html
Doesn't seem much common

So it's likely that Blitzwolf BW-SHP10P is probably the main device using it

From the datasheet, the BL0940 can also work in SDI mode.
So could it be possible that your device use that other mode (which is currently not supported by tasmota) ?

Have you opened the device ? Can you try to find out how the BL040 is connected to the ESP ? Which GPIOs (all of them) ?

**Comment by bilogic** [comment] 2023-05-09 18:55
# GPIO
1. 14
2. 13 (Button)
3. 4 (LED)
4. RX
5. VCC

6. 12
7. 5 (Relay)
8. TX
9. GND

Yes, it's opened. These are the pins with solder points. As the device works with SWA9 template, GPIO 13, 4 and 5 should be correct.

**Comment by bilogic** [comment] 2023-05-09 18:57
![20230510_025607](https://github.com/arendst/Tasmota/assets/946010/4175babb-55d2-4a10-9f7a-b87078ee8f51)
`SWA9S`

**Comment by barbudor** [comment] 2023-05-09 22:06
You didn't track the GPIO to the BL0940
This is what we are looking for

If BL0940 is connected in Serial, it should be connected to TX (GPIO1) and RX (GPIO3)
GPIO1/TX should be set to "Serial TX" and GPIO3/RX should be set to "BL0940 RX"

Or translated in "template" : `{"NAME":"SWA9","GPIO":[0,3200,0,5056,288,224,0,0,0,32,0,0,0,0],"FLAG":0,"BASE":18}`

**Comment by bilogic** [comment] 2023-05-10 00:22
![image](https://github.com/arendst/Tasmota/assets/946010/d6d9ac47-c279-4104-b287-5a0d5fa05117)

I reconfigured GPIO1 and GPIO3, now I'm getting the right voltage and probably temp!

What does "track" mean? I simply went by deduction when I saw only GPIO 12 and 14 remaining.

**Comment by barbudor** [comment] 2023-05-10 11:45
"track" as in follow the path of someone or an animall

So follow the PCB tracks from the esp device to the other parts using eyes and optionaly a test device like an ohmmeter

Glad it works don't forget to go through the calibration process

And please add an entry in the template repository

**Comment by Le-Duc0069** [comment] 2024-05-16 05:29
I have a problem that needs to be solved, I am connecting bl0940 with tasmota connected to GPIO16 and 17 but do not see the electrical measurement parameters. Can anyone help me fix this error? 
![IMG_2046](https://github.com/arendst/Tasmota/assets/134246880/66a5c42b-e866-4aae-9377-31045598a806)
![IMG_2047](https://github.com/arendst/Tasmota/assets/134246880/1d5b35b0-0130-4b3b-a068-40328b731a0d)
