### ISSUE TITLE
Wiki addition - list of confirmed unsupported devices

### ISSUE THREAD

**Issue by tmiklas** [arendst/Tasmota#7030] opened 2019-11-25 20:34 UTC
Hi

How about adding a page for **Known - Unsupported** devices to the Wiki?

At the moment wiki says what is supported but it may make sense to have exceptions list - would save people time and money buying devices that won't work.

I can start

- [Teckin SP23](https://www.amazon.co.uk/gp/product/B07STZ1V3J/) (November 2019, Amazon UK) - `tuya-convert` says it appears device does not use ESP82xx chip, possibly moved to Realtek - will not flash
- [Teckin SP27](https://www.amazon.co.uk/gp/product/B07YY9NKSF/) (November 2019, Amazon UK) - `tuya-convert` says it appears device does not use ESP82xx chip, possibly moved to Realtek - will not flash

Tomasz

**Comment by meingraham** [comment] 2019-11-25 21:24
The problem is that for some device models, some are compatible and some are not - they've changed some newer ones to RealTek. Perhaps not these two examples, but to know which are which will be difficult to maintain accurately. For now, if there is a Template for the device in the repository, then, at some point in time, the device was successfully flashed and configured with Tasmota.

**Comment by ascillato2** [comment] 2019-11-25 21:39
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2019-11-25 21:39 UTC
