### ISSUE TITLE
Aqara(Xiaomi) E1 Door & Window Sensor (MCCGQ14LM) not working

### ISSUE THREAD

**Issue by f45tb00t** [arendst/Tasmota#13843] opened 2021-11-28 21:11 UTC
### PROBLEM DESCRIPTION
Hello,

I am using Tasmota v10.0.0(zbbridge) since today. I was with v9.4.0 before. Unfortunately the new Aqara devices are not working.

It seems the firmware needs to be upgraded.

Here are some references:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403
https://github.com/Koenkk/zigbee2mqtt/issues/9274
https://github.com/home-assistant/core/issues/58985

@theo: Is there anything you can do?

Kind regards

fb

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Bridge
- [x] Tasmota binary firmware version number used: 10.0.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
- Just use the E1

### EXPECTED BEHAVIOUR
- Battery Status
-  Open/Closed Status

### SCREENSHOTS
None

### ADDITIONAL CONTEXT
None

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-11-28 22:16
Moving to discussions as this is a feature request and not a bug report. Thanks.

**Closed** 2021-11-28 22:17 UTC
Labels: feature request (devs?)
