### ISSUE TITLE
SML json SENSOR invalid

### ISSUE THREAD

**Issue by OCIN91** [arendst/Tasmota#11680] opened 2021-04-12 08:43 UTC
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
JSON Template not Valid by use SML Meter
{"Time":"2021-04-12T09:37:42","SML  ":{"Total_in":720.2593,"Total_out":1091.3074,"Power_curr":-821  ,"daily_consumption":0.00,"daily_feed":0.00  }

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): ESP2866 -Wemos D1
- [x ] Tasmota binary firmware version number used: 9.3.1.2
  - [ ] Pre-compiled
  - [ x] Self-compiled
- [ x] Flashing tools used: Visual Studio with Plattform IO
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
 Expecting ending } in STATUS JSON 

Error:  [Code 22, Structure 27]

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Used Script
>D  
pin=0  
pout=0  
pi_d=0  
po_d=0  
hr=0  
; permanent midnight values  
p:pi_m=0  
p:po_m=0  
>B  
->sensor53 r  
>T  
; get total consumption and total feed  
pin=SML#Total_in  
pout=SML#Total_out  
>S  
; at midnight, save meter total values  
hr=hours  
if chg[hr]>0  
and hr==0  
then  
pi_m=pin  
po_m=pout  
svars  
endif  
; on teleperiod calculate current daily values from midnight  
if upsecs%tper==0  
then  
pi_d=pin-pi_m  
po_d=pout-po_m  
endif  
; show these values on WEB UI  
>W  
Tagesverbrauch: {m} %pi_d% kWh  
Tageseinspeisung: {m} %po_d% kWh    
; transmit these values with MQTT  
>J  
,"daily_consumption":%pi_d%,"daily_feed":%po_d%  
; meter definition  
>M 1  
+1,3,s,0,9600,SML  
1,77070100010800ff@1000,Total Consumed,KWh,Total_in,4  
1,77070100020800ff@1000,Total Delivered,KWh,Total_out,4  
1,77070100100700ff@1,Current Consumption,W,Power_curr,0  
1,77070100000009ff@#,Meter Number,,Meter_number,0  
#

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment] 2021-04-12 10:58
this was a bug in a previous version. please use last dev version.

**Comment by ascillato2** [comment] 2021-04-12 12:15
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by OCIN91** [comment] 2021-04-13 09:29
> this was a bug in a previous version. please use last dev version.

I have Compiled the last dev yesterday, same issure

**Comment by gemu2015** [comment] 2021-04-13 15:50
this is indeed a bug. it is caused by your meter number not being updated from your meter.
if you delete the last decoder line the problem should be fixed.

but you may also try this version. it should fix the bug also.

[xsns_53_sml.ino.zip](https://github.com/arendst/Tasmota/files/6304999/xsns_53_sml.ino.zip)

**Closed** 2021-04-15 21:03 UTC
Labels: bug, fixed
