### ISSUE TITLE
Tasmota v13.0.0 IRHVAC GREE { ,"Light":"On", } not work

### ISSUE THREAD

**Issue by hamadfayyad** [arendst/Tasmota#19231] opened 2023-07-31 15:38 UTC
Tasmota v13.0.0 IRHVAC gree { ,"**Light":"On**", } not work

i  downgrade to  Tasmota 12.5.0 it's working

**Comment by Jason2866** [comment] 2023-08-15 17:49
Try latest release

**Comment by Jason2866** [comment] 2023-08-25 13:15
Closing since no feedback. Feel free to reopen when the issue is still there with latest Tasmota version

**Closed by Jason2866** 2023-08-25 13:15 UTC
Labels: awaiting feedback
