### ISSUE TITLE
MI32_BLE device MJYD2S missing motion entity

### ISSUE THREAD

**Issue by abu9** [arendst/Tasmota#12916] opened 2021-08-18 04:53 UTC
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Could not found the binary motion sensor entity for MJYD2S in WebUI, MQTT message and Homeassistant.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32-DevKit v1
- [x] Tasmota binary firmware version number used: ESP32 9.5.0(bluetooth)
  - [x] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: ESP-Flasher-Windows-x64
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
12:34:48.387 MQT: stat/tasmota_6621B0/STATUS0 = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_6621B0","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":5,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"1T02:59:58","StartupUTC":"2021-08-17T01:34:50","Sleep":50,"CfgHolder":4617,"BootCount":5,"BCResetTime":"2021-08-17T01:31:26","SaveCount":15},"StatusFWR":{"Version":"9.5.0(bluetooth)","BuildDateTime":"2021-08-16T17:26:25","Core":"1_0_6","SDK":"v3.3.5-1-g85c43024c","CpuFrequency":80,"Hardware":"ESP32-D0WDQ6","CR":"390/699"},"StatusLOG":{"SerialLog":4,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxxx",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005A0A000000000000","00000280","00006000","00000002"]},"StatusMEM":{"ProgramSize":1504,"Free":1856,"Heap":118,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","00140001","000000CF","010013C0","40000981","00004080","00200000","00000024"],"Drivers":"1,2,3,4,5,7,8,9,10,12,20,21,24,26,27,29,38,50,79","Sensors":"1,2,3,5,6,52,62,87"},"StatusNET":{"Hostname":"tasmota_6621B0-0432","IPAddress":"192.168.3.28","Gateway":"192.168.3.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.3.1","Mac":"7C:9E:xx","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.2.253","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_6621B0","MqttUser":"xxx","MqttCount":3,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2021-08-18T04:34:48","Local":"2021-08-18T12:34:48","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+08:00","Sunrise":"12:47","Sunset":"02:59"},"StatusSNS":{"Time":"2021-08-18T12:34:48","ESP32":{"Temperature":52.2},"TempUnit":"C"},"StatusSTS":{"Time":"2021-08-18T12:34:48","Uptime":"1T02:59:58","UptimeSec":97198,"Heap":115,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":3,"Wifi":{"AP":1,"SSId":"xxx","BSSId":"88:C3:xx","Channel":6,"Mode":"11n","RSSI":100,"Signal":-37,"LinkCount":1,"Downtime":"0T00:00:06"}}}


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/2047272/129838656-4e92ec5b-c875-4a02-86f8-1ac2c09d214e.png)
![image](https://user-images.githubusercontent.com/2047272/129838693-377afd1f-6784-4548-9f3a-e70c8ce802b5.png)

The device works fine with Homeassistant Passive BLE Monitor integration
![image](https://user-images.githubusercontent.com/2047272/129838965-66d2a68e-e009-4ce7-80d7-31b3e7f25528.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

```lua
  BLEDebug:
13:16:13.482 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:13.484 M32: MI:5859F6073C57A23727D128AF9FD173FABAEB030012266FC5
13:16:13.487 M32: Search key for MAC: 28d12737a257
13:16:13.490 M32: Decryption Key found
13:16:13.494 M32: Err:1, Decrypted : 00 03 64 00 00
13:16:13.497 M32 28D12737A257: Payload decrypted
13:16:13.501 M32: Frame 60, last 56
13:16:13.504 M32: MI32: slot: 2/4
13:16:13.509 M32: MI2 payload 0F0003640000
13:16:13.523 MQT: tele/tasmota_ble/MJYD2S37a257 = {"Time":"2021-08-18T13:16:13","mac":"28d12737a257","Illuminance":100,"Events":295,"Battery":91,"RSSI":-89}
13:16:13.530 M32: MI32: triggered 3 {"Time":"2021-08-18T13:16:13","mac":"28d12737a257","Illuminance":100,"Events":295,"Battery":91,"RSSI":-89}
13:16:14.111 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:14.113 M32: MI:5859F6073C57A23727D128AF9FD173FABAEB030012266FC5
13:16:14.115 M32: Search key for MAC: 28d12737a257
13:16:14.118 M32: Decryption Key found
13:16:14.123 M32: Err:1, Decrypted : 00 03 64 00 00
13:16:14.127 M32 28D12737A257: Payload decrypted
13:16:14.132 M32: MI32: slot: 2/4 - ign repeat
13:16:14.135 M32: Frame 60, last 60
13:16:14.137 M32: MI32: slot: 2/4
13:16:14.141 M32: MI2 payload 0F0003640000
13:16:14.165 MQT: tele/tasmota_ble/MJYD2S37a257 = {"Time":"2021-08-18T13:16:14","mac":"28d12737a257","Illuminance":100,"Events":296,"Battery":91,"RSSI":-89}
peatp313:16:15.745 M32: Frame 60, last 60q413:16:15.748 M32: MI32: slot: 2/4r413:16:15.752 M32: MI2 payload 0F0003640000ast 604 - ign r
13:16:15.843 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:15.726 M32: MI:5859F6073C57A23727D128AF9FD173FABAEB030012266FC5
13:16:15.730 M32: Search key for MAC: 28d12737a257
13:16:15.732 M32: Decryption Key found
13:16:15.735 M32: Err:1, Decrypted : 00 03 64 00 00
13:16:15.738 M32 28D12737A257: Payload decrypted
13:16:15.741 M32: MI32: slot: 2/4 - ign repeat
13:16:15.745 M32: Frame 60, last 60
13:16:15.748 M32: MI32: slot: 2/4
13:16:15.752 M32: MI2 payload 0F0003640000
13:16:15.843 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:15.846 M32: MI:5859F6073C57A23727D128AF9FD173FABAEB030012266FC5
13:16:15.849 M32: Search key for MAC: 28d12737a257
13:16:15.852 M32: Decryption Key found
13:16:15.854 M32: Err:1, Decrypted : 00 03 64 00 00
13:16:15.858 M32 28D12737A257: Payload decrypted
13:16:15.866 M32: MI32: slot: 2/4 - ign repeat
13:16:15.871 M32: Frame 60, last 60
13:16:15.873 M32: MI32: slot: 2/4
13:16:15.876 M32: MI2 payload 0F0003640000
13:16:15.718 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:15.726 M32: MI:5859F6073C57A23727D128AF9FD173FABAEB030012266FC5
13:16:15.730 M32: Search key for MAC: 28d12737a257
13:16:15.732 M32: Decryption Key found
13:16:15.735 M32: Err:1, Decrypted : 00 03 64 00 00
13:16:15.738 M32 28D12737A257: Payload decrypted
13:16:15.741 M32: MI32: slot: 2/4 - ign repeat
13:16:15.745 M32: Frame 60, last 60
13:16:15.748 M32: MI32: slot: 2/4
13:16:15.752 M32: MI2 payload 0F0003640000
13:16:15.843 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:15.846 M32: MI:5859F6073C57A23727D128AF9FD173FABAEB030012266FC5
13:16:15.849 M32: Search key for MAC: 28d12737a257
13:16:15.852 M32: Decryption Key found
13:16:15.854 M32: Err:1, Decrypted : 00 03 64 00 00
13:16:15.858 M32 28D12737A257: Payload decrypted
13:16:15.866 M32: MI32: slot: 2/4 - ign repeat
13:16:15.871 M32: Frame 60, last 60
13:16:15.873 M32: MI32: slot: 2/4
13:16:15.876 M32: MI2 payload 0F0003640000
13:16:16.764 MQT: tele/tasmota_ble/MJYD2S37a257 = {"Time":"2021-08-18T13:16:16","mac":"28d12737a257","Illuminance":100,"Events":298,"Battery":91,"RSSI":-92}
13:16:16.771 M32: MI32: triggered 3 {"Time":"2021-08-18T13:16:16","mac":"28d12737a257","Illuminance":100,"Events":298,"Battery":91,"RSSI":-92}
13:16:17.097 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:17.100 M32: MI:4859F6073D66A9D37FFF990DEB0300E660D62E
13:16:17.102 M32: Search key for MAC: 57a23727d128
13:16:17.105 M32: No Key found
13:16:17.107 M32 28D12737A257: Payload encrypted but no key
13:16:17.113 M32: MI packet with MAC addr mismatch - is this mesh?
13:16:17.117 M32: MI32: new MJYD2S at slot: 4
13:16:17.121 M32: MIParsePacket returned 0
13:16:17.192 M32: Dev no longer present MAC: 000000000000
13:16:17.737 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:17.740 M32: MI:4859F6073D66A9D37FFF990DEB0300E660D62E
13:16:17.743 M32: Search key for MAC: 57a23727d128
13:16:17.745 M32: No Key found
13:16:17.747 M32 28D12737A257: Payload encrypted but no key
13:16:17.760 M32: MI packet with MAC addr mismatch - is this mesh?
13:16:17.763 M32: MI32: new MJYD2S at slot: 4
13:16:17.765 M32: MIParsePacket returned 0
13:16:17.930 M32: MI:A4C1382519E7 svc[0] UUID (181a)
13:16:17.933 M32: MI:E7192538C1A41E0CD11C890B53D604
13:16:17.936 M32: MI32: slot: 3/5 - ign repeat
13:16:17.939 M32: Frame 214, last 214
13:16:17.942 M32: MI32: slot: 3/5
13:16:17.944 M32: ATC:pvvx at slot 3
13:16:18.050 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:18.052 M32: MI:4859F6073D66A9D37FFF990DEB0300E660D62E
13:16:18.056 M32: Search key for MAC: 57a23727d128
13:16:18.060 M32: No Key found
13:16:18.062 M32 28D12737A257: Payload encrypted but no key
13:16:18.069 M32: MI packet with MAC addr mismatch - is this mesh?
13:16:18.073 M32: Frame 61, last 0
13:16:18.075 M32: MI32: slot: 4/5
13:16:18.077 M32: MIParsePacket returned 0
13:16:18.192 M32: Dev no longer present MAC: 000000000000
13:16:18.377 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:18.380 M32: MI:4859F6073D66A9D37FFF990DEB0300E660D62E
13:16:18.382 M32: Search key for MAC: 57a23727d128
13:16:18.385 M32: No Key found
13:16:18.389 M32 28D12737A257: Payload encrypted but no key
13:16:18.392 M32: MI packet with MAC addr mismatch - is this mesh?
13:16:18.397 M32: MI32: new MJYD2S at slot: 4
13:16:18.401 M32: MIParsePacket returned 0
2 28D12737A257: Payload encrypted but no key�113:16
13:16:18.778 M32: MI:4859F6073D66A9D37FFF990DEB0300E660D62E
13:16:18.786 M32: Search key for MAC: 57a23727d128
13:16:18.789 M32: No Key found
13:16:18.791 M32 28D12737A257: Payload encrypted but no key
13:16:18.794 M32: MI packet with MAC addr mismatch - is this mesh?
13:16:18.799 M32: Frame 61, last 0
13:16:18.802 M32: MI32: slot: 4/5
13:16:18.804 M32: MIParsePacket returned 0
13:16:19.192 M32: Dev no longer present MAC: 000000000000
13:16:19.219 M32: MI:28D12737A257 svc[0] UUID (fe95)
13:16:19.223 M32: MI:4859F6073D66A9D37FFF990DEB0300E660D62E
13:16:19.226 M32: Search key for MAC: 57a23727d128
13:16:19.228 M32: No Key found
13:16:19.230 M32 28D12737A257: Payload encrypted but no key
13:16:19.233 M32: MI packet with MAC addr mismatch - is this mesh?
13:16:19.240 M32: MI32: new MJYD2S at slot: 4
13:16:19.245 M32: MIParsePacket returned 0
13:16:22.955 M32: MI:A4C1382519E7 svc[0] UUID (181a)
13:16:22.958 M32: MI:E7192538C1A41F0CCD1C840B53D704
13:16:22.960 M32: Frame 215, last 214
```
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-08-18 10:12
Moving to discussions as this is a feature request and not a bug report.

**Closed** 2021-08-18 10:13 UTC
Labels: feature request (devs?)
