### ISSUE TITLE
WiFi brooked by "sleep 0"

### ISSUE THREAD

**Issue by to-scho** [arendst/Tasmota#7526] opened 2020-01-15 18:29 UTC
### PROBLEM DESCRIPTION
When calling "sleep 0" there is no WiFi connectivity any more. In STA mode Tasmota tries to connect again and again to WiFi AP (was working fine until sleep 0) without success. In AP mode WiFi Manager is started but SSID never becomes visible to my PC.
  
This is independent from SetOption60 setting.

Unfortunately a module factory reset is the only way to get out of this again.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Basic
- [x] Tasmota binary firmware version number used: 8.1.0.3
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
From serial monitor:

00:00:12 WIF: Connected
00:00:12 HTP: Web server active on tasmota-5646 with IP address 192.168.42.24
19:19:03 CMD: sleep 0
19:19:03 RSL: stat/tasmota/RESULT = {"Sleep":{"0":{"Active":"0"}}}
19:19:26 WIF: Connect failed as AP cannot be reached
19:19:26 WIF: Connecting to AP1 SPIDER_NET_WLAN_FB in mode 11N as tasmota-5646...
19:19:35 WIF: Connect failed as AP cannot be reached
19:19:36 WIF: Connect failed as AP cannot be reached
19:19:36 WIF: Connecting to AP1 SPIDER_NET_WLAN_FB in mode 11N as tasmota-5646...
19:19:43 RSL: stat/tasmota/RESULT = {"POWER":"ON"}
19:19:43 RSL: stat/tasmota/POWER = ON

19:19:50 WIF: Connect failed as AP cannot be reached
19:19:51 WIF: Connect failed as AP cannot be reached
19:19:51 WIF: Connecting to AP1 SPIDER_NET_WLAN_FB in mode 11N as tasmota-5646...
19:20:00 WIF: Connect failed as AP cannot be reached
19:20:01 WIF: Connect failed as AP cannot be reached
19:20:01 WIF: Connecting to AP1 SPIDER_NET_WLAN_FB in mode 11N as tasmota-5646...
19:20:10 WIF: Connect failed as AP cannot be reached
19:20:11 WIF: Connect failed as AP cannot be reached
19:20:11 WIF: Connecting to AP1 SPIDER_NET_WLAN_FB in mode 11N as tasmota-5646...
19:20:20 WIF: Connect failed as AP cannot be reached
19:20:21 WIF: Connect failed as AP cannot be reached
19:20:22 WIF: Connecting to AP1 SPIDER_NET_WLAN_FB in mode 11N as tasmota-5646...
19:20:27 RSL: stat/tasmota/RESULT = {"Reset":"Reset and Restarting"}
19:20:27 CFG: Use defaults
19:20:30 WIF: WifiManager active for 3 minutes
19:20:30 HTP: Web server stopped
19:20:31 HTP: Web server active on tasmota-5646 with IP address 192.168.4.1
19:20:31 APP: Restarting



```

### TO REPRODUCE
Pure Tasmota build, attach to Wifi, type "sleep 0" to console, dead

### EXPECTED BEHAVIOUR
According to wiki sleep 0 should disable power saving and not the device ;-)

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment] 2020-01-15 19:16
It is not a bug in Tasmota. You have a bad hardware. Weak power supply and / or heat management of
the ESP.

**Comment by ascillato2** [comment] 2020-01-15 19:41
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2020-01-15 19:41 UTC
