### ISSUE TITLE
Support for Tuya irrigitation valve

### ISSUE THREAD

**Issue by ahorseman** [arendst/Tasmota#15672] opened 2022-05-23 18:10 UTC
### PROBLEM DESCRIPTION
Hello!

I've bought a Tuya irrigitation valve (https://zigbee.blakadder.com/RTX_ZVG1.html) and I expected it's well supported using ZigBee. I am able to include the valve and use it so far that I can power on or off the valve. However, I have not yet figured out how to - for instance - set the timer value or find any other possible settings.

I hope I am here in the right place, to ask for help regarding that ZigBee Device and Tasmota and whether support for it can be included.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff ZigBee Bridge
- [X] Tasmota binary firmware version number used: 11.1.0.3
  - [X] Pre-compiled
- [X] Flashing tools used: Tasmotizer
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
19:05:24.424 MQT: stat/zbbridge_E4DB3A/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
19:05:24.643 MQT: stat/zbbridge_E4DB3A/RESULT = {"Module":{"75":"Sonoff ZbBridge"}}
19:05:24.896 MQT: stat/zbbridge_E4DB3A/RESULT = {"GPIO0":{"320":"Led_i1"},"GPIO1":{"3552":"Zigbee Tx"},"GPIO2":{"0":"None"},"GPIO3":{"3584":"Zigbee Rx"},"GPIO4":{"5312":"Zigbee Rst1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"640":"I2C SDA"},"GPIO13":{"576":"LedLink_i"},"GPIO14":{"608":"I2C SCL"},"GPIO15":{"0":"None"},"GPIO16":{"32":"Button1"},"GPIO17":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
---

### EXPECTED BEHAVIOUR
The device output is this:

19:06:39.885 CMD: ZbStatus3 Watering
19:06:39.886 SRC: WebConsole from 172.16.2.102
19:06:39.888 CMD: Grp 0, Cmnd 'ZBSTATUS', Idx 3, Len 18, Data 'Watering'
19:06:39.895 MQT: stat/zbbridge_E4DB3A/RESULT = {"ZbStatus3":[{"Device":"0x2ED1","Name":"Watering","IEEEAddr":"0x79E281EFFF186FC8","ModelId":"TS0601","Manufacturer":"_TZE200_akjefhj5","Endpoints":[1],"Config":["~01.1"],"Reachable":true,"LastSeen":44,"LastSeenEpoch":1653329155,"LinkQuality":37}]}

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2022-05-23 19:02
Thanks for posting. Moving this issue to Ideas in Discussions as this is a feature request and not a bug report.

**Closed by ascillato2** 2022-05-23 19:02 UTC
Labels: feature request (devs?)
