### ISSUE TITLE
Hiking Single Phase 65A DIN Rail Energy Meter (DDS238-2): wrong VAr (0VAr), PowerFactor (1,0)

### ISSUE THREAD

**Issue by g6094199** [arendst/Tasmota#15760] opened 2022-06-05 10:48 UTC
### PROBLEM DESCRIPTION
MQTT sending wrong power factor cosPhi and reactive power. cosPhi is alway 1,0 and thus VAr must be 0W. But this cant be true since Power and Apparent Power are NOT the same. Which tells that cosPhi CANT be 1,0, which must be true in reallife. So something must be miscalculated in tasmota.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Hiking Single Phase 65A DIN Rail Energy Meter (DDS238-2
- [x] Tasmota binary firmware version number used: 11.1.0.4
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here: 11:59:22.399 MQT: tele/tasmota_C64D61/SENSOR = {"Time":"2022-06-05T11:59:22","ENERGY":{"TotalStartTime":"2022-06-05T09:16:09","Total":97.932,"Yesterday":3.240,"Today":0.562,"Period":19.9,"Power":232.2,"ApparentPower":233.1,"ReactivePower":0.0,"Factor":1.00,"Voltage":233.3,"Current":0.999}}
11:59:29.603 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived":{"Data":"55AA03070005010100010112","Cmnd":7,"CmndData":"0101000101","DpType1Id1":1,"1":{"DpId":1,"DpIdType":1,"DpIdData":"01"}}}
11:59:29.610 TYA: fnId=99 is set for dpId=1
11:59:29.645 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived":{"Data":"55AA03070008090200040000000020","Cmnd":7,"CmndData":"0902000400000000","DpType2Id9":0,"9":{"DpId":9,"DpIdType":2,"DpIdData":"00000000"}}}
11:59:29.655 TYA: fnId=36 is set for dpId=9
11:59:29.656 TYA: RX value 0 from dpId 9 
11:59:29.664 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived":{"Data":"55AA030700086502000400002641E3","Cmnd":7,"CmndData":"6502000400002641","DpType2Id101":9793,"101":{"DpId":101,"DpIdType":2,"DpIdData":"00002641"}}}
11:59:29.672 TYA: fnId=37 is set for dpId=101
11:59:29.674 TYA: RX value 9793 from dpId 101 
11:59:29.676 TYA: Rx ID=101 Total_Power=9793
11:59:29.678 NRG: EnergyTotal[0] 97.9300 kWh
11:59:29.685 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived":{"Data":"55AA0307000812020004000003E612","Cmnd":7,"CmndData":"12020004000003E6","DpType2Id18":998,"18":{"DpId":18,"DpIdType":2,"DpIdData":"000003E6"}}}
11:59:29.693 TYA: fnId=32 is set for dpId=18
11:59:29.695 TYA: RX value 998 from dpId 18 
11:59:29.697 TYA: Rx ID=18 Current=998
11:59:29.703 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived":{"Data":"55AA03070008130200040000091346","Cmnd":7,"CmndData":"1302000400000913","DpType2Id19":2323,"19":{"DpId":19,"DpIdType":2,"DpIdData":"00000913"}}}
11:59:29.712 TYA: fnId=31 is set for dpId=19
11:59:29.714 TYA: RX value 2323 from dpId 19 
11:59:29.716 TYA: Rx ID=19 Active_Power=2323
11:59:29.723 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived":{"Data":"55AA03070008140200040000092054","Cmnd":7,"CmndData":"1402000400000920","DpType2Id20":2336,"20":{"DpId":20,"DpIdType":2,"DpIdData":"00000920"}}}
11:59:29.732 TYA: fnId=33 is set for dpId=20
11:59:29.734 TYA: RX value 2336 from dpId 20 
11:59:29.736 TYA: Rx ID=20 Voltage=2336

```

### TO REPRODUCE
Install and setup like in [template](https://templates.blakadder.com/hiking_DDS238-2.html)

### EXPECTED BEHAVIOUR
VAr is almost never 0VAr und thus cosPhi can be 1,0,  physically almost impossible in reallife.

### SCREENSHOTS
![Bildschirmfoto vom 2022-06-05 12-04-11](https://user-images.githubusercontent.com/37833326/172046477-50dd314c-c16a-4e8b-9c9b-0c7d2595fc62.png)

**Comment by arendst** [comment] 2022-06-05 11:37
Ever heard of rounding numbers? Your difference is 0.7VA. So power factor is 226,7W / 227,4VA = 0.997. With a fixed resolution set to 2 this is rounded up to 1.

**Comment by sfromis** [comment] 2022-06-05 12:32
If you want more decimals on the power factor, you can modify that number in the source code
https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xdrv_driver/xdrv_03_energy.ino#L1225
`EnergyFormat(value3_chr, power_factor, 2));`

**Comment by Jason2866** [comment] 2022-06-05 17:10
Closing since answered and does work as designed

**Closed by Jason2866** 2022-06-05 17:10 UTC
