### ISSUE TITLE
German languange texts with default en-GB configuration

### ISSUE THREAD

**Issue by tiagofreire-pt** [arendst/Tasmota#7916] opened 2020-03-14 16:14 UTC
### PROBLEM DESCRIPTION

German texts with webUI in english:

![image](https://user-images.githubusercontent.com/41837236/76685800-5e8b8a80-660e-11ea-80d0-204ab3f7d80a.png)

This is straight from a compiled Tasmota development version, on adding the procedures and lines stated in the wiki for Smart Meters.

No `MY_LANGUAGE` settings were changed or defined.

### REQUESTED INFORMATION
- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Wemos D1 mini
- [x] Tasmota binary firmware version number used: development as 13/03/2020
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: Arduino 1.8.3
- [X] Flashing tools used: USB
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:

Default.

```
### TO REPRODUCE
N/A

### EXPECTED BEHAVIOUR
The texts should be all in english (default en-GB)

### ADDITIONAL CONTEXT
N/A

**Comment by arendst** [comment] 2020-03-14 16:56
This is caused by xsns_53_sml.ino. Disable define USE_SML_M and the messages will be gone.

The code owner will need to revisit the functionality of this: 
```
#if MY_LANGUAGE==de-DE
// german web text
#define D_TPWRIN "Verbrauch"
#define D_TPWROUT "Einspeisung"
#define D_TPWRCURR "Aktueller Verbrauch"
#define D_TPWRCURR1 "Verbrauch P1"
#define D_TPWRCURR2 "Verbrauch P2"
#define D_TPWRCURR3 "Verbrauch P3"
#define D_Strom_L1 "Strom L1"
#define D_Strom_L2 "Strom L2"
#define D_Strom_L3 "Strom L3"
#define D_Spannung_L1 "Spannung L1"
#define D_Spannung_L2 "Spannung L2"
#define D_Spannung_L3 "Spannung L3"
#define D_METERNR "Zähler Nr"
#define D_METERSID "Service ID"
#define D_GasIN "Zählerstand"                // Gas-Verbrauch
#define D_H2oIN "Zählerstand"                // H2o-Verbrauch
#define D_StL1L2L3 "Ströme L1+L2+L3"
#define D_SpL1L2L3 "Spannung L1+L2+L3/3"

#else
// other languages (tbd)
#undef D_TPWRIN
#undef D_TPWROUT
#undef D_TPWRCURR
#undef D_TPWRCURR1
#undef D_TPWRCURR2
#undef D_TPWRCURR3
#undef D_Strom_L1
#undef D_Strom_L2
#undef D_Strom_L3
#undef D_Spannung_L1
#undef D_Spannung_L2
#undef D_Spannung_L3
#undef D_METERNR
#undef D_METERSID
#undef D_GasIN
#undef D_H2oIN
#undef D_StL1L2L3
#undef D_SpL1L2L3

#define D_TPWRIN "Total-In"
#define D_TPWROUT "Total-Out"
#define D_TPWRCURR "Current-In/Out"
#define D_TPWRCURR1 "Current-In p1"
#define D_TPWRCURR2 "Current-In p2"
#define D_TPWRCURR3 "Current-In p3"
#define D_Strom_L1 "Current L1"
#define D_Strom_L2 "Current L2"
#define D_Strom_L3 "Current L3"
#define D_Spannung_L1 "Voltage L1"
#define D_Spannung_L2 "Voltage L2"
#define D_Spannung_L3 "Voltage L3"
#define D_METERNR "Meter_number"
#define D_METERSID "Service ID"
#define D_GasIN "Counter"                // Gas-Verbrauch
#define D_H2oIN "Counter"                // H2o-Verbrauch
#define D_StL1L2L3 "Current L1+L2+L3"
#define D_SpL1L2L3 "Voltage L1+L2+L3/3"

#endif
```
As it stands it won't work as pio users will add the language switch as compiler option undetectable by the code.

Only solution is to add translations to all language files and/or re-use already translated words.

**Comment by tiagofreire-pt** [comment] 2020-03-14 17:02
I'm able to translate this to Portuguese (pt-PT) and Spanish (es-ES). How can I contribute to?

**Comment by tiagofreire-pt** [comment] 2020-03-14 17:04
> 
> 
> This is caused by xsns_53_sml.ino. Disable define USE_SML_M and the messages will be gone.
> 

The Smart Meter wiki state that I need to define that var. Is the wiki correct?

**Comment by ascillato2** [comment] 2020-03-14 21:08
Closing as the PR has been made.

**Closed by ascillato2** 2020-03-14 21:08 UTC
Labels: bug, fixed
