### ISSUE TITLE
RFProtocol for Dooya 1602 remote

### ISSUE THREAD

**Issue by nosaj66au** [arendst/Tasmota#13054] opened 2021-09-04 05:35 UTC
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Try to use a DC1602 Dooya Remote with RFSwitch.  I have read the other cases on Dooya Remotes and I believe the 1603 is very similar. To confirm I have compiled the current version with the inclusion of RFRemote. I have tested 2 other remotes (not Dooya), which work correctly and display the received command.

My Question: I have researched the 1602 and it is also a 40bit protocol similar to 1603 (RC protocol 35 or 33) don't revieve work with 40 Bits on the 1603? Do I need to enable 40 reception ? I understand default is 24.      

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ yes] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ yes] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ yes] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ yes] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ yes] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ yes] Device used (e.g., Sonoff Basic): Generic
- [ yes] Tasmota binary firmware version number used: 0x09050007
  - [ ] Pre-compiled
  - [ yes] Self-compiled
- [ ] Flashing tools used: PlatformIO python
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
Not relevant

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
Not relevant

```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
Not relevant

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
Not relevant

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Not relevant

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
return an RF message to the console

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
This demonstrates the 2 working remotes, however the 1602 does not return anything
![image](https://user-images.githubusercontent.com/13111932/132083791-829ddc93-44a0-44c8-bcc3-9d27fb90875f.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-09-04 06:12
Moving this to discussions as this is a question and not a bug report.

**Closed** 2021-09-04 06:12 UTC
