### ISSUE TITLE
SwitchMode11 - New SetOption for disabling toggle action at Double-Click

### ISSUE THREAD

**Issue by Seestern93** [arendst/Tasmota#12712] opened 2021-07-21 07:55 UTC
### PROBLEM DESCRIPTION
Summary:
Feature Request for new SetOptionXXX to disable TOGGLE event at DOUBLE click with SwitchMode11 (and 12) to use the DOUBLE event without triggering the TOGGLE event.

Detailed:
For handling a dimmable LED over a wall switch I am currently using the SwitchMode11 for toggling the light (1x click => switch1#state=2) and for changing the brightness (hold = switch1#state=4 -> "-"; click + hold = switch1#state=5 -> "+"). Now I got a second light (not-dimmable) which I want to command over the same switch, therefore I implemented double-click feature -> 2x click = switch1#state=8 -> toggling light 2.
My problem now is, that with each double-click, the toggle action (switch1#state=2) from the single-click is also sent. That means, that I have to filter out the toggle event which makes things more complicated and less respsonsive. I checked several methods how to do, but the only thing which worked for me is using a ruletimer with 1s to delay the "single-click" to check whether the "double-click" event was executed within that time. That means that single-click is now delayed by (a little bit more than) 1s. (with backlog it did not work due to the backlog queue is always FIFO). 

For completeness, here are my full rules:
(mem1 is used as "-" and "+" switch)
(mem2 is used to check whether double-click happened -> 0; or not -> 1; which is checked at end of Ruletimer1)
(cmnd/tasmsw01/event togglepower is used to toggle the second light)

```lua
Rule1:
on system#boot do
	backlog mem1 -; mem2 0;
endon 
on switch1#state=2 do
	backlog Ruletimer1 1; mem2 1
endon 
on switch1#state=4 do
	Dimmer %mem1%
endon 
on switch1#state=5 do
	mem1 +
endon 
on switch1#state=6 do
	mem1 -
endon 
on switch1#state=8 do
	backlog mem2 0; publish cmnd/tasmsw01/event togglepower
endon

Rule2:
on Rules#Timer=1 do
	event togglepower=%mem2%
endon
on event#togglepower=1 do
	power1 toggle
endon
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Shelly Dimmer 2
- [x] Tasmota binary firmware version number used: Tasmota 9.2.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: OTA
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
08:44:31 CMD: Backlog Template; Module; GPIO 255
08:44:31 MQT: stat/tasmshdim01/RESULT = {"NAME":"Shelly Dimmer 2","GPIO":[0,3200,0,3232,5568,5600,0,0,0,0,192,0,320,4736],"FLAG":0,"BASE":18}
08:44:31 MQT: stat/tasmshdim01/RESULT = {"Module":{"0":"Shelly Dimmer 2"}}
08:44:32 MQT: stat/tasmshdim01/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"3200":"Serial Tx"},"GPIO2":{"0":"None"},"GPIO3":{"3232":"Serial Rx"},"GPIO4":{"5568":"SHD Boot 0"},"GPIO5":{"5600":"SHD Reset"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"192":"Switch_n1"},"GPIO15":{"0":"None"},"GPIO16":{"320":"Led_i1"},"GPIO17":{"4736":"ADC Temp"}}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
08:46:12 CMD: Backlog Rule1; Rule2; Rule3
08:46:12 MQT: stat/tasmshdim01/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":300,"Free":211,"Rules":"on system#boot do backlog mem1 -; mem2 0; endon on switch1#state=2 do backlog Ruletimer1 1; mem2 1 endon on switch1#state=4 do Dimmer %mem1% endon on switch1#state=5 do mem1 + endon on switch1#state=6 do mem1 - endon on switch1#state=8 do backlog mem2 0; publish cmnd/tasmsw01/event togglepower endon"}
08:46:12 MQT: stat/tasmshdim01/RESULT = {"Rule2":"ON","Once":"OFF","StopOnError":"OFF","Length":96,"Free":415,"Rules":"on Rules#Timer=1 do event togglepower=%mem2% ENDON on event#togglepower=1 do power1 toggle ENDON"}
08:46:12 MQT: stat/tasmshdim01/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
08:46:40 CMD: Status 0
08:46:40 MQT: stat/tasmshdim01/STATUS = {"Status":{"Module":0,"DeviceName":"tasmshdim01","FriendlyName":["tasmshdim01"],"Topic":"tasmshdim01","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"","SwitchMode":[11,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
08:46:40 MQT: stat/tasmshdim01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"0T12:25:16","StartupUTC":"2021-07-20T19:21:24","Sleep":50,"CfgHolder":4617,"BootCount":14,"BCResetTime":"2021-02-11T13:18:10","SaveCount":1664,"SaveAddress":"FA000"}}
08:46:41 MQT: stat/tasmshdim01/STATUS2 = {"StatusFWR":{"Version":"9.2.0(tasmota)","BuildDateTime":"2020-12-21T15:03:40","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"482/699"}}
08:46:41 MQT: stat/tasmshdim01/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Seestern-Homenet",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["8010800B","0505C8000100060000005A00000000000000","08800000","00006000","00000000"]}}
08:46:41 MQT: stat/tasmshdim01/STATUS4 = {"StatusMEM":{"ProgramSize":586,"Free":416,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"15701C","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
08:46:41 MQT: stat/tasmshdim01/STATUS5 = {"StatusNET":{"Hostname":"tasmshdim01","IPAddress":"10.69.0.47","Gateway":"10.69.0.1","Subnetmask":"255.255.240.0","DNSServer":"10.69.0.1","Mac":"D8:BF:C0:19:FD:E2","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
08:46:41 MQT: stat/tasmshdim01/STATUS6 = {"StatusMQT":{"MqttHost":"10.69.0.10","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_19FDE2","MqttUser":"raspberryMQTT","MqttCount":5,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
08:46:41 MQT: stat/tasmshdim01/STATUS7 = {"StatusTIM":{"UTC":"2021-07-21T07:46:41","Local":"2021-07-21T08:46:41","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"05:10","Sunset":"20:42"}}
08:46:41 MQT: stat/tasmshdim01/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
08:46:41 MQT: stat/tasmshdim01/STATUS10 = {"StatusSNS":{"Time":"2021-07-21T08:46:41","Switch1":"OFF","ANALOG":{"Temperature":44.3},"ENERGY":{"TotalStartTime":"2021-02-11T13:18:10","Total":0.093,"Yesterday":0.093,"Today":0.000,"Power":0},"TempUnit":"C"}}
08:46:41 MQT: stat/tasmshdim01/STATUS11 = {"StatusSTS":{"Time":"2021-07-21T08:46:41","Uptime":"0T12:25:17","UptimeSec":44717,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":5,"POWER":"OFF","Dimmer":37,"Fade":"ON","Speed":4,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"Seestern-Homenet","BSSId":"DC:39:6F:AB:C4:63","Channel":6,"RSSI":70,"Signal":-65,"LinkCount":8,"Downtime":"0T00:02:26"}}}


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
See steps to reproduce / expected behavior below

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

1. Set SwitchMode to 11
2. Double-Click the Switch button (should be a momentary switch)
3. Switch#state=2 (=TOGGLE) is sent together with Switch#state=8 (=DOUBLE)

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

1. Set new SetOptionXXX to 1
2. Execute steps 1 + 2 to reproduce behavior
3. Only Switch#state=8 (=DOUBLE) is sent

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment] 2021-07-21 10:12
Thanks for posting.

Moving to discussions as this is a feature request and not a bug report.

**Closed** 2021-07-21 10:12 UTC
Labels: feature request (devs?)
