### ISSUE TITLE
Sr04TModeDetect passes the wrong value to TasmotaSerial constructor when GPIO_SR04_TRIG is unused 

### ISSUE THREAD

**Issue by rossack** [arendst/Tasmota#16613] opened 2022-09-21 09:02 UTC
### PROBLEM DESCRIPTION
The ultrasonic sensor A02YYUW (DFRobot SKU:SEN0311) which uses a serial UART @ 9600 baud with 4 byte output does not work with sr04 module when the Tx line of the sensor is connected and the Rx line is unused (not needed, spec says it can be grounded or left floating). Suggested fix is described in Additional Context section.

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): QS-WIFI-S03 
- [x] Tasmota binary firmware version number used: 12.1.1
  - [x] Pre-compiled - tasmota-sensors.bin.gz
  - [x] Self-compiled -  to test the fix
- [x] Flashing tools used: OTA
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
8:17:11.979 CMD: Grp 0, Cmd 'BACKLOG', Idx 1, Len 27, Pld -99, Data 'Template; Module; GPIO 255:'
08:17:12.043 SRC: Backlog
08:17:12.046 CMD: Grp 0, Cmd 'TEMPLATE', Idx 1, Len 0, Pld -99, Data ''
08:17:12.053 MQT: Water_Tank/stat/RESULT = {"NAME":"RossTest","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
08:17:12.263 SRC: Backlog
08:17:12.265 CMD: Grp 0, Cmd 'MODULE', Idx 1, Len 0, Pld -99, Data ''
08:17:12.270 MQT: Water_Tank/stat/RESULT = {"Module":{"0":"RossTest"}}
08:17:12.715 SRC: Backlog
08:17:12.718 CMD: Grp 0, Cmd 'GPIO', Idx 1, Len 4, Pld 255, Data '255:'
08:17:12.728 MQT: Water_Tank/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"1888":"SR04 Ech/RX"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
08:21:50.866 CMD: status 0
08:21:50.868 SRC: WebConsole from 192.168.0.16
08:21:50.871 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 0, Data '0'
08:21:50.878 MQT: Water_Tank/stat/STATUS = {"Status":{"Module":0,"DeviceName":"WaterTank","FriendlyName":["Water Tank"],"Topic":"Water_Tank","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
08:21:50.887 MQT: Water_Tank/stat/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:51","StartupUTC":"2022-09-21T07:20:59","Sleep":50,"CfgHolder":4617,"BootCount":143,"BCResetTime":"2020-07-16T11:26:31","SaveCount":951,"SaveAddress":"FA000"}}
08:21:50.898 MQT: Water_Tank/stat/STATUS2 = {"StatusFWR":{"Version":"12.1.1(sensors)","BuildDateTime":"2022-09-21T05:40:35","Boot":4,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"375/699"}}
08:21:50.906 MQT: Water_Tank/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Wireless-BRm","Wireless-N"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00C28009","2805C80001000600003C5AFF002800000000","00000280","00006000","00004000","00000000"]}}
08:21:50.923 MQT: Water_Tank/stat/STATUS4 = {"StatusMEM":{"ProgramSize":681,"Free":320,"Heap":20,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440C8","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F9A8787","0415A005","B7F7BFCF","05DA9BC4","64367CC7","00084052","20000000","54000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,14,16,17,20,21,24,29,34,62","Sensors":"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,28,31,34,37,39,40,42,43,45,51,52,55,56,58,59,62,64,66,67,74"}}
08:21:50.932 MQT: Water_Tank/stat/STATUS5 = {"StatusNET":{"Hostname":"Water-Tank-3304","IPAddress":"192.168.0.52","Gateway":"192.168.0.254","Subnetmask":"255.255.254.0","DNSServer1":"192.168.0.254","DNSServer2":"0.0.0.0","Mac":"68:C6:3A:E4:AC:E8","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
08:21:50.939 MQT: Water_Tank/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.9","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_E4ACE8","MqttUser":"ross","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
08:21:50.947 MQT: Water_Tank/stat/STATUS7 = {"StatusTIM":{"UTC":"2022-09-21T07:21:50","Local":"2022-09-21T08:21:50","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"06:35","Sunset":"18:50"}}
08:21:50.956 MQT: Water_Tank/stat/STATUS10 = {"StatusSNS":{"Time":"2022-09-21T08:21:50"}}
08:21:50.964 MQT: Water_Tank/stat/STATUS11 = {"StatusSTS":{"Time":"2022-09-21T08:21:50","Uptime":"0T00:00:51","UptimeSec":51,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":61,"MqttCount":1,"Wifi":{"AP":2,"SSId":"Wireless-N","BSSId":"7C:10:C9:3B:69:C0","Channel":5,"Mode":"11n","RSSI":82,"Signal":-59,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
00:00:00.001 HDW: ESP8266EX
00:00:00.050 CFG: Loaded from flash at FB, Count 952
00:00:00.056 QPC: Count 1
00:00:00.058 CFG: CR 375/699, Busy 0
00:00:00.063 ROT: Mode 1
00:00:00.065 SRC: Restart
00:00:00.067 Project tasmota - WaterTank Version 12.1.1(sensors)-2_7_4_9(2022-08-25T11:37:09)
00:00:00.362 WIF: Checking connection...
00:00:00.363 WIF: Attempting connection...
00:00:00.700 WIF: Connecting to AP2 Wireless-N Channel 5 BSSId 7C:10:C9:3B:69:C0 in mode 11n as Water-Tank-3304...
00:00:01.378 SR4: Mode 2
00:00:01.528 WIF: Checking connection...
00:00:01.529 WIF: Attempting connection...
00:00:01.532 RSL: RESULT = {"SerialReceived":"FF06B5BAFF06B6BBFF06B6BBFF06BEC3FF06B6BBFF06B6BBFF06B1B6FF06B1B6FF06B6BBFF06B6BBFF06B1B6FF06BABFFF06B6BBFF06B6BBFF06B6BBFF06B6BBFF06B6BBFF06B1B6FF06B6BBFF06BEC3FF06B6BBFF06B6BB00"}
00:00:02.835 WIF: Checking connection...
00:00:02.836 WIF: Attempting connection...
00:00:04.039 WIF: Checking connection...
00:00:04.040 WIF: Connected
00:00:04.293 HTP: Web server active on Water-Tank-3304 with IP address 192.168.0.52
00:00:04.391 WIF: Sending Gratuitous ARP
00:00:04.392 NTP: Sync time...
00:00:04.447 RTC: UTC 2022-09-21T07:26:16, DST 2022-03-27T02:00:00, STD 2022-10-30T03:00:00
08:26:16.000 RTC: Synced by NTP
08:26:16.311 HTP: Firmware Upgrade
08:26:17.707 MQT: Attempting connection...
08:26:17.720 MQT: Connected
08:26:17.723 MQT: Water_Tank/tele/LWT = Online (retained)
08:26:17.725 MQT: Water_Tank/cmnd/POWER = 
08:26:17.726 MQT: Subscribe to Water_Tank/cmnd/#
08:26:17.729 MQT: Subscribe to sonoffs/cmnd/#
08:26:17.733 MQT: Subscribe to cmnd/DVES_E4ACE8_fb/#
08:26:17.740 MQT: Water_Tank/tele/INFO1 = {"Info1":{"Module":"RossTest","Version":"12.1.1(sensors)","FallbackTopic":"cmnd/DVES_E4ACE8_fb/","GroupTopic":"sonoffs/cmnd/"}}
08:26:17.744 MQT: Water_Tank/tele/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"Water-Tank-3304","IPAddress":"192.168.0.52"}}
08:26:17.749 MQT: Water_Tank/tele/INFO3 = {"Info3":{"RestartReason":"Software/System restart","BootCount":144}}
08:26:18.453 QPC: Reset
08:26:18.758 SRC: MQTT
08:26:18.760 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 1, Data '1'
08:26:18.767 MQT: Water_Tank/stat/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:08","StartupUTC":"2022-09-21T07:26:10","Sleep":50,"CfgHolder":4617,"BootCount":143,"BCResetTime":"2020-07-16T11:26:31","SaveCount":952,"SaveAddress":"FB000"}}
08:26:18.808 SRC: MQTT

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Connect the Tx line of A02YYUW ultrasonic sensor (DFRobot as SKU:SEN0311) to the RX GPIO3 input pin
The Rx line of of A02YYUW can be grounded or left floating, its not required by Sr04 module
Module configuration using Generic (18): RX GPIO3 = SR04 Ech/RX 

### EXPECTED BEHAVIOUR
The web page should display distance values: <html>
<body>  SR04 Distance      189.600 cm  </body>
</html> 

But no values are being read from the serial port so nothing is displayed

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
On startup, serial data is being received (see log output) but when Sr04TModeDetect() function is called in xsns_22_sr04.ino the constructor for TasmotaSerial is passed the wrong value for sr04_trig_pin.  TasmotaSerial checks which GPIO pins are assigned to decide if hardware_fallback is available by comparing with -1 if pin is not assigned. To fix this (in xsns_22_sr04.ino) the value of sr04_trig_pin needs to be -1 then it all works fine.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by rossack** [comment] 2022-09-26 23:33
Fix solves the problem. 
MQT: Water_Tank/tele/SENSOR = {"Time":"2022-09-27T00:27:34","SR04":{"Distance":84.700}}
Thanks.

**Comment by rossack** [comment] 2022-09-27 00:36
Forgot to mention the occasional CRC errors, probably due to the driver making the call to empty the input buffer while the sensor is transmitting and no attempt to sync with the 0xFF header byte. Only relevant to serial 4 byte sensors. Suggest its not worth worrying about, unless someone needs reliable high frequency sensor readings.

**Comment by Jason2866** [comment] 2022-09-29 17:58
Closing since the issue is fixed

**Closed by Jason2866** 2022-09-29 17:58 UTC
Labels: troubleshooting
